// packages/svelte/src/lib/components/Accelerator/AcceleratorProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import {
    createAcceleratorRegistry,
    detectPlatform,
    type AcceleratorPlatform,
    type AcceleratorRegistry,
  } from '@larose-ui/core';
  import { setAcceleratorContext, type AcceleratorContextValue } from '../../accelerator/context';

  let { platform, children }: { platform?: AcceleratorPlatform; children?: Snippet } = $props();

  const registry: AcceleratorRegistry = createAcceleratorRegistry();
  const resolvedPlatform = platform ?? detectPlatform();
  let activeMenuId: string | null = null;
  const menuHandlers = new Map<string, (event: KeyboardEvent) => boolean>();

  const value: AcceleratorContextValue = {
    registry,
    platform: resolvedPlatform,
    registerMenuHandler(id, handler) {
      menuHandlers.set(id, handler);
      return () => {
        menuHandlers.delete(id);
      };
    },
    setActiveMenuId(id) {
      activeMenuId = id;
    },
  };

  setAcceleratorContext(value);

  $effect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (activeMenuId) {
        const menuHandler = menuHandlers.get(activeMenuId);
        if (menuHandler?.(event)) return;
      }
      registry.handleEvent(event, {
        platform: resolvedPlatform,
        scopes: ['component', 'global'],
        target: event.target,
      });
    };
    window.addEventListener('keydown', onKeyDown, true);
    return () => window.removeEventListener('keydown', onKeyDown, true);
  });
</script>

{@render children?.()}

// packages/vue/src/components/Accelerator/AcceleratorProvider.vue
<script setup lang="ts">
import { onMounted, onUnmounted, provide } from 'vue';
import type { AcceleratorPlatform } from '@larose-ui/core';
import {
  acceleratorKey,
  createAcceleratorContextValue,
} from '../../composables/useAccelerator';

const props = defineProps<{ platform?: AcceleratorPlatform }>();
const context = createAcceleratorContextValue(props.platform);
provide(acceleratorKey, context);

let detach: (() => void) | undefined;

onMounted(() => {
  const onKeyDown = (event: KeyboardEvent) => {
    const activeMenuId = context.activeMenuId.current;
    if (activeMenuId) {
      const menuHandler = context.menuHandlers.get(activeMenuId);
      if (menuHandler?.(event)) return;
    }
    context.registry.handleEvent(event, {
      platform: context.platform,
      scopes: ['component', 'global'],
      target: event.target,
    });
  };
  window.addEventListener('keydown', onKeyDown, true);
  detach = () => window.removeEventListener('keydown', onKeyDown, true);
});

onUnmounted(() => detach?.());
</script>

<template>
  <slot />
</template>
