// packages/svelte/src/lib/components/Accelerator/MnemonicLabel.svelte
<script lang="ts">
  import { parseMnemonicLabel, resolveMnemonicKey } from '@larose-ui/core';
  import styles from '@larose-ui/styles/components/Menu/Menu.module.css';

  let {
    label,
    mnemonic,
    showAccessKey = false,
    class: className,
    style,
  }: {
    label: string;
    mnemonic?: string;
    showAccessKey?: boolean;
    class?: string;
    style?: string;
  } = $props();

  const parsed = $derived(parseMnemonicLabel(label));
  const accessKey = $derived(resolveMnemonicKey(label, mnemonic) ?? parsed.mnemonicKey);
  const display = $derived(parsed.displayLabel);
  const index = $derived(
    showAccessKey && accessKey ? display.toLowerCase().indexOf(accessKey.toLowerCase()) : -1,
  );
</script>

{#if !showAccessKey || !accessKey || index === -1}
  <span class={className} {style}>{display}</span>
{:else}
  <span class={className} {style}>
    {display.slice(0, index)}<span class={styles.mnemonicChar}>{display.charAt(index)}</span
    >{display.slice(index + 1)}
  </span>
{/if}

// packages/vue/src/components/Accelerator/MnemonicLabel.vue
<script setup lang="ts">
import { computed } from 'vue';
import { parseMnemonicLabel, resolveMnemonicKey } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/Menu/Menu.module.css';
import { cn } from '../../utils/cn';

const props = withDefaults(
  defineProps<{
    label: string;
    mnemonic?: string;
    showAccessKey?: boolean;
    class?: string;
    style?: Record<string, string | number>;
  }>(),
  { showAccessKey: false },
);

const parts = computed(() => {
  const parsed = parseMnemonicLabel(props.label);
  const accessKey = resolveMnemonicKey(props.label, props.mnemonic) ?? parsed.mnemonicKey;
  const display = parsed.displayLabel;
  if (!props.showAccessKey || !accessKey) {
    return { before: display, char: '', after: '' };
  }
  const index = display.toLowerCase().indexOf(accessKey.toLowerCase());
  if (index === -1) return { before: display, char: '', after: '' };
  return {
    before: display.slice(0, index),
    char: display.charAt(index),
    after: display.slice(index + 1),
  };
});
</script>

<template>
  <span :class="cn(props.class)" :style="props.style">
    {{ parts.before }}<span v-if="parts.char" :class="styles.mnemonicChar">{{ parts.char }}</span>{{ parts.after }}
  </span>
</template>
