// packages/react/src/ImageView/ImageOverlay.tsx
import type { ReactNode } from 'react';
import { ImageView, type ImageViewProps } from './ImageView';
import styles from '@larose-ui/styles/components/ImageView/ImageView.module.css';

export interface ImageOverlayProps extends Omit<ImageViewProps, 'children'> {
  overlay: ReactNode;
}

/**
 * Image with legible text overlay — scrim improves contrast per Apple HIG.
 * @see https://developer.apple.com/design/human-interface-guidelines/image-views
 */
export function ImageOverlay({ overlay, alt, ...imageProps }: ImageOverlayProps) {
  return (
    <figure className={styles.overlay}>
      <ImageView {...imageProps} alt={alt} className={styles.overlayImage} fit="cover" />
      <div className={styles.overlayScrim} aria-hidden="true" />
      <figcaption className={styles.overlayContent}>{overlay}</figcaption>
    </figure>
  );
}

// packages/svelte/src/lib/components/ImageView/ImageOverlay.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/ImageView/ImageView.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    src: string;
    alt: string;
    class?: string;
    style?: string;
    children?: Snippet;
  }

  let { src, alt, class: className, style, children }: Props = $props();
</script>

<div class={cn(styles.overlay, className)} {style}>
  <img {src} {alt} class={styles.overlayImage} />
  <div class={styles.overlayScrim} aria-hidden="true"></div>
  <div class={styles.overlayContent}>{#if children}{@render children()}{/if}</div>
</div>
