// packages/react/src/ImageView/ImageButton.tsx
import type { ButtonHTMLAttributes, ImgHTMLAttributes } from 'react';
import styles from '@larose-ui/styles/components/ImageView/ImageView.module.css';

export interface ImageButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  src: string;
  alt: string;
  imageProps?: Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'alt'>;
}

/**
 * Clickable image — use instead of adding button behavior to a plain image view.
 * @see https://developer.apple.com/design/human-interface-guidelines/image-views
 */
export function ImageButton({ src, alt, imageProps, className, ...props }: ImageButtonProps) {
  return (
    <button type="button" className={[styles.imageButton, className].filter(Boolean).join(' ')} {...props}>
      <img src={src} alt={alt} className={styles.imageButtonImage} {...imageProps} />
    </button>
  );
}

// packages/svelte/src/lib/components/ImageView/ImageButton.svelte
<script lang="ts">
  import styles from '@larose-ui/styles/components/ImageView/ImageView.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    src: string;
    alt: string;
    class?: string;
    style?: string;
    ariaLabel?: string;
    onclick?: () => void;
  }

  let { src, alt, class: className, style, ariaLabel, onclick }: Props = $props();
</script>

<button type="button" class={cn(styles.imageButton, className)} {style} aria-label={ariaLabel ?? alt} {onclick}>
  <img {src} {alt} class={styles.imageButtonImage} />
</button>
