// packages/forms-vue/src/Form.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { Alert, Button, Input, Select, Textarea } from '@larose-ui/vue';
import {
  getVisibleFields,
  validateForm,
  type FormSchema,
  type FormValues,
} from '@larose-ui/forms-core';
import {
  apiFetch,
  isApiError,
  type ApiFetchOptions,
} from '@larose-ui/data-core';
import {
  useOptionalObservability,
  markFormSubmitted,
  trackFormSuccess,
  trackFormError,
  trackFormValidationFailed,
} from '@larose-ui/observability-vue';
import type { ApiError } from '@larose-ui/core';
import styles from './Form.module.css';

const props = withDefaults(
  defineProps<{
    schema: FormSchema;
    initialValues?: FormValues;
    submitUrl?: string;
    submitLabel?: string;
  }>(),
  {
    initialValues: () => ({}),
    submitLabel: 'Save',
  },
);

const emit = defineEmits<{
  submit: [values: FormValues];
}>();

const values = ref<FormValues>({ ...props.initialValues });
const errors = ref<Record<string, string>>({});
const touched = ref<Record<string, boolean>>({});
const submitting = ref(false);
const serverError = ref<ApiError | null>(null);
const observability = useOptionalObservability();
const formName = computed(() => props.schema.id);

const visibleFields = computed(() => getVisibleFields(props.schema, values.value));

function handleChange(name: string, value: string) {
  values.value = { ...values.value, [name]: value };
  touched.value = { ...touched.value, [name]: true };
}

async function handleSubmit(event: Event) {
  event.preventDefault();
  const validationErrors = validateForm(props.schema, values.value);
  errors.value = validationErrors;
  if (Object.keys(validationErrors).length > 0) {
    if (observability) {
      trackFormValidationFailed(
        formName.value,
        observability.track,
        Object.keys(validationErrors),
      );
    }
    return;
  }

  if (observability) {
    markFormSubmitted(formName.value, observability.track);
  }

  submitting.value = true;
  serverError.value = null;
  try {
    if (props.submitUrl) {
      await apiFetch(props.submitUrl, {
        method: 'POST',
        body: JSON.stringify(values.value),
      } satisfies ApiFetchOptions);
    }
    emit('submit', values.value);
    if (observability) {
      trackFormSuccess(formName.value, observability.track);
    }
  } catch (err) {
    serverError.value = isApiError(err)
      ? err.apiError
      : { code: 500, message: 'Submit failed', retryable: true };
    if (observability) {
      trackFormError(
        formName.value,
        observability.track,
        serverError.value.message,
      );
    }
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <form :class="styles.form" :data-form-id="schema.id" @submit="handleSubmit">
    <h2 v-if="schema.title" :class="styles.title">{{ schema.title }}</h2>

    <Alert v-if="serverError" variant="error" title="Save failed">
      {{ serverError.message }}
    </Alert>

    <div v-for="field in visibleFields" :key="field.name">
      <Select
        v-if="field.type === 'select'"
        :label="field.label"
        :model-value="values[field.name] ?? ''"
        :options="field.options ?? []"
        :error="touched[field.name] ? errors[field.name] : undefined"
        @update:model-value="handleChange(field.name, $event)"
      />
      <Textarea
        v-else-if="field.type === 'textarea'"
        :label="field.label"
        :model-value="values[field.name] ?? ''"
        :placeholder="field.placeholder"
        :hint="field.hint"
        :error="touched[field.name] ? errors[field.name] : undefined"
        @update:model-value="handleChange(field.name, $event)"
      />
      <Input
        v-else
        :label="field.label"
        :type="field.type === 'number' ? 'number' : field.type"
        :model-value="values[field.name] ?? ''"
        :placeholder="field.placeholder"
        :hint="field.hint"
        :error="touched[field.name] ? errors[field.name] : undefined"
        @update:model-value="handleChange(field.name, $event)"
      />
    </div>

    <div :class="styles.actions">
      <Button type="submit" :loading="submitting">{{ submitLabel }}</Button>
    </div>
  </form>
</template>

// packages/forms/src/Form.tsx
import { useCallback, useMemo, useState, type FormEvent } from 'react';
import { Input, Button, Alert, Textarea, Select } from '@larose-ui/react';
import { useMutation } from '@larose-ui/data';
import {
  useOptionalObservability,
  markFormSubmitted,
  trackFormSuccess,
  trackFormError,
  trackFormValidationFailed,
} from '@larose-ui/observability';
import type { ApiError } from '@larose-ui/core';
import {
  getVisibleFields,
  validateForm,
  type FormSchema,
  type FormValues,
} from './schema';
import styles from './Form.module.css';

export interface FormProps {
  schema: FormSchema;
  initialValues?: FormValues;
  submitUrl?: string;
  onSubmit?: (values: FormValues) => Promise<void> | void;
  submitLabel?: string;
}

export function Form({
  schema,
  initialValues = {},
  submitUrl,
  onSubmit,
  submitLabel = 'Save',
}: FormProps) {
  const [values, setValues] = useState<FormValues>(initialValues);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [localSubmitting, setLocalSubmitting] = useState(false);
  const observability = useOptionalObservability();
  const formName = schema.id;

  const mutation = useMutation<unknown, FormValues>({
    url: submitUrl ?? '/__larose_noop__',
    method: 'POST',
  });

  const visibleFields = useMemo(
    () => getVisibleFields(schema, values),
    [schema, values],
  );

  const handleChange = useCallback((name: string, value: string) => {
    setValues((prev) => ({ ...prev, [name]: value }));
    setTouched((prev) => ({ ...prev, [name]: true }));
  }, []);

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault();
      const validationErrors = validateForm(schema, values);
      setErrors(validationErrors);
      if (Object.keys(validationErrors).length > 0) {
        if (observability) {
          trackFormValidationFailed(
            formName,
            observability.track,
            Object.keys(validationErrors),
          );
        }
        return;
      }

      if (observability) {
        markFormSubmitted(formName, observability.track);
      }

      if (onSubmit) {
        setLocalSubmitting(true);
        try {
          await onSubmit(values);
          if (observability) trackFormSuccess(formName, observability.track);
        } catch (err) {
          if (observability) {
            trackFormError(
              formName,
              observability.track,
              err instanceof Error ? err.message : 'Submit failed',
            );
          }
          throw err;
        } finally {
          setLocalSubmitting(false);
        }
      } else if (submitUrl) {
        const result = await mutation.mutate(values);
        if (mutation.error && observability) {
          trackFormError(formName, observability.track, mutation.error.message);
        } else if (result !== undefined && observability) {
          trackFormSuccess(formName, observability.track);
        }
      }
    },
    [schema, values, onSubmit, submitUrl, mutation, observability, formName],
  );

  const serverError = submitUrl ? (mutation.error as ApiError | null) : null;
  const isSubmitting = localSubmitting || mutation.status === 'submitting';

  return (
    <form className={styles.form} onSubmit={handleSubmit} data-form-id={schema.id}>
      {schema.title && <h2 className={styles.title}>{schema.title}</h2>}

      {serverError && (
        <Alert variant="error" title="Save failed">
          {serverError.message}
        </Alert>
      )}

      {visibleFields.map((field) => (
        <div key={field.name}>
          {field.type === 'select' ? (
            <Select
              label={field.label}
              name={field.name}
              value={values[field.name] ?? ''}
              onChange={(e) => handleChange(field.name, e.target.value)}
              options={field.options ?? []}
              error={touched[field.name] ? errors[field.name] : undefined}
            />
          ) : field.type === 'textarea' ? (
            <Textarea
              label={field.label}
              name={field.name}
              value={values[field.name] ?? ''}
              onChange={(e) => handleChange(field.name, e.target.value)}
              placeholder={field.placeholder}
              error={touched[field.name] ? errors[field.name] : undefined}
              hint={field.hint}
            />
          ) : (
            <Input
              label={field.label}
              name={field.name}
              type={field.type === 'number' ? 'number' : field.type}
              value={values[field.name] ?? ''}
              onChange={(e) => handleChange(field.name, e.target.value)}
              hint={field.hint}
              error={touched[field.name] ? errors[field.name] : undefined}
              placeholder={field.placeholder}
            />
          )}
        </div>
      ))}

      <div className={styles.actions}>
        <Button type="submit" loading={isSubmitting}>
          {submitLabel}
        </Button>
      </div>
    </form>
  );
}
