// packages/runtime-svelte/src/network/NetworkProvider.svelte
<script lang="ts">
  import { onDestroy, onMount, type Snippet } from 'svelte';
  import type { NetworkMonitor } from '@larose-ui/network';
  import { createNetworkStore, setNetworkContext } from './context';

  interface Props {
    monitor?: NetworkMonitor;
    children?: Snippet;
  }

  let { monitor, children }: Props = $props();
  const network = createNetworkStore(monitor);
  setNetworkContext(network.state, network.monitor);
  onMount(() => network.mount());
  onDestroy(() => network.destroy());
</script>

{@render children?.()}

// packages/runtime-vue/src/network/NetworkProvider.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import type { NetworkMonitor } from '@larose-ui/network';
import { provideNetwork } from './context';

const props = defineProps<{ monitor?: NetworkMonitor }>();
const network = provideNetwork(props.monitor);

onMounted(() => network.mount());
onUnmounted(() => network.unmount());
</script>

<template>
  <slot />
</template>
