// packages/data-vue/src/DataView.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue';
import { getRetryDelay } from '@larose-ui/data-core';
import { useQuery } from './useQuery';

const props = withDefaults(
  defineProps<{
    url: string;
    enabled?: boolean;
    permissionAllowed?: boolean;
    baseUrl?: string;
  }>(),
  {
    enabled: true,
    permissionAllowed: true,
  },
);

const urlRef = computed(() => props.url);
const query = useQuery(urlRef, {
  enabled: props.enabled,
  permissionAllowed: computed(() => props.permissionAllowed),
  baseUrl: props.baseUrl,
});
const { status, data, error, isEmpty, retryCount, refetch, retry } = query;

const countdown = ref<number | null>(null);
let timer: ReturnType<typeof setInterval> | null = null;

function clearCountdown() {
  if (timer) {
    clearInterval(timer);
    timer = null;
  }
  countdown.value = null;
}

watch(
  () => [error.value, status.value, retryCount.value] as const,
  ([err, currentStatus]) => {
    clearCountdown();
    if (currentStatus !== 'error' || !err || err.code !== 429 || !err.retryable) return;
    const delay = Math.ceil(getRetryDelay(retryCount.value, 2000) / 1000);
    countdown.value = delay;
    timer = setInterval(() => {
      if (countdown.value === null || countdown.value <= 1) {
        clearCountdown();
        void retry();
        return;
      }
      countdown.value -= 1;
    }, 1000);
  },
);

onUnmounted(clearCountdown);

defineExpose({ refetch, retry });
</script>

<template>
  <div v-if="status === 'loading' || status === 'idle'">
    <slot name="loading">
      <div role="status" aria-busy="true" style="padding: var(--lr-space-4)">Loading...</div>
    </slot>
  </div>

  <div v-else-if="status === 'unauthorized'">
    <slot name="unauthorized">
      <div role="alert" style="padding: var(--lr-space-4); color: var(--lr-color-error)">
        You do not have permission to view this data.
      </div>
    </slot>
  </div>

  <div v-else-if="status === 'error' && error" role="alert" :data-lr-error="error.code">
    <p style="color: var(--lr-color-error); margin-bottom: var(--lr-space-2)">
      {{ error.message }}
    </p>
    <button v-if="error.retryable && error.code !== 429" type="button" @click="retry()">
      Retry
    </button>
    <p
      v-if="countdown !== null"
      style="font-size: var(--lr-font-size-sm); color: var(--lr-color-text-muted)"
    >
      Retrying in {{ countdown }}s...
    </p>
  </div>

  <div v-else-if="isEmpty">
    <slot name="empty">
      <div role="status" style="padding: var(--lr-space-4); color: var(--lr-color-text-muted)">
        No data found
      </div>
    </slot>
  </div>

  <slot v-else-if="data !== null" :data="data" :refetch="refetch" />
</template>

// packages/data-svelte/src/DataView.svelte
<script lang="ts">
  import { getRetryDelay, isQueryEmpty } from '@larose-ui/data-core';
  import { createQuery, type CreateQueryOptions } from './createQuery';
  import type { Snippet } from 'svelte';

  type Props = CreateQueryOptions<unknown> & {
    url: string;
    children?: Snippet<[unknown, () => Promise<void>]>;
    loading?: Snippet;
    empty?: Snippet;
    unauthorized?: Snippet;
  };

  let { url, children, loading, empty, unauthorized, ...queryOptions }: Props = $props();

  const query = createQuery(() => url, queryOptions);
  let countdown = $state<number | null>(null);

  $effect(() => {
    const snapshot = $query;
    if (snapshot.status !== 'error' || !snapshot.error || snapshot.error.code !== 429 || !snapshot.error.retryable) {
      countdown = null;
      return;
    }
    const delay = Math.ceil(getRetryDelay(snapshot.retryCount, 2000) / 1000);
    countdown = delay;
    const timer = setInterval(() => {
      if (countdown === null || countdown <= 1) {
        clearInterval(timer);
        countdown = null;
        void query.retry();
        return;
      }
      countdown -= 1;
    }, 1000);
    return () => clearInterval(timer);
  });
</script>

{#if $query.status === 'loading' || $query.status === 'idle'}
  {#if loading}
    {@render loading()}
  {:else}
    <div role="status" aria-busy="true" style="padding: var(--lr-space-4)">Loading...</div>
  {/if}
{:else if $query.status === 'unauthorized'}
  {#if unauthorized}
    {@render unauthorized()}
  {:else}
    <div role="alert" style="padding: var(--lr-space-4); color: var(--lr-color-error)">
      You do not have permission to view this data.
    </div>
  {/if}
{:else if $query.status === 'error' && $query.error}
  <div role="alert" data-lr-error={$query.error.code}>
    <p style="color: var(--lr-color-error); margin-bottom: var(--lr-space-2)">{$query.error.message}</p>
    {#if $query.error.retryable && $query.error.code !== 429}
      <button type="button" onclick={() => query.retry()}>Retry</button>
    {/if}
    {#if countdown !== null}
      <p style="font-size: var(--lr-font-size-sm); color: var(--lr-color-text-muted)">
        Retrying in {countdown}s...
      </p>
    {/if}
  </div>
{:else if isQueryEmpty($query.status, $query.data)}
  {#if empty}
    {@render empty()}
  {:else}
    <div role="status" style="padding: var(--lr-space-4); color: var(--lr-color-text-muted)">
      No data found
    </div>
  {/if}
{:else if $query.data !== null && children}
  {@render children($query.data, query.refetch)}
{/if}
