// packages/vue/src/components/Radio/Radio.vue
<script setup lang="ts">
import type { Size } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/Radio/Radio.module.css';
import { cn } from '../../utils/cn';

const props = withDefaults(
  defineProps<{
    label: string;
    hint?: string;
    error?: string | null;
    disabled?: boolean;
    boxSize?: Size;
    id?: string;
    name?: string;
    value?: string;
    class?: string;
    modelValue?: string;
  }>(),
  {
    error: null,
    boxSize: 'md',
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
  change: [event: Event];
}>();

const inputId = props.id ?? props.label.toLowerCase().replace(/\s+/g, '-');
</script>

<template>
  <div :class="styles.wrapper" :data-state="error ? 'error' : 'default'">
    <label :for="inputId" :class="styles.row">
      <input
        :id="inputId"
        type="radio"
        :name="name"
        :value="value"
        :class="cn(styles.input, props.class)"
        :data-size="boxSize"
        :disabled="disabled"
        :checked="modelValue === value"
        :aria-invalid="Boolean(error)"
        :aria-describedby="error ? `${inputId}-error` : hint ? `${inputId}-hint` : undefined"
        @change="
          emit('update:modelValue', ($event.target as HTMLInputElement).value);
          emit('change', $event);
        "
      />
      <span :class="styles.label">{{ label }}</span>
    </label>
    <span v-if="hint && !error" :id="`${inputId}-hint`" :class="styles.hint">{{ hint }}</span>
    <span v-if="error" :id="`${inputId}-error`" :class="styles.error" role="alert">{{ error }}</span>
  </div>
</template>

// packages/react/src/Radio/Radio.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import type { Size } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/Radio/Radio.module.css';

export interface RadioProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  label: string;
  hint?: string;
  error?: string | null;
  boxSize?: Size;
}

export const Radio = forwardRef<HTMLInputElement, RadioProps>(
  (
    { label, hint, error = null, disabled, boxSize = 'md', className, style, id, ...props },
    ref,
  ) => {
    const inputId = id ?? label.toLowerCase().replace(/\s+/g, '-');
    const errorMessage = typeof error === 'string' ? error : null;

    return (
      <div className={styles.wrapper} style={style} data-state={errorMessage ? 'error' : 'default'}>
        <label htmlFor={inputId} className={styles.row}>
          <input
            ref={ref}
            id={inputId}
            type="radio"
            className={[styles.input, className].filter(Boolean).join(' ')}
            data-size={boxSize}
            disabled={disabled}
            aria-invalid={Boolean(errorMessage)}
            aria-describedby={
              errorMessage ? `${inputId}-error` : hint ? `${inputId}-hint` : undefined
            }
            {...props}
          />
          <span className={styles.label}>{label}</span>
        </label>
        {hint && !errorMessage && (
          <span id={`${inputId}-hint`} className={styles.hint}>
            {hint}
          </span>
        )}
        {errorMessage && (
          <span id={`${inputId}-error`} className={styles.error} role="alert">
            {errorMessage}
          </span>
        )}
      </div>
    );
  },
);

Radio.displayName = 'Radio';
