// packages/vue/src/components/ListTable/ListSection.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/ListTable/ListTable.module.css';
import { cn } from '../../utils/cn';
defineProps<{ header?: string; footer?: string; class?: string; style?: Record<string, string | number> }>();
</script>
<template>
  <section :class="cn(styles.section, $props.class)" :style="$props.style">
    <h3 v-if="header" :class="styles.sectionHeader">{{ header }}</h3>
    <ul :class="styles.sectionBody"><slot /></ul>
    <p v-if="footer" :class="styles.sectionFooter">{{ footer }}</p>
  </section>
</template>

// packages/react/src/ListTable/ListSection.tsx
import type { ReactNode } from 'react';
import styles from '@larose-ui/styles/components/ListTable/ListTable.module.css';

export interface ListSectionProps {
  header?: string;
  footer?: string;
  children: ReactNode;
}

export function ListSection({ header, footer, children }: ListSectionProps) {
  return (
    <section className={styles.section}>
      {header && <h3 className={styles.sectionHeader}>{header}</h3>}
      <ul className={styles.sectionBody}>{children}</ul>
      {footer && <p className={styles.sectionFooter}>{footer}</p>}
    </section>
  );
}
