// packages/vue/src/components/ListTable/List.vue
<script setup lang="ts">
import type { ListVariant } from '../../ListTable/types';
import styles from '@larose-ui/styles/components/ListTable/ListTable.module.css';
import { cn } from '../../utils/cn';
withDefaults(defineProps<{ variant?: ListVariant; class?: string; style?: Record<string, string | number>; 'aria-label'?: string }>(), { variant: 'grouped' });
</script>
<template>
  <div :class="cn(styles.list, $props.class)" :style="$props.style" :data-variant="variant" role="list" :aria-label="$props['aria-label']"><slot /></div>
</template>

// packages/react/src/ListTable/List.tsx
import type { ReactNode } from 'react';
import type { ListVariant } from './types';
import styles from '@larose-ui/styles/components/ListTable/ListTable.module.css';

export interface ListProps {
  variant?: ListVariant;
  children: ReactNode;
  className?: string;
  'aria-label'?: string;
}

export function List({
  variant = 'grouped',
  children,
  className,
  'aria-label': ariaLabel,
}: ListProps) {
  return (
    <div
      className={[styles.list, className].filter(Boolean).join(' ')}
      data-variant={variant}
      role="list"
      aria-label={ariaLabel}
    >
      {children}
    </div>
  );
}
