// packages/svelte/src/lib/components/Disclosure/DisclosureGroup.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Disclosure/Disclosure.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    class?: string;
    style?: string;
    children?: Snippet;
  }

  let { class: className, style, children }: Props = $props();
</script>

<div class={cn(styles.group, className)} {style}>
  {#if children}{@render children()}{/if}
</div>

// packages/vue/src/components/Disclosure/DisclosureGroup.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Disclosure/Disclosure.module.css';
import { cn } from '../../utils/cn';

defineProps<{ class?: string; style?: CSSProperties }>();
</script>

<template>
  <div :class="cn(styles.group, $props.class)" :style="$props.style">
    <slot />
  </div>
</template>
