// packages/react/src/Chart/Chart.tsx
import {
  useCallback,
  useId,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type PointerEvent,
} from 'react';
import { CHART_SERIES_COLORS } from '@larose-ui/tokens';
import type {
  ChartAxisConfig,
  ChartDataPoint,
  ChartLegendItem,
  ChartMark,
  ChartSeries,
  PointShape,
} from './types';
import {
  DEFAULT_PADDING,
  buildLinePath,
  collectXValues,
  collectYValues,
  defaultAccessibilityLabel,
  formatDefaultNumber,
  nearestPointIndex,
  niceTicks,
  resolveYDomain,
  xBandIndex,
  yToPixel,
} from './utils';
import styles from '@larose-ui/styles/components/Chart/Chart.module.css';

export interface ChartProps {
  /** Chart mark type — bar, line, or point. */
  mark?: ChartMark;
  /** Single-series shorthand. */
  data?: ChartDataPoint[];
  /** One or more data series. */
  series?: ChartSeries[];
  title?: string;
  subtitle?: string;
  annotation?: string;
  /** High-level summary for assistive technologies (Apple Audio Graphs pattern). */
  accessibilitySummary?: string;
  xAxis?: ChartAxisConfig;
  yAxis?: ChartAxisConfig;
  /** Combine line marks with point marks. Default true for line charts. */
  showPoints?: boolean;
  /** Stack bar marks when multiple series are present. */
  stacked?: boolean;
  /** Gap between stacked bar segments (Apple HIG visual separation). */
  stackGap?: number;
  /** Plot height in CSS pixels. */
  height?: number;
  /** Enable plot-area scrubbing with crosshair. */
  interactive?: boolean;
  /** Y axis on trailing edge (right in LTR) for layout alignment. */
  yAxisTrailing?: boolean;
  showLegend?: boolean;
  className?: string;
  style?: CSSProperties;
  onPointFocus?: (point: ChartDataPoint, seriesId: string, index: number) => void;
}

function seriesColor(index: number, override?: string): string {
  return override ?? CHART_SERIES_COLORS[index % CHART_SERIES_COLORS.length] ?? 'var(--lr-chart-series-1)';
}

function resolveSeries(
  data: ChartDataPoint[] | undefined,
  series: ChartSeries[] | undefined,
): ChartSeries[] {
  if (series && series.length > 0) return series;
  if (data && data.length > 0) {
    return [{ id: 'default', label: 'Value', data }];
  }
  return [];
}

function renderPointShape(
  shape: PointShape,
  cx: number,
  cy: number,
  r: number,
  color: string,
  key: string,
) {
  if (shape === 'diamond') {
    return (
      <polygon
        key={key}
        className={styles.point}
        points={`${cx},${cy - r} ${cx + r},${cy} ${cx},${cy + r} ${cx - r},${cy}`}
        fill={color}
      />
    );
  }
  if (shape === 'square') {
    return (
      <rect
        key={key}
        className={styles.point}
        x={cx - r}
        y={cy - r}
        width={r * 2}
        height={r * 2}
        rx={1}
        fill={color}
      />
    );
  }
  return <circle key={key} className={styles.point} cx={cx} cy={cy} r={r} fill={color} />;
}

export function Chart({
  mark = 'bar',
  data,
  series: seriesProp,
  title,
  subtitle,
  annotation,
  accessibilitySummary,
  xAxis,
  yAxis,
  showPoints = mark === 'line',
  stacked = false,
  stackGap = 2,
  height = 220,
  interactive = false,
  yAxisTrailing = false,
  showLegend,
  className,
  style,
  onPointFocus,
}: ChartProps) {
  const chartId = useId();
  const svgRef = useRef<SVGSVGElement>(null);
  const [focusIndex, setFocusIndex] = useState<number | null>(null);
  const [liveMessage, setLiveMessage] = useState('');

  const width = 640;
  const padding = DEFAULT_PADDING;
  const plotWidth = width - padding.left - padding.right;
  const plotHeight = height - padding.top - padding.bottom;

  const resolvedSeries = useMemo(
    () => resolveSeries(data, seriesProp),
    [data, seriesProp],
  );

  const categories = useMemo(() => collectXValues(resolvedSeries), [resolvedSeries]);
  const yValues = useMemo(() => collectYValues(resolvedSeries), [resolvedSeries]);

  const yFormat = yAxis?.formatValue ?? formatDefaultNumber;
  const xFormat = xAxis?.formatCategory ?? ((v: string | number) => String(v));

  const yDomain = useMemo(
    () => resolveYDomain(yValues, yAxis?.min, yAxis?.max, mark),
    [yValues, yAxis?.min, yAxis?.max, mark],
  );

  const yTicks = useMemo(
    () => niceTicks(yDomain.min, yDomain.max, yAxis?.tickCount ?? 5),
    [yDomain, yAxis?.tickCount],
  );

  const legendItems: ChartLegendItem[] = useMemo(
    () =>
      resolvedSeries.map((s, i) => ({
        id: s.id,
        label: s.label,
        color: seriesColor(i, s.color),
        shape: s.pointShape ?? 'circle',
      })),
    [resolvedSeries],
  );

  const shouldShowLegend =
    showLegend ?? (resolvedSeries.length > 1 || mark === 'point');

  const accessibilityLabels = useMemo(() => {
    const labels: string[] = [];
    for (const s of resolvedSeries) {
      for (const point of s.data) {
        labels.push(
          point.accessibilityLabel ??
            defaultAccessibilityLabel(s.label, point, yFormat),
        );
      }
    }
    return labels;
  }, [resolvedSeries, yFormat]);

  const updateFocus = useCallback(
    (index: number) => {
      if (index < 0 || index >= categories.length) return;
      setFocusIndex(index);
      const xLabel = xFormat(categories[index]!);
      const parts = resolvedSeries.map((s) => {
        const point = s.data.find((d) => String(d.x) === String(categories[index]));
        return point ? `${s.label}: ${yFormat(point.y)}` : null;
      }).filter(Boolean);
      setLiveMessage(`${xLabel}. ${parts.join('. ')}`);
      const primary = resolvedSeries[0];
      const point = primary?.data.find((d) => String(d.x) === String(categories[index]));
      if (point && primary) {
        onPointFocus?.(point, primary.id, index);
      }
    },
    [categories, onPointFocus, resolvedSeries, xFormat, yFormat],
  );

  const handlePointer = useCallback(
    (event: PointerEvent<SVGRectElement>) => {
      if (!interactive || !svgRef.current) return;
      const rect = svgRef.current.getBoundingClientRect();
      const index = nearestPointIndex(event.clientX, rect, categories, width, padding);
      updateFocus(index);
    },
    [categories, interactive, padding, updateFocus, width],
  );

  const handleKeyDown = useCallback(
    (event: KeyboardEvent<SVGSVGElement>) => {
      if (!interactive) return;
      const current = focusIndex ?? 0;
      if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
        event.preventDefault();
        updateFocus(Math.min(categories.length - 1, current + 1));
      } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
        event.preventDefault();
        updateFocus(Math.max(0, current - 1));
      }
    },
    [categories.length, focusIndex, interactive, updateFocus],
  );

  const barStep = categories.length > 0 ? plotWidth / categories.length : plotWidth;
  const barWidth = Math.max(4, barStep * 0.62);

  const renderBars = () => {
    if (stacked && resolvedSeries.length > 1) {
      return categories.flatMap((cat, catIndex) => {
        const cx = xBandIndex(cat, categories, width, padding);
        let runningTotal = 0;
        return resolvedSeries.map((s, seriesIndex) => {
          const point = s.data.find((d) => String(d.x) === String(cat));
          const value = point?.y ?? 0;
          if (value <= 0) return null;
          const color = seriesColor(seriesIndex, s.color);
          const yTop = yToPixel(runningTotal + value, yDomain.min, yDomain.max, height, padding);
          const yBottom = yToPixel(runningTotal, yDomain.min, yDomain.max, height, padding);
          const segmentHeight = Math.max(0, yBottom - yTop - (seriesIndex > 0 ? stackGap : 0));
          const y = yTop + (seriesIndex > 0 ? stackGap : 0);
          runningTotal += value;
          return (
            <rect
              key={`${s.id}-${catIndex}`}
              className={`${styles.bar} ${styles.barSegment}`}
              x={cx - barWidth / 2}
              y={y}
              width={barWidth}
              height={segmentHeight}
              rx={4}
              fill={color}
              opacity={focusIndex === null || focusIndex === catIndex ? 1 : 0.45}
            />
          );
        });
      });
    }

    return resolvedSeries.flatMap((s, seriesIndex) => {
      const offset =
        resolvedSeries.length > 1
          ? (seriesIndex - (resolvedSeries.length - 1) / 2) * (barWidth / resolvedSeries.length)
          : 0;
      const sliceWidth =
        resolvedSeries.length > 1 ? barWidth / resolvedSeries.length - 2 : barWidth;
      const color = seriesColor(seriesIndex, s.color);

      return s.data.map((point) => {
        const catIndex = categories.findIndex((c) => String(c) === String(point.x));
        const cx = xBandIndex(point.x, categories, width, padding) + offset;
        const yBase = yToPixel(0, yDomain.min, yDomain.max, height, padding);
        const yTop = yToPixel(point.y, yDomain.min, yDomain.max, height, padding);
        const barHeight = Math.max(0, yBase - yTop);
        return (
          <rect
            key={`${s.id}-${String(point.x)}`}
            className={styles.bar}
            x={cx - sliceWidth / 2}
            y={yTop}
            width={sliceWidth}
            height={barHeight}
            rx={4}
            fill={color}
            opacity={focusIndex === null || focusIndex === catIndex ? 1 : 0.45}
          />
        );
      });
    });
  };

  const renderLineSeries = () =>
    resolvedSeries.map((s, seriesIndex) => {
      const color = seriesColor(seriesIndex, s.color);
      const points = s.data.map((point) => ({
        x: xBandIndex(point.x, categories, width, padding),
        y: yToPixel(point.y, yDomain.min, yDomain.max, height, padding),
      }));
      const shape = s.pointShape ?? 'circle';

      return (
        <g key={s.id}>
          <path className={styles.line} d={buildLinePath(points)} stroke={color} />
          {showPoints &&
            points.map((p, i) =>
              renderPointShape(shape, p.x, p.y, 4.5, color, `${s.id}-pt-${i}`),
            )}
        </g>
      );
    });

  const renderPointSeries = () =>
    resolvedSeries.flatMap((s, seriesIndex) => {
      const color = seriesColor(seriesIndex, s.color);
      const shape = s.pointShape ?? (seriesIndex === 0 ? 'circle' : 'diamond');
      return s.data.map((point, i) => {
        const cx = xBandIndex(point.x, categories, width, padding);
        const cy = yToPixel(point.y, yDomain.min, yDomain.max, height, padding);
        return renderPointShape(shape, cx, cy, 5, color, `${s.id}-${i}`);
      });
    });

  const focusX =
    focusIndex !== null && categories[focusIndex] !== undefined
      ? xBandIndex(categories[focusIndex]!, categories, width, padding)
      : null;

  const yAxisX = yAxisTrailing ? width - padding.right : padding.left;
  const yLabelX = yAxisTrailing ? width - padding.right + 8 : padding.left - 8;
  const yTextAnchor = yAxisTrailing ? 'start' : 'end';

  return (
    <figure
      className={[styles.chart, className].filter(Boolean).join(' ')}
      style={style}
      aria-labelledby={title ? `${chartId}-title` : undefined}
      aria-describedby={
        accessibilitySummary || subtitle ? `${chartId}-summary` : undefined
      }
    >
      {(title || subtitle || annotation) && (
        <header className={styles.header}>
          {title && (
            <h3 id={`${chartId}-title`} className={styles.title}>
              {title}
            </h3>
          )}
          {subtitle && <p className={styles.subtitle}>{subtitle}</p>}
          {annotation && <p className={styles.annotation}>{annotation}</p>}
        </header>
      )}

      <div className={styles.plotWrapper}>
        <svg
          ref={svgRef}
          className={styles.plot}
          viewBox={`0 0 ${width} ${height}`}
          role="img"
          aria-hidden={accessibilityLabels.length > 0 ? true : undefined}
          aria-label={accessibilityLabels.length === 0 ? accessibilitySummary ?? title : undefined}
          data-interactive={interactive ? 'true' : undefined}
          tabIndex={interactive ? 0 : undefined}
          onKeyDown={handleKeyDown}
        >
          <rect
            x={padding.left}
            y={padding.top}
            width={plotWidth}
            height={plotHeight}
            fill="var(--lr-chart-plot-bg)"
            onPointerDown={handlePointer}
            onPointerMove={handlePointer}
          />

          {!yAxis?.hidden &&
            yTicks.map((tick) => {
              const y = yToPixel(tick, yDomain.min, yDomain.max, height, padding);
              return (
                <g key={tick}>
                  <line
                    className={styles.gridLine}
                    x1={padding.left}
                    x2={width - padding.right}
                    y1={y}
                    y2={y}
                  />
                  <text
                    className={styles.axisLabel}
                    x={yLabelX}
                    y={y + 4}
                    textAnchor={yTextAnchor}
                  >
                    {yFormat(tick)}
                  </text>
                </g>
              );
            })}

          <line
            className={styles.axisLine}
            x1={padding.left}
            x2={width - padding.right}
            y1={height - padding.bottom}
            y2={height - padding.bottom}
          />
          <line
            className={styles.axisLine}
            x1={yAxisX}
            x2={yAxisX}
            y1={padding.top}
            y2={height - padding.bottom}
          />

          {categories.map((cat) => {
            const x = xBandIndex(cat, categories, width, padding);
            return (
              <g key={String(cat)}>
                <line
                  className={styles.tick}
                  x1={x}
                  x2={x}
                  y1={height - padding.bottom}
                  y2={height - padding.bottom + 4}
                />
                <text
                  className={styles.axisLabel}
                  x={x}
                  y={height - padding.bottom + 16}
                  textAnchor="middle"
                >
                  {xFormat(cat)}
                </text>
              </g>
            );
          })}

          {mark === 'bar' && renderBars()}
          {mark === 'line' && renderLineSeries()}
          {mark === 'point' && renderPointSeries()}

          {interactive && focusX !== null && (
            <>
              <line
                className={styles.crosshair}
                x1={focusX}
                x2={focusX}
                y1={padding.top}
                y2={height - padding.bottom}
              />
              <circle
                className={styles.focusRing}
                cx={focusX}
                cy={padding.top + plotHeight / 2}
                r={8}
              />
            </>
          )}
        </svg>

        {interactive && focusIndex !== null && focusX !== null && (
          <div
            className={styles.tooltip}
            style={{ left: `${(focusX / width) * 100}%`, top: '0.5rem' }}
            aria-hidden="true"
          >
            {liveMessage}
          </div>
        )}
      </div>

      {shouldShowLegend && (
        <ul className={styles.legend} aria-hidden="true">
          {legendItems.map((item) => (
            <li key={item.id} className={styles.legendItem}>
              <span
                className={styles.legendSwatch}
                data-shape={item.shape}
                style={{ backgroundColor: item.color }}
              />
              {item.label}
            </li>
          ))}
        </ul>
      )}

      <figcaption id={`${chartId}-summary`} className={styles.srOnly}>
        {accessibilitySummary ?? subtitle ?? title}
      </figcaption>

      <ul className={styles.srOnly} aria-label="Chart data values">
        {accessibilityLabels.map((label, i) => (
          <li key={i}>{label}</li>
        ))}
      </ul>

      <div className={styles.liveRegion} aria-live="polite" aria-atomic="true">
        {interactive ? liveMessage : ''}
      </div>
    </figure>
  );
}

export type {
  ChartAxisConfig,
  ChartDataPoint,
  ChartLegendItem,
  ChartMark,
  ChartSeries,
  PointShape,
} from './types';

// packages/vue/src/components/Chart/Chart.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import { CHART_SERIES_COLORS } from '@larose-ui/tokens';
import styles from '@larose-ui/styles/components/Chart/Chart.module.css';
import { cn } from '../../utils/cn';
import type {
  ChartDataPoint,
  ChartLegendItem,
  ChartMark,
  ChartSeries,
  PointShape,
} from '../../Chart/types';
import {
  DEFAULT_PADDING,
  buildLinePath,
  collectXValues,
  collectYValues,
  formatDefaultNumber,
  niceTicks,
  resolveYDomain,
  xBandIndex,
  yToPixel,
} from '../../Chart/utils';

const props = withDefaults(
  defineProps<{
    mark?: ChartMark;
    data?: ChartDataPoint[];
    series?: ChartSeries[];
    title?: string;
    subtitle?: string;
    annotation?: string;
    height?: number;
    showPoints?: boolean;
    stacked?: boolean;
    showLegend?: boolean;
    class?: string;
    style?: CSSProperties;
  }>(),
  {
    mark: 'bar',
    height: 220,
    stacked: false,
  },
);

const width = 640;
const padding = DEFAULT_PADDING;
const plotWidth = computed(() => width - padding.left - padding.right);
const plotHeight = computed(() => props.height - padding.top - padding.bottom);

const resolvedSeries = computed<ChartSeries[]>(() => {
  if (props.series?.length) return props.series;
  if (props.data?.length) return [{ id: 'default', label: 'Value', data: props.data }];
  return [];
});

const categories = computed(() => collectXValues(resolvedSeries.value));
const yValues = computed(() => collectYValues(resolvedSeries.value));
const yDomain = computed(() =>
  resolveYDomain(yValues.value, undefined, undefined, props.mark),
);
const yTicks = computed(() => niceTicks(yDomain.value.min, yDomain.value.max, 5));

const effectiveShowPoints = computed(
  () => props.showPoints ?? props.mark === 'line',
);

function seriesColor(index: number, override?: string): string {
  return (
    override ??
    CHART_SERIES_COLORS[index % CHART_SERIES_COLORS.length] ??
    'var(--lr-chart-series-1)'
  );
}

const legendItems = computed<ChartLegendItem[]>(() =>
  resolvedSeries.value.map((s, i) => ({
    id: s.id,
    label: s.label,
    color: seriesColor(i, s.color),
    shape: s.pointShape ?? 'circle',
  })),
);

const shouldShowLegend = computed(
  () =>
    props.showLegend ??
    (resolvedSeries.value.length > 1 || props.mark === 'point'),
);

const barStep = computed(() =>
  categories.value.length > 0
    ? plotWidth.value / categories.value.length
    : plotWidth.value,
);
const barWidth = computed(() => Math.max(4, barStep.value * 0.62));

interface BarRect {
  key: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string;
  stacked?: boolean;
}

const barRects = computed<BarRect[]>(() => {
  if (props.mark !== 'bar') return [];
  const result: BarRect[] = [];
  const cats = categories.value;
  const domain = yDomain.value;
  const bw = barWidth.value;
  const series = resolvedSeries.value;

  if (props.stacked && series.length > 1) {
    for (let catIndex = 0; catIndex < cats.length; catIndex++) {
      const cat = cats[catIndex]!;
      const cx = xBandIndex(cat, cats, width, padding);
      let runningTotal = 0;
      series.forEach((s, seriesIndex) => {
        const point = s.data.find((d) => String(d.x) === String(cat));
        const value = point?.y ?? 0;
        if (value <= 0) return;
        const color = seriesColor(seriesIndex, s.color);
        const yTop = yToPixel(runningTotal + value, domain.min, domain.max, props.height, padding);
        const yBottom = yToPixel(runningTotal, domain.min, domain.max, props.height, padding);
        const segmentHeight = Math.max(0, yBottom - yTop - (seriesIndex > 0 ? 2 : 0));
        const y = yTop + (seriesIndex > 0 ? 2 : 0);
        runningTotal += value;
        result.push({
          key: `${s.id}-${catIndex}`,
          x: cx - bw / 2,
          y,
          width: bw,
          height: segmentHeight,
          fill: color,
          stacked: true,
        });
      });
    }
    return result;
  }

  series.forEach((s, seriesIndex) => {
    const offset =
      series.length > 1
        ? (seriesIndex - (series.length - 1) / 2) * (bw / series.length)
        : 0;
    const sliceWidth = series.length > 1 ? bw / series.length - 2 : bw;
    const color = seriesColor(seriesIndex, s.color);
    s.data.forEach((point) => {
      const cx = xBandIndex(point.x, cats, width, padding) + offset;
      const yBase = yToPixel(0, domain.min, domain.max, props.height, padding);
      const yTop = yToPixel(point.y, domain.min, domain.max, props.height, padding);
      result.push({
        key: `${s.id}-${String(point.x)}`,
        x: cx - sliceWidth / 2,
        y: yTop,
        width: sliceWidth,
        height: Math.max(0, yBase - yTop),
        fill: color,
      });
    });
  });
  return result;
});

interface LineSeriesDraw {
  id: string;
  color: string;
  path: string;
  points: Array<{ x: number; y: number }>;
  shape: PointShape;
}

const lineSeries = computed<LineSeriesDraw[]>(() => {
  if (props.mark !== 'line') return [];
  const cats = categories.value;
  const domain = yDomain.value;
  return resolvedSeries.value.map((s, seriesIndex) => {
    const color = seriesColor(seriesIndex, s.color);
    const points = s.data.map((point) => ({
      x: xBandIndex(point.x, cats, width, padding),
      y: yToPixel(point.y, domain.min, domain.max, props.height, padding),
    }));
    return {
      id: s.id,
      color,
      path: buildLinePath(points),
      points,
      shape: s.pointShape ?? 'circle',
    };
  });
});

interface PointDraw {
  key: string;
  cx: number;
  cy: number;
  color: string;
  shape: PointShape;
  r: number;
}

const pointMarks = computed<PointDraw[]>(() => {
  if (props.mark !== 'point') return [];
  const cats = categories.value;
  const domain = yDomain.value;
  return resolvedSeries.value.flatMap((s, seriesIndex) => {
    const color = seriesColor(seriesIndex, s.color);
    const shape = s.pointShape ?? (seriesIndex === 0 ? 'circle' : 'diamond');
    return s.data.map((point, i) => ({
      key: `${s.id}-${i}`,
      cx: xBandIndex(point.x, cats, width, padding),
      cy: yToPixel(point.y, domain.min, domain.max, props.height, padding),
      color,
      shape,
      r: 5,
    }));
  });
});

function diamondPoints(cx: number, cy: number, r: number): string {
  return `${cx},${cy - r} ${cx + r},${cy} ${cx},${cy + r} ${cx - r},${cy}`;
}
</script>

<template>
  <figure :class="cn(styles.chart, props.class)" :style="props.style">
    <header v-if="title || subtitle || annotation" :class="styles.header">
      <h3 v-if="title" :class="styles.title">{{ title }}</h3>
      <p v-if="subtitle" :class="styles.subtitle">{{ subtitle }}</p>
      <p v-if="annotation" :class="styles.annotation">{{ annotation }}</p>
    </header>

    <div :class="styles.plotWrapper">
      <svg
        :class="styles.plot"
        :viewBox="`0 0 ${width} ${height}`"
        role="img"
        :aria-label="title ?? 'Chart'"
      >
        <rect
          :x="padding.left"
          :y="padding.top"
          :width="plotWidth"
          :height="plotHeight"
          fill="var(--lr-chart-plot-bg)"
        />

        <g v-for="tick in yTicks" :key="tick">
          <line
            :class="styles.gridLine"
            :x1="padding.left"
            :x2="width - padding.right"
            :y1="yToPixel(tick, yDomain.min, yDomain.max, height, padding)"
            :y2="yToPixel(tick, yDomain.min, yDomain.max, height, padding)"
          />
          <text
            :class="styles.axisLabel"
            :x="padding.left - 8"
            :y="yToPixel(tick, yDomain.min, yDomain.max, height, padding) + 4"
            text-anchor="end"
          >
            {{ formatDefaultNumber(tick) }}
          </text>
        </g>

        <line
          :class="styles.axisLine"
          :x1="padding.left"
          :x2="width - padding.right"
          :y1="height - padding.bottom"
          :y2="height - padding.bottom"
        />
        <line
          :class="styles.axisLine"
          :x1="padding.left"
          :x2="padding.left"
          :y1="padding.top"
          :y2="height - padding.bottom"
        />

        <g v-for="cat in categories" :key="String(cat)">
          <line
            :class="styles.tick"
            :x1="xBandIndex(cat, categories, width, padding)"
            :x2="xBandIndex(cat, categories, width, padding)"
            :y1="height - padding.bottom"
            :y2="height - padding.bottom + 4"
          />
          <text
            :class="styles.axisLabel"
            :x="xBandIndex(cat, categories, width, padding)"
            :y="height - padding.bottom + 16"
            text-anchor="middle"
          >
            {{ String(cat) }}
          </text>
        </g>

        <template v-if="mark === 'bar'">
          <rect
            v-for="bar in barRects"
            :key="bar.key"
            :class="cn(styles.bar, bar.stacked ? styles.barSegment : undefined)"
            :x="bar.x"
            :y="bar.y"
            :width="bar.width"
            :height="bar.height"
            rx="4"
            :fill="bar.fill"
          />
        </template>

        <template v-else-if="mark === 'line'">
          <g v-for="line in lineSeries" :key="line.id">
            <path :class="styles.line" :d="line.path" :stroke="line.color" />
            <template v-if="effectiveShowPoints">
              <template v-for="(p, i) in line.points" :key="`${line.id}-pt-${i}`">
                <polygon
                  v-if="line.shape === 'diamond'"
                  :class="styles.point"
                  :points="diamondPoints(p.x, p.y, 4.5)"
                  :fill="line.color"
                />
                <rect
                  v-else-if="line.shape === 'square'"
                  :class="styles.point"
                  :x="p.x - 4.5"
                  :y="p.y - 4.5"
                  width="9"
                  height="9"
                  rx="1"
                  :fill="line.color"
                />
                <circle
                  v-else
                  :class="styles.point"
                  :cx="p.x"
                  :cy="p.y"
                  r="4.5"
                  :fill="line.color"
                />
              </template>
            </template>
          </g>
        </template>

        <template v-else-if="mark === 'point'">
          <template v-for="pt in pointMarks" :key="pt.key">
            <polygon
              v-if="pt.shape === 'diamond'"
              :class="styles.point"
              :points="diamondPoints(pt.cx, pt.cy, pt.r)"
              :fill="pt.color"
            />
            <rect
              v-else-if="pt.shape === 'square'"
              :class="styles.point"
              :x="pt.cx - pt.r"
              :y="pt.cy - pt.r"
              :width="pt.r * 2"
              :height="pt.r * 2"
              rx="1"
              :fill="pt.color"
            />
            <circle
              v-else
              :class="styles.point"
              :cx="pt.cx"
              :cy="pt.cy"
              :r="pt.r"
              :fill="pt.color"
            />
          </template>
        </template>
      </svg>
    </div>

    <ul v-if="shouldShowLegend" :class="styles.legend" aria-hidden="true">
      <li v-for="item in legendItems" :key="item.id" :class="styles.legendItem">
        <span
          :class="styles.legendSwatch"
          :data-shape="item.shape"
          :style="{ backgroundColor: item.color }"
        />
        {{ item.label }}
      </li>
    </ul>
  </figure>
</template>
