// packages/vue/src/components/TabView/TabView.vue
<script setup lang="ts">
import { computed, provide, ref, useId, watch } from 'vue';
import type { TabViewVariant } from '../../TabView/types';
import styles from '@larose-ui/styles/components/TabView/TabView.module.css';
import { cn } from '../../utils/cn';
import { tabViewKey } from '../../composables/useTabView';

const props = withDefaults(
  defineProps<{
    value?: string;
    defaultValue?: string;
    variant?: TabViewVariant;
    showTabs?: boolean;
    inset?: boolean;
    class?: string;
    style?: Record<string, string | number>;
    'aria-label'?: string;
  }>(),
  {
    defaultValue: '',
    variant: 'bordered',
    showTabs: true,
    inset: true,
    'aria-label': 'Tab view',
  },
);

const emit = defineEmits<{ valueChange: [value: string] }>();
const internal = ref(props.defaultValue);
const current = computed(() => (props.value !== undefined ? props.value : internal.value));
const baseId = useId();

function onValueChange(next: string) {
  if (props.value === undefined) internal.value = next;
  emit('valueChange', next);
}

provide(tabViewKey, { value: current as any, onValueChange, baseId });
</script>

<template>
  <div
    :class="cn(styles.tabView, props.class)"
    :style="props.style"
    :data-variant="variant"
    :data-inset="inset ? 'true' : undefined"
    :aria-label="props['aria-label']"
  >
    <slot v-if="showTabs" name="list" />
    <div :class="styles.content">
      <slot />
    </div>
  </div>
</template>

// packages/svelte/src/lib/components/TabView/TabView.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { TabViewVariant } from '../../TabView/types';
  import { setTabViewContext } from '../../TabView/context';
  import styles from '@larose-ui/styles/components/TabView/TabView.module.css';

  let {
    value,
    defaultValue = '',
    onValueChange,
    variant = 'bordered',
    showTabs = true,
    inset = true,
    class: className,
    style,
    'aria-label': ariaLabel = 'Tab view',
    children,
    list,
    panels,
  }: {
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    variant?: TabViewVariant;
    showTabs?: boolean;
    inset?: boolean;
    class?: string;
    style?: string;
    'aria-label'?: string;
    children?: Snippet;
    list?: Snippet;
    panels?: Snippet;
  } = $props();

  let internal = $state(defaultValue);
  const current = $derived(value ?? internal);
  const baseId = $props.id();

  setTabViewContext(() => ({
    value: current,
    onValueChange(next: string) {
      if (value === undefined) internal = next;
      onValueChange?.(next);
    },
    baseId,
  }));
</script>

<div
  class={[styles.tabView, className].filter(Boolean).join(' ')}
  {style}
  data-variant={variant}
  data-inset={inset ? 'true' : undefined}
  aria-label={ariaLabel}
>
  {#if showTabs}
    {@render list?.()}
  {/if}
  <div class={styles.content}>{@render panels?.()}{@render children?.()}</div>
</div>
