// packages/react/src/Pagination/Pagination.tsx
import { useMemo, type CSSProperties } from 'react';
import styles from '@larose-ui/styles/components/Pagination/Pagination.module.css';

type PageItem = number | 'ellipsis';

function range(start: number, end: number): number[] {
  const items: number[] = [];
  for (let i = start; i <= end; i += 1) {
    items.push(i);
  }
  return items;
}

function getPageItems(page: number, totalPages: number, siblingCount: number): PageItem[] {
  if (totalPages <= 1) return [1];

  const totalNumbers = siblingCount * 2 + 5;
  if (totalPages <= totalNumbers) {
    return range(1, totalPages);
  }

  const leftSibling = Math.max(page - siblingCount, 1);
  const rightSibling = Math.min(page + siblingCount, totalPages);
  const showLeftEllipsis = leftSibling > 2;
  const showRightEllipsis = rightSibling < totalPages - 1;

  if (!showLeftEllipsis && showRightEllipsis) {
    return [...range(1, 3 + siblingCount * 2), 'ellipsis', totalPages];
  }

  if (showLeftEllipsis && !showRightEllipsis) {
    return [1, 'ellipsis', ...range(totalPages - (3 + siblingCount * 2), totalPages)];
  }

  if (showLeftEllipsis && showRightEllipsis) {
    return [1, 'ellipsis', ...range(leftSibling, rightSibling), 'ellipsis', totalPages];
  }

  return range(1, totalPages);
}

export interface PaginationProps {
  page: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  siblingCount?: number;
  previousLabel?: string;
  nextLabel?: string;
  'aria-label'?: string;
  className?: string;
  style?: CSSProperties;
}

export function Pagination({
  page,
  totalPages,
  onPageChange,
  siblingCount = 1,
  previousLabel = 'Previous page',
  nextLabel = 'Next page',
  'aria-label': ariaLabel = 'Pagination',
  className,
  style,
}: PaginationProps) {
  const items = useMemo(
    () => getPageItems(page, totalPages, siblingCount),
    [page, siblingCount, totalPages],
  );

  if (totalPages < 1) return null;

  return (
    <nav
      className={[styles.pagination, className].filter(Boolean).join(' ')}
      style={style}
      aria-label={ariaLabel}
    >
      <button
        type="button"
        className={styles.pageButton}
        aria-label={previousLabel}
        disabled={page <= 1}
        onClick={() => onPageChange(page - 1)}
      >
        ‹
      </button>

      {items.map((item, index) =>
        item === 'ellipsis' ? (
          <span key={`ellipsis-${index}`} className={styles.ellipsis} aria-hidden="true">
            …
          </span>
        ) : (
          <button
            key={item}
            type="button"
            className={styles.pageButton}
            aria-label={`Page ${item}`}
            aria-current={item === page ? 'page' : undefined}
            data-state={item === page ? 'active' : 'inactive'}
            onClick={() => onPageChange(item)}
          >
            {item}
          </button>
        ),
      )}

      <button
        type="button"
        className={styles.pageButton}
        aria-label={nextLabel}
        disabled={page >= totalPages}
        onClick={() => onPageChange(page + 1)}
      >
        ›
      </button>
    </nav>
  );
}

// packages/vue/src/components/Pagination/Pagination.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Pagination/Pagination.module.css';
import { cn } from '../../utils/cn';
import { getPageItems } from './pageItems';

const props = withDefaults(
  defineProps<{
    page: number;
    totalPages: number;
    siblingCount?: number;
    previousLabel?: string;
    nextLabel?: string;
    class?: string;
    style?: CSSProperties;
    ariaLabel?: string;
  }>(),
  {
    siblingCount: 1,
    previousLabel: 'Previous page',
    nextLabel: 'Next page',
    ariaLabel: 'Pagination',
  },
);

const emit = defineEmits<{ pageChange: [page: number] }>();
const items = computed(() => getPageItems(props.page, props.totalPages, props.siblingCount));
</script>

<template>
  <nav
    v-if="totalPages >= 1"
    :class="cn(styles.pagination, props.class)"
    :style="props.style"
    :aria-label="ariaLabel"
  >
    <button
      type="button"
      :class="styles.pageButton"
      :disabled="page <= 1"
      :aria-label="previousLabel"
      @click="emit('pageChange', page - 1)"
    >
      ‹
    </button>
    <template v-for="(item, index) in items" :key="`${item}-${index}`">
      <span v-if="item === 'ellipsis'" :class="styles.ellipsis" aria-hidden="true">…</span>
      <button
        v-else
        type="button"
        :class="styles.pageButton"
        :data-state="item === page ? 'active' : undefined"
        :aria-current="item === page ? 'page' : undefined"
        @click="emit('pageChange', item)"
      >
        {{ item }}
      </button>
    </template>
    <button
      type="button"
      :class="styles.pageButton"
      :disabled="page >= totalPages"
      :aria-label="nextLabel"
      @click="emit('pageChange', page + 1)"
    >
      ›
    </button>
  </nav>
</template>
