// packages/vue/src/components/Toolbar/ToolbarGroup.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/Toolbar/Toolbar.module.css';
import { cn } from '../../utils/cn';
import { useToolbarPlatform } from '../../composables/useToolbarPlatform';
defineProps<{ class?: string; style?: Record<string, string | number> }>();
const platform = useToolbarPlatform();
</script>
<template>
  <div :class="cn(styles.group, $props.class)" :style="$props.style" :data-platform="platform" role="group">
    <slot />
  </div>
</template>

// packages/svelte/src/lib/components/Toolbar/ToolbarGroup.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getToolbarPlatform } from '../../Toolbar/context';
  import styles from '@larose-ui/styles/components/Toolbar/Toolbar.module.css';

  let {
    class: className,
    style,
    children,
  }: { class?: string; style?: string; children?: Snippet } = $props();

  const platform = $derived(getToolbarPlatform());
</script>

<div class={[styles.group, className].filter(Boolean).join(' ')} {style} data-platform={platform} role="group">
  {@render children?.()}
</div>
