// packages/svelte/src/lib/components/Sidebar/SidebarNav.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Sidebar/Sidebar.module.css';

  let {
    class: className,
    style,
    'aria-label': ariaLabel = 'Sidebar navigation',
    children,
  }: { class?: string; style?: string; 'aria-label'?: string; children?: Snippet } = $props();
</script>

<nav class={[styles.nav, className].filter(Boolean).join(' ')} {style} aria-label={ariaLabel}>
  {@render children?.()}
</nav>

// packages/vue/src/components/Sidebar/SidebarNav.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/Sidebar/Sidebar.module.css';
import { cn } from '../../utils/cn';
defineProps<{ class?: string; style?: Record<string, string | number>; 'aria-label'?: string }>();
</script>
<template>
  <nav :class="cn(styles.nav, $props.class)" :style="$props.style" :aria-label="$props['aria-label'] ?? 'Sidebar navigation'"><slot /></nav>
</template>
