// packages/svelte/src/lib/components/Sidebar/SidebarHeader.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Sidebar/Sidebar.module.css';

  let {
    class: className,
    style,
    children,
  }: { class?: string; style?: string; children?: Snippet } = $props();
</script>

<div class={[styles.header, className].filter(Boolean).join(' ')} {style}>
  {@render children?.()}
</div>

// packages/vue/src/components/Sidebar/SidebarHeader.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/Sidebar/Sidebar.module.css';
import { cn } from '../../utils/cn';
defineProps<{ class?: string; style?: Record<string, string | number> }>();
</script>
<template>
  <div :class="cn(styles.header, $props.class)" :style="$props.style"><slot /></div>
</template>
