// packages/permissions-vue/src/Can.vue
<script setup lang="ts">
import type { PermissionFallback } from '@larose-ui/core';
import { resolvePermissionFallback } from '@larose-ui/permissions-core';
import { computed } from 'vue';
import { usePermission } from './context';

const props = withDefaults(
  defineProps<{
    permission: string;
    resource?: string;
    fallback?: PermissionFallback;
    reason?: string;
  }>(),
  {
    fallback: 'hidden',
  },
);

const result = usePermission(
  computed(() => props.permission),
  computed(() => props.resource),
);
const mode = computed(() =>
  resolvePermissionFallback(result.value.allowed, false, props.fallback),
);
const explainReason = computed(() => props.reason ?? result.value.reason);
</script>

<template>
  <span v-if="mode === 'loading'" aria-busy="true">
    <slot />
  </span>
  <span
    v-else-if="mode === 'forbidden' || mode === 'disabled' || mode === 'readonly'"
    class="lr-explainable"
    :data-variant="mode === 'forbidden' ? 'forbidden' : mode === 'readonly' ? 'readonly' : 'disabled'"
    :title="explainReason ?? 'Not allowed'"
    style="display: inline-flex; flex-direction: column; gap: 0.25rem"
  >
    <span aria-disabled="true" :data-permission-fallback="mode">
      <slot />
    </span>
    <span
      role="note"
      style="font-size: var(--lr-font-size-xs, 0.75rem); color: var(--lr-color-text-muted, #64748b); max-width: 16rem"
    >
      {{ explainReason ?? 'Access denied' }}
    </span>
  </span>
  <slot v-else-if="mode !== 'hidden'" />
</template>

// packages/permissions/src/Can.tsx
import type { ReactNode } from 'react';
import type { PermissionFallback } from '@larose-ui/core';
import { usePermission } from './PermissionProvider';
import { resolvePermissionFallback } from '@larose-ui/permissions-core';
import { Explainable } from './Explainable';

export interface CanProps {
  permission: string;
  resource?: string;
  fallback?: PermissionFallback;
  children: ReactNode;
  reason?: string;
}

export function Can({
  permission,
  resource,
  fallback = 'hidden',
  children,
  reason,
}: CanProps) {
  const result = usePermission(permission, resource);
  const mode = resolvePermissionFallback(result.allowed, false, fallback);
  const explainReason = reason ?? result.reason;

  if (mode === 'hidden') return null;

  if (mode === 'loading') {
    return <span aria-busy="true">{children}</span>;
  }

  if (mode === 'forbidden') {
    return (
      <Explainable reason={explainReason ?? 'Access denied'} variant="forbidden">
        {children}
      </Explainable>
    );
  }

  if (mode === 'disabled' || mode === 'readonly') {
    return (
      <Explainable
        reason={explainReason ?? 'Not allowed'}
        variant={mode === 'readonly' ? 'readonly' : 'disabled'}
      >
        <span aria-disabled="true" data-permission-fallback={mode}>
          {children}
        </span>
      </Explainable>
    );
  }

  return <>{children}</>;
}
