// packages/permissions-vue/src/Permission.vue
<script setup lang="ts">
import type { PermissionFallback } from '@larose-ui/core';
import { resolvePermissionFallback } from '@larose-ui/permissions-core';
import { computed } from 'vue';
import { usePermission, usePermissions } from './context';

const props = withDefaults(
  defineProps<{
    action: string;
    resource?: string;
    fallback?: PermissionFallback;
    reason?: string;
  }>(),
  {
    fallback: 'disabled',
  },
);

const perms = usePermissions();
const result = usePermission(
  computed(() => props.action),
  computed(() => props.resource),
);
const mode = computed(() =>
  resolvePermissionFallback(result.value.allowed, perms.loading, props.fallback),
);
const explainReason = computed(
  () => props.reason ?? result.value.reason ?? `Missing permission: ${props.action}`,
);
</script>

<template>
  <div v-if="mode === 'loading'" data-permission-state="loading" aria-busy="true">
    <slot />
  </div>
  <span
    v-else-if="!result.allowed && mode !== 'hidden'"
    class="lr-explainable"
    :data-variant="mode === 'forbidden' ? 'forbidden' : 'disabled'"
    :title="explainReason"
    style="display: inline-flex; flex-direction: column; gap: 0.25rem"
  >
    <div :data-permission-state="mode" aria-disabled="true">
      <slot />
    </div>
    <span
      role="note"
      style="font-size: var(--lr-font-size-xs, 0.75rem); color: var(--lr-color-text-muted, #64748b); max-width: 16rem"
    >
      {{ explainReason }}
    </span>
  </span>
  <slot v-else-if="result.allowed" />
</template>

// packages/permissions/src/Permission.tsx
import type { ReactNode } from 'react';
import type { PermissionFallback } from '@larose-ui/core';
import { usePermission, usePermissions } from './PermissionProvider';
import { resolvePermissionFallback } from '@larose-ui/permissions-core';
import { Explainable } from './Explainable';

export interface PermissionProps {
  action: string;
  resource?: string;
  fallback?: PermissionFallback;
  reason?: string;
  children: ReactNode;
}

export function Permission({
  action,
  resource,
  fallback = 'disabled',
  reason,
  children,
}: PermissionProps) {
  const result = usePermission(action, resource);
  const { loading } = usePermissions();
  const mode = resolvePermissionFallback(result.allowed, loading, fallback);
  const explainReason = reason ?? result.reason;

  if (mode === 'hidden') return null;

  if (mode === 'loading') {
    return (
      <div data-permission-state="loading" aria-busy="true">
        {children}
      </div>
    );
  }

  if (!result.allowed) {
    return (
      <Explainable
        reason={explainReason ?? `Missing permission: ${action}`}
        variant={mode === 'forbidden' ? 'forbidden' : 'disabled'}
      >
        <div data-permission-state={mode} aria-disabled="true">
          {children}
        </div>
      </Explainable>
    );
  }

  return <>{children}</>;
}
