// packages/svelte/src/lib/components/FileManagement/DocumentLauncher.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import Button from '../Button/Button.svelte';
  import FileBrowser from './FileBrowser.svelte';
  import type { FileBrowserItem, FileBrowserTab } from '../../FileManagement/types';
  import styles from '@larose-ui/styles/components/FileManagement/FileManagement.module.css';

  let {
    appTitle,
    primaryActionLabel = 'Create Document',
    secondaryActionLabel = 'Choose Template',
    onPrimaryAction,
    onSecondaryAction,
    background,
    accessories,
    class: className,
    style,
    files,
    activeTab,
    onTabChange,
    showExtensions,
    onShowExtensionsChange,
    selectedId,
    onSelect,
    onOpen,
    acceptTypes,
    emptyLabel,
  }: {
    appTitle: string;
    primaryActionLabel?: string;
    secondaryActionLabel?: string;
    onPrimaryAction?: () => void;
    onSecondaryAction?: () => void;
    background?: Snippet;
    accessories?: Snippet;
    class?: string;
    style?: string;
    files: FileBrowserItem[];
    activeTab?: FileBrowserTab;
    onTabChange?: (tab: FileBrowserTab) => void;
    showExtensions?: boolean;
    onShowExtensionsChange?: (show: boolean) => void;
    selectedId?: string;
    onSelect?: (file: FileBrowserItem) => void;
    onOpen?: (file: FileBrowserItem) => void;
    acceptTypes?: string[];
    emptyLabel?: string;
  } = $props();
</script>

<div class={[styles.launcher, className].filter(Boolean).join(' ')} {style}>
  <div class={styles.launcherHero}>
    {#if background}{@render background()}{:else}<div class={styles.launcherBackground} aria-hidden="true"></div>{/if}
    {@render accessories?.()}
    <div class={styles.launcherContent}>
      <h2 class={styles.launcherTitle}>{appTitle}</h2>
      <div class={styles.launcherActions}>
        {#if onPrimaryAction}<Button size="lg" onclick={onPrimaryAction}>{primaryActionLabel}</Button>{/if}
        {#if onSecondaryAction}<Button size="lg" variant="secondary" onclick={onSecondaryAction}>{secondaryActionLabel}</Button>{/if}
      </div>
    </div>
  </div>
  <div class={styles.launcherSheet}>
    <FileBrowser {files} {activeTab} {onTabChange} {showExtensions} {onShowExtensionsChange} {selectedId} {onSelect} {onOpen} {acceptTypes} {emptyLabel} />
  </div>
</div>

// packages/vue/src/components/FileManagement/DocumentLauncher.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/FileManagement/FileManagement.module.css';
import { cn } from '../../utils/cn';
import Button from '../Button/Button.vue';
import FileBrowser from './FileBrowser.vue';
import type { FileBrowserItem, FileBrowserTab } from '../../FileManagement/types';

withDefaults(defineProps<{
  appTitle: string; files: FileBrowserItem[]; primaryActionLabel?: string; secondaryActionLabel?: string;
  activeTab?: FileBrowserTab; selectedId?: string; class?: string; style?: Record<string, string | number>;
}>(), { primaryActionLabel: 'Create Document', secondaryActionLabel: 'Choose Template' });

const emit = defineEmits<{
  primaryAction: []; secondaryAction: [];
  tabChange: [FileBrowserTab]; select: [FileBrowserItem]; open: [FileBrowserItem];
}>();
</script>

<template>
  <div :class="cn(styles.launcher, $props.class)" :style="$props.style">
    <div :class="styles.launcherHero">
      <slot name="background"><div :class="styles.launcherBackground" aria-hidden="true" /></slot>
      <slot name="accessories" />
      <div :class="styles.launcherContent">
        <h2 :class="styles.launcherTitle">{{ appTitle }}</h2>
        <div :class="styles.launcherActions">
          <Button size="lg" @click="emit('primaryAction')">{{ primaryActionLabel }}</Button>
          <Button size="lg" variant="secondary" @click="emit('secondaryAction')">{{ secondaryActionLabel }}</Button>
        </div>
      </div>
    </div>
    <div :class="styles.launcherSheet">
      <FileBrowser :files="files" :active-tab="activeTab" :selected-id="selectedId" @tab-change="emit('tabChange', $event)" @select="emit('select', $event)" @open="emit('open', $event)" />
    </div>
  </div>
</template>
