// packages/vue/src/components/Breadcrumb/Breadcrumb.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import { sanitizeNavigationUrl } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/Breadcrumb/Breadcrumb.module.css';
import { cn } from '../../utils/cn';

export interface BreadcrumbItem {
  label: string;
  href?: string;
  onClick?: () => void;
  current?: boolean;
}

const props = withDefaults(
  defineProps<{
    items: BreadcrumbItem[];
    class?: string;
    style?: CSSProperties;
    ariaLabel?: string;
  }>(),
  { ariaLabel: 'Breadcrumb' },
);
</script>

<template>
  <nav :class="cn(styles.nav, props.class)" :style="props.style" :aria-label="ariaLabel">
    <ol :class="styles.list">
      <li v-for="(item, index) in items" :key="`${item.label}-${index}`" :class="styles.item">
        <span v-if="item.current ?? index === items.length - 1" :class="styles.current" aria-current="page">
          {{ item.label }}
        </span>
        <a
          v-else-if="sanitizeNavigationUrl(item.href)"
          :href="sanitizeNavigationUrl(item.href)!"
          :class="styles.link"
          @click="item.onClick?.()"
        >
          {{ item.label }}
        </a>
        <button
          v-else-if="item.onClick"
          type="button"
          :class="styles.linkButton"
          @click="item.onClick"
        >
          {{ item.label }}
        </button>
        <span v-else :class="styles.current">{{ item.label }}</span>
        <span v-if="index < items.length - 1" :class="styles.separator" aria-hidden="true">/</span>
      </li>
    </ol>
  </nav>
</template>

// packages/react/src/Breadcrumb/Breadcrumb.tsx
import styles from '@larose-ui/styles/components/Breadcrumb/Breadcrumb.module.css';
import { sanitizeNavigationUrl } from '@larose-ui/core';

export interface BreadcrumbItem {
  label: string;
  href?: string;
  onClick?: () => void;
  current?: boolean;
}

export interface BreadcrumbProps {
  items: BreadcrumbItem[];
  'aria-label'?: string;
}

export function Breadcrumb({ items, 'aria-label': ariaLabel = 'Breadcrumb' }: BreadcrumbProps) {
  return (
    <nav className={styles.nav} aria-label={ariaLabel}>
      <ol className={styles.list}>
        {items.map((item, index) => {
          const isLast = index === items.length - 1;
          const isCurrent = item.current ?? isLast;
          const safeHref = sanitizeNavigationUrl(item.href);

          return (
            <li key={`${item.label}-${index}`} className={styles.item}>
              {isCurrent ? (
                <span className={styles.current} aria-current="page">
                  {item.label}
                </span>
              ) : safeHref ? (
                <a href={safeHref} className={styles.link} onClick={item.onClick}>
                  {item.label}
                </a>
              ) : item.onClick ? (
                <button type="button" className={styles.linkButton} onClick={item.onClick}>
                  {item.label}
                </button>
              ) : (
                <span className={styles.current}>{item.label}</span>
              )}
              {!isLast && (
                <span className={styles.separator} aria-hidden="true">
                  /
                </span>
              )}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}
