// packages/svelte/src/lib/components/Menu/Menu.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getAcceleratorContext, registerMenuAccelerator, createCombinedMenuKeyboard } from '../../accelerator/context';
  import { resolveMenuShortcut } from '../../accelerator/resolveMenuShortcut';
  import MnemonicLabel from '../Accelerator/MnemonicLabel.svelte';
  import type { MenuEntry, MenuItemConfig, MenuLayout, MenuPosition } from '../../Menu/types';
  import {
    isMenuItem,
    isMenuSubmenu,
    prepareMenuEntries,
    resolveMenuPanelPosition,
    splitCompactAndList,
  } from '../../Menu/utils';
  import styles from '@larose-ui/styles/components/Menu/Menu.module.css';

  let {
    children,
    entries,
    layout = 'large',
    title,
    open,
    onOpenChange,
    onEntrySelect,
    dimBackground = true,
    enableShortcuts = true,
    optionKey,
    enableTypeAhead = true,
    enableMnemonics = true,
    mnemonicVisible = false,
    class: className,
    style,
  }: {
    children?: Snippet;
    entries: MenuEntry[];
    layout?: MenuLayout;
    title?: string;
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    onEntrySelect?: (entry: MenuItemConfig) => boolean | void;
    dimBackground?: boolean;
    enableShortcuts?: boolean;
    optionKey?: boolean;
    enableTypeAhead?: boolean;
    enableMnemonics?: boolean;
    mnemonicVisible?: boolean;
    class?: string;
    style?: string;
  } = $props();

  const menuId = $props.id();
  let triggerEl = $state<HTMLSpanElement | null>(null);
  let internalOpen = $state(false);
  let position = $state<MenuPosition>({ x: 0, y: 0, placement: 'below' });
  let activeSubmenu = $state<string | null>(null);
  let typeAheadHighlightId = $state<string | null>(null);
  const isOpen = $derived(open ?? internalOpen);
  const prepared = $derived(prepareMenuEntries(entries));
  const split = $derived(splitCompactAndList(prepared, layout));

  function setOpen(next: boolean) {
    if (open === undefined) internalOpen = next;
    onOpenChange?.(next);
    if (!next) activeSubmenu = null;
  }

  function estimateHeight() {
    return Math.min(420, 48 + prepared.length * 36 + (layout !== 'large' ? 64 : 0));
  }
  function estimateWidth() {
    return layout === 'large' ? 240 : 280;
  }

  function openFromTrigger() {
    const rect = triggerEl?.getBoundingClientRect() ?? new DOMRect(100, 100, 120, 32);
    position = resolveMenuPanelPosition(rect, estimateWidth(), estimateHeight());
    setOpen(true);
  }

  function close() {
    setOpen(false);
  }

  function handleSelect(entry: MenuItemConfig) {
    const shouldClose = onEntrySelect?.(entry) !== false;
    if (shouldClose) close();
  }

  $effect(() => {
    if (!isOpen) return;
    if (!children) {
      position = {
        x: Math.max(16, (window.innerWidth - estimateWidth()) / 2),
        y: Math.max(16, (window.innerHeight - estimateHeight()) / 2),
        placement: 'below',
      };
    }
  });

  $effect(() => {
    if (!isOpen || !enableShortcuts) return;
    const keyboard = createCombinedMenuKeyboard({
      entries: prepared,
      activeSubmenuId: activeSubmenu,
      optionKey,
      onSelect: handleSelect,
      onClose: close,
      enableTypeAhead,
      enableMnemonics,
      mnemonicActive: mnemonicVisible,
    });
    const unregister = registerMenuAccelerator(menuId, keyboard.handler, true);
    const ctx = getAcceleratorContext();
    const onKey = (event: KeyboardEvent) => {
      keyboard.handler(event);
      typeAheadHighlightId = keyboard.getTypeAheadHighlightId();
    };
    if (!ctx) document.addEventListener('keydown', onKey, true);
    const onEsc = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
    };
    document.addEventListener('keydown', onEsc);
    return () => {
      unregister();
      if (!ctx) document.removeEventListener('keydown', onKey, true);
      document.removeEventListener('keydown', onEsc);
    };
  });
</script>

{#if children}
  <span bind:this={triggerEl} class={[styles.triggerWrap, className].filter(Boolean).join(' ')} {style} onclick={openFromTrigger}>
    {@render children()}
  </span>
{/if}

{#if isOpen}
  {#if dimBackground}
    <div class={styles.menuBackdrop} role="presentation" onclick={close}></div>
  {/if}
  <div
    id={menuId}
    class={styles.menu}
    role="menu"
    aria-label="Menu"
    style={`position:fixed;left:${position.x}px;top:${position.y}px;z-index:1000;${style ?? ''}`}
    onclick={(event) => event.stopPropagation()}
  >
    {#if title}<p class={styles.menuTitle}>{title}</p>{/if}
    {#if split.compact.length > 0}
      <div class={styles.compactRow} role="group" aria-label="Primary actions">
        {#each split.compact as item (item.id)}
          <button
            type="button"
            class={styles.compactTile}
            data-layout={layout}
            disabled={item.disabled}
            aria-label={layout === 'small' ? item.label : undefined}
            onclick={() => {
              if (item.disabled) return;
              item.onSelect?.();
              handleSelect(item);
            }}
          >
            {#if item.icon}<span class={styles.compactIcon}></span>{/if}
            {#if layout === 'medium'}<span class={styles.compactLabel}>{item.label}</span>{/if}
          </button>
        {/each}
      </div>
    {/if}
    <ul class={styles.list}>
      {#each split.list as entry, index (entry.type === 'separator' ? entry.id ?? `sep-${index}` : 'id' in entry ? entry.id : index)}
        {#if entry.type === 'separator'}
          <li class={styles.separator} role="separator"></li>
        {:else if isMenuSubmenu(entry)}
          {@const submenuResolved = resolveMenuShortcut(entry, { optionKey })}
          <li class={styles.submenuWrap} data-active={activeSubmenu === entry.id ? 'true' : undefined}>
            <button
              type="button"
              class={styles.submenuTrigger}
              role="menuitem"
              aria-haspopup="menu"
              aria-expanded={activeSubmenu === entry.id}
              disabled={entry.disabled}
              onmouseenter={() => (activeSubmenu = entry.id)}
              onfocus={() => (activeSubmenu = entry.id)}
            >
              <span class={styles.checkmark} aria-hidden="true"></span>
              {#if entry.icon}<span class={styles.icon}></span>{/if}
              <MnemonicLabel label={entry.label} showAccessKey={mnemonicVisible} class={styles.label} />
              {#if submenuResolved.display}
                <span class={styles.shortcut} dir="ltr">{submenuResolved.display}</span>
              {/if}
              <span class={styles.submenuChevron} aria-hidden="true">›</span>
            </button>
            {#if activeSubmenu === entry.id}
              <ul class={styles.submenu} role="menu" aria-label={entry.label} data-side="end">
                {#each entry.items as item (item.id)}
                  {@const resolved = resolveMenuShortcut(item, { optionKey })}
                  <li>
                    <button
                      type="button"
                      class={styles.item}
                      role="menuitem"
                      data-destructive={item.destructive ? 'true' : undefined}
                      data-typeahead-match={typeAheadHighlightId === item.id ? 'true' : undefined}
                      disabled={item.disabled}
                      aria-checked={item.selected ? true : undefined}
                      aria-keyshortcuts={resolved.ariaKeyshortcuts}
                      onclick={() => {
                        if (item.disabled) return;
                        item.onSelect?.();
                        handleSelect(item);
                      }}
                    >
                      <span class={styles.checkmark} aria-hidden="true">{item.selected ? '✓' : ''}</span>
                      {#if item.icon}<span class={styles.icon}></span>{/if}
                      <MnemonicLabel
                        label={item.label}
                        mnemonic={item.mnemonic}
                        showAccessKey={mnemonicVisible}
                        class={styles.label}
                      />
                      {#if resolved.display}<span class={styles.shortcut} dir="ltr">{resolved.display}</span>{/if}
                    </button>
                  </li>
                {/each}
              </ul>
            {/if}
          </li>
        {:else if isMenuItem(entry)}
          {@const resolved = resolveMenuShortcut(entry, { optionKey })}
          <li>
            <button
              type="button"
              class={styles.item}
              role="menuitem"
              data-destructive={entry.destructive ? 'true' : undefined}
              data-typeahead-match={typeAheadHighlightId === entry.id ? 'true' : undefined}
              disabled={entry.disabled}
              aria-checked={entry.selected ? true : undefined}
              aria-keyshortcuts={resolved.ariaKeyshortcuts}
              onclick={() => {
                if (entry.disabled) return;
                entry.onSelect?.();
                handleSelect(entry);
              }}
            >
              <span class={styles.checkmark} aria-hidden="true">{entry.selected ? '✓' : ''}</span>
              {#if entry.icon}<span class={styles.icon}></span>{/if}
              <MnemonicLabel
                label={entry.label}
                mnemonic={entry.mnemonic}
                showAccessKey={mnemonicVisible}
                class={styles.label}
              />
              {#if resolved.display}<span class={styles.shortcut} dir="ltr">{resolved.display}</span>{/if}
            </button>
          </li>
        {/if}
      {/each}
    </ul>
  </div>
{/if}

// packages/react/src/Menu/Menu.tsx
import {
  cloneElement,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ReactElement,
  type CSSProperties,
} from 'react';
import { ContextualMenuPortal } from '../Motion/OverlayPortal';
import { mergeStyles } from '../shared/styleProps';
import {
  resolveMenuShortcut,
  useAcceleratorContext,
  useCombinedMenuKeyboard,
  useMenuAcceleratorRegistration,
  MnemonicLabel,
} from '../accelerator';
import type { MenuEntry, MenuItemConfig, MenuLayout, MenuPosition } from './types';
import {
  isMenuItem,
  isMenuSubmenu,
  prepareMenuEntries,
  resolveMenuPanelPosition,
  splitCompactAndList,
} from './utils';
import styles from '@larose-ui/styles/components/Menu/Menu.module.css';

export interface MenuProps {
  children?: ReactElement;
  entries: MenuEntry[];
  layout?: MenuLayout;
  title?: string;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  onEntrySelect?: (entry: MenuItemConfig) => boolean | void;
  dimBackground?: boolean;
  /** When true, keyboard shortcuts activate menu items while open. Defaults to true. */
  enableShortcuts?: boolean;
  /** Passed from MenuBar for Option-key alternate accelerators. */
  optionKey?: boolean;
  /** Enable type-ahead letter matching while open. Defaults to true. */
  enableTypeAhead?: boolean;
  /** Enable Alt+key mnemonics while open. Defaults to true. */
  enableMnemonics?: boolean;
  /** When true, underline mnemonic access keys in labels. */
  mnemonicVisible?: boolean;
  className?: string;
  style?: CSSProperties;
}

function MenuItemRow({
  item,
  onSelect,
  optionKey,
  mnemonicVisible,
  typeAheadHighlightId,
}: {
  item: MenuItemConfig;
  onSelect: (entry: MenuItemConfig) => void;
  optionKey?: boolean;
  mnemonicVisible?: boolean;
  typeAheadHighlightId?: string | null;
}) {
  const resolved = resolveMenuShortcut(item, { optionKey });
  const isHighlighted = typeAheadHighlightId === item.id;

  return (
    <button
      type="button"
      className={styles.item}
      role="menuitem"
      data-destructive={item.destructive ? 'true' : undefined}
      data-typeahead-match={isHighlighted ? 'true' : undefined}
      disabled={item.disabled}
      aria-checked={item.selected ? true : undefined}
      aria-keyshortcuts={resolved.ariaKeyshortcuts}
      onClick={() => {
        if (item.disabled) return;
        item.onSelect?.();
        onSelect(item);
      }}
    >
      <span className={styles.checkmark} aria-hidden="true">
        {item.selected ? '✓' : ''}
      </span>
      {item.icon && <span className={styles.icon}>{item.icon}</span>}
      <MnemonicLabel
        label={item.label}
        mnemonic={item.mnemonic}
        showAccessKey={mnemonicVisible}
        className={styles.label}
      />
      {resolved.display && (
        <span className={styles.shortcut} dir="ltr">
          {resolved.display}
        </span>
      )}
    </button>
  );
}

function MenuPanel({
  menuId,
  entries,
  layout,
  title,
  onSelect,
  onClose,
  enableShortcuts,
  optionKey,
  enableTypeAhead = true,
  enableMnemonics = true,
  mnemonicVisible = false,
  isOpen,
}: {
  menuId: string;
  entries: MenuEntry[];
  layout: MenuLayout;
  title?: string;
  onSelect: (entry: MenuItemConfig) => void;
  onClose: () => void;
  enableShortcuts: boolean;
  optionKey?: boolean;
  enableTypeAhead?: boolean;
  enableMnemonics?: boolean;
  mnemonicVisible?: boolean;
  isOpen: boolean;
}) {
  const [activeSubmenu, setActiveSubmenu] = useState<string | null>(null);
  const [submenuSides, setSubmenuSides] = useState<Record<string, 'end' | 'start'>>({});
  const submenuTriggerRefs = useRef<Record<string, HTMLButtonElement | null>>({});
  const { compact, list } = useMemo(() => splitCompactAndList(entries, layout), [entries, layout]);

  const resolveSubmenuSide = useCallback((submenuId: string) => {
    const trigger = submenuTriggerRefs.current[submenuId];
    if (!trigger) return;

    const rect = trigger.getBoundingClientRect();
    const submenuWidth = 240;
    const gap = 8;
    const fitsEnd = rect.right + submenuWidth + gap <= window.innerWidth;
    const fitsStart = rect.left - submenuWidth - gap >= 0;
    const side: 'end' | 'start' = fitsEnd || !fitsStart ? 'end' : 'start';

    setSubmenuSides((current) =>
      current[submenuId] === side ? current : { ...current, [submenuId]: side },
    );
  }, []);

  const openSubmenu = useCallback(
    (submenuId: string) => {
      setActiveSubmenu(submenuId);
      requestAnimationFrame(() => resolveSubmenuSide(submenuId));
    },
    [resolveSubmenuSide],
  );

  const { handler: handleKeyboard, typeAheadHighlightId, resetTypeAhead } =
    useCombinedMenuKeyboard({
      entries,
      activeSubmenuId: activeSubmenu,
      optionKey,
      onSelect,
      onClose,
      enableTypeAhead: enableShortcuts && enableTypeAhead,
      enableMnemonics: enableShortcuts && enableMnemonics,
      mnemonicActive: mnemonicVisible,
    });

  const acceleratorContext = useAcceleratorContext();
  useMenuAcceleratorRegistration(menuId, handleKeyboard, isOpen && enableShortcuts);

  useEffect(() => {
    if (!isOpen) resetTypeAhead();
  }, [isOpen, resetTypeAhead]);

  // Fallback local listener when no AcceleratorProvider wraps the tree
  useEffect(() => {
    if (!isOpen || !enableShortcuts || acceleratorContext) return;

    const onKeyDown = (event: KeyboardEvent) => {
      handleKeyboard(event);
    };
    document.addEventListener('keydown', onKeyDown, true);
    return () => document.removeEventListener('keydown', onKeyDown, true);
  }, [acceleratorContext, enableShortcuts, handleKeyboard, isOpen]);

  useEffect(() => {
    if (!enableShortcuts || acceleratorContext) {
      const onKeyDown = (event: KeyboardEvent) => {
        if (event.key === 'Escape') onClose();
      };
      document.addEventListener('keydown', onKeyDown);
      return () => document.removeEventListener('keydown', onKeyDown);
    }
    return undefined;
  }, [acceleratorContext, enableShortcuts, onClose]);

  return (
    <>
      {title && <p className={styles.menuTitle}>{title}</p>}
      {compact.length > 0 && (
        <div className={styles.compactRow} role="group" aria-label="Primary actions">
          {compact.map((item) => (
            <button
              key={item.id}
              type="button"
              className={styles.compactTile}
              data-layout={layout}
              disabled={item.disabled}
              aria-label={layout === 'small' ? item.label : undefined}
              onClick={() => {
                if (item.disabled) return;
                item.onSelect?.();
                onSelect(item);
              }}
            >
              {item.icon && <span className={styles.compactIcon}>{item.icon}</span>}
              {layout === 'medium' && <span className={styles.compactLabel}>{item.label}</span>}
            </button>
          ))}
        </div>
      )}
      <ul className={styles.list}>
        {list.map((entry, index) => {
          if (entry.type === 'separator') {
            return <li key={entry.id ?? `sep-${index}`} className={styles.separator} role="separator" />;
          }

          if (isMenuSubmenu(entry)) {
            const submenuResolved = resolveMenuShortcut(entry, { optionKey });
            return (
              <li
                key={entry.id}
                className={styles.submenuWrap}
                data-active={activeSubmenu === entry.id ? 'true' : undefined}
              >
                <button
                  ref={(node) => {
                    submenuTriggerRefs.current[entry.id] = node;
                  }}
                  type="button"
                  className={styles.submenuTrigger}
                  role="menuitem"
                  aria-haspopup="menu"
                  aria-expanded={activeSubmenu === entry.id}
                  disabled={entry.disabled}
                  onMouseEnter={() => openSubmenu(entry.id)}
                  onFocus={() => openSubmenu(entry.id)}
                >
                  <span className={styles.checkmark} aria-hidden="true" />
                  {entry.icon && <span className={styles.icon}>{entry.icon}</span>}
                  <MnemonicLabel
                    label={entry.label}
                    showAccessKey={mnemonicVisible}
                    className={styles.label}
                  />
                  {submenuResolved.display && (
                    <span className={styles.shortcut} dir="ltr">
                      {submenuResolved.display}
                    </span>
                  )}
                  <span className={styles.submenuChevron} aria-hidden="true">
                    ›
                  </span>
                </button>
                {activeSubmenu === entry.id && (
                  <ul
                    className={styles.submenu}
                    role="menu"
                    aria-label={entry.label}
                    data-side={submenuSides[entry.id] === 'start' ? 'start' : 'end'}
                  >
                    {entry.items.map((item) => (
                      <li key={item.id}>
                        <MenuItemRow
                          item={item}
                          onSelect={onSelect}
                          optionKey={optionKey}
                          mnemonicVisible={mnemonicVisible}
                          typeAheadHighlightId={typeAheadHighlightId}
                        />
                      </li>
                    ))}
                  </ul>
                )}
              </li>
            );
          }

          if (isMenuItem(entry)) {
            return (
              <li key={entry.id}>
                <MenuItemRow
                  item={entry}
                  onSelect={onSelect}
                  optionKey={optionKey}
                  mnemonicVisible={mnemonicVisible}
                  typeAheadHighlightId={typeAheadHighlightId}
                />
              </li>
            );
          }

          return null;
        })}
      </ul>
    </>
  );
}

/**
 * General-purpose menu with small, medium, and large iOS/iPadOS layouts.
 * @see https://developer.apple.com/design/human-interface-guidelines/menus
 */
export function Menu({
  children,
  entries,
  layout = 'large',
  title,
  open,
  onOpenChange,
  onEntrySelect,
  dimBackground = true,
  enableShortcuts = true,
  optionKey,
  enableTypeAhead = true,
  enableMnemonics = true,
  mnemonicVisible = false,
  className,
  style,
}: MenuProps) {
  const menuId = useId();
  const triggerRef = useRef<HTMLSpanElement>(null);
  const [internalOpen, setInternalOpen] = useState(false);
  const [position, setPosition] = useState<MenuPosition>({ x: 0, y: 0, placement: 'below' });
  const isControlled = open !== undefined;
  const isOpen = isControlled ? open : internalOpen;

  const preparedEntries = useMemo(() => prepareMenuEntries(entries), [entries]);

  const setOpen = useCallback(
    (next: boolean) => {
      if (!isControlled) setInternalOpen(next);
      onOpenChange?.(next);
    },
    [isControlled, onOpenChange],
  );

  const estimateMenuHeight = useCallback(() => {
    return Math.min(420, 48 + preparedEntries.length * 36 + (layout !== 'large' ? 64 : 0));
  }, [layout, preparedEntries.length]);

  const estimateMenuWidth = useCallback(() => {
    return layout === 'large' ? 240 : 280;
  }, [layout]);

  const centerMenuOnViewport = useCallback(() => {
    const menuWidth = estimateMenuWidth();
    const menuHeight = estimateMenuHeight();
    setPosition({
      x: Math.max(16, (window.innerWidth - menuWidth) / 2),
      y: Math.max(16, (window.innerHeight - menuHeight) / 2),
      placement: 'below',
    });
  }, [estimateMenuHeight, estimateMenuWidth]);

  const openFromTrigger = useCallback(() => {
    const rect =
      triggerRef.current?.getBoundingClientRect() ?? new DOMRect(100, 100, 120, 32);
    const menuWidth = estimateMenuWidth();
    const menuHeight = estimateMenuHeight();
    const resolved = resolveMenuPanelPosition(rect, menuWidth, menuHeight);
    setPosition(resolved);
    setOpen(true);
  }, [estimateMenuHeight, estimateMenuWidth, setOpen]);

  const close = useCallback(() => setOpen(false), [setOpen]);

  const handleSelect = useCallback(
    (entry: MenuItemConfig) => {
      const shouldClose = onEntrySelect?.(entry) !== false;
      if (shouldClose) close();
    },
    [close, onEntrySelect],
  );

  useEffect(() => {
    if (!isOpen) return;

    if (!children) {
      centerMenuOnViewport();
      return;
    }

    if (open === undefined) return;

    const rect = triggerRef.current?.getBoundingClientRect() ?? new DOMRect(100, 100, 120, 32);
    const menuWidth = estimateMenuWidth();
    const menuHeight = estimateMenuHeight();
    setPosition(resolveMenuPanelPosition(rect, menuWidth, menuHeight));
  }, [
    centerMenuOnViewport,
    children,
    estimateMenuHeight,
    estimateMenuWidth,
    isOpen,
    open,
  ]);

  const bindTrigger = (child: ReactElement<Record<string, unknown>>) =>
    cloneElement(child, {
      onClick: (event: React.MouseEvent<Element>) => {
        (child.props.onClick as ((event: React.MouseEvent<Element>) => void) | undefined)?.(event);
        if (isOpen) {
          close();
          return;
        }
        openFromTrigger();
      },
      'aria-haspopup': 'menu',
      'aria-expanded': isOpen,
      'aria-controls': isOpen ? menuId : undefined,
    });

  const menuPortal = (
    <ContextualMenuPortal
      open={isOpen}
      onClose={close}
      placement={position.placement === 'above' ? 'top' : 'bottom'}
      showBackdrop={dimBackground}
      backdropClassName={styles.menuBackdrop}
      surfaceId={menuId}
      surfaceClassName={styles.menu}
      surfaceRole="menu"
      aria-label="Menu"
      surfaceStyle={mergeStyles({ left: position.x, top: position.y }, style)}
      onSurfaceClick={(event) => event.stopPropagation()}
      anchorRef={triggerRef}
    >
      <MenuPanel
        menuId={menuId}
        entries={preparedEntries}
        layout={layout}
        title={title}
        onSelect={handleSelect}
        onClose={close}
        enableShortcuts={enableShortcuts}
        optionKey={optionKey}
        enableTypeAhead={enableTypeAhead}
        enableMnemonics={enableMnemonics}
        mnemonicVisible={mnemonicVisible}
        isOpen={isOpen}
      />
    </ContextualMenuPortal>
  );

  if (!children) {
    return menuPortal;
  }

  if (!isValidElement(children)) {
    throw new Error('Menu expects a single React element child when used with a trigger.');
  }

  return (
    <>
      <span ref={triggerRef} className={[styles.triggerWrap, className].filter(Boolean).join(' ')} style={style}>
        {bindTrigger(children as ReactElement<Record<string, unknown>>)}
      </span>
      {menuPortal}
    </>
  );
}

export type { MenuEntry, MenuItemConfig, MenuLayout, MenuSubmenuConfig } from './types';
export { prepareMenuEntries, splitCompactAndList, MAX_SUBMENU_ITEMS } from './utils';
