// packages/svelte/src/lib/components/EditMenu/EditMenu.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type {
    EditMenuContext,
    EditMenuInputMode,
    EditMenuItemConfig,
    EditMenuPosition,
    EditMenuResolvedAction,
    EditMenuVariant,
    StandardEditActionId,
  } from '../../EditMenu/types';
  import {
    buildEditMenuActions,
    canExpandCompactMenu,
    compactVisibleCount,
    filterVisibleEditMenuActions,
    LONG_PRESS_MS,
    resolveEditMenuPosition,
    resolveEditMenuVariant,
  } from '../../EditMenu/utils';
  import { portal } from '../../utils/portal';
  import styles from '@larose-ui/styles/components/EditMenu/EditMenu.module.css';
  import { cn } from '../../utils/cn';

  let {
    children,
    context,
    customActions = [],
    includeStandardActions = true,
    variant = 'auto',
    inputMode = 'auto',
    placement = 'auto',
    open,
    onOpenChange,
    onAction,
    onStandardAction,
    longPress = true,
    dimBackground = true,
    class: className,
    style,
  }: {
    children?: Snippet;
    context: EditMenuContext;
    customActions?: EditMenuItemConfig[];
    includeStandardActions?: boolean;
    variant?: EditMenuVariant;
    inputMode?: EditMenuInputMode;
    placement?: 'above' | 'below' | 'auto';
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    onAction?: (actionId: string) => void;
    onStandardAction?: (actionId: StandardEditActionId) => void;
    longPress?: boolean;
    dimBackground?: boolean;
    class?: string;
    style?: string;
  } = $props();

  const menuId = $props.id();
  let triggerEl = $state<HTMLSpanElement | null>(null);
  let internalOpen = $state(false);
  let resolvedVariant = $state<'compact' | 'context'>(
    resolveEditMenuVariant(variant, inputMode, 'mouse'),
  );
  let expanded = $state(false);
  let position = $state<EditMenuPosition>({
    x: 100,
    y: 100,
    placement: 'below',
    pointerOffset: 110,
  });
  let longPressTimer: number | null = null;
  const isOpen = $derived(open ?? internalOpen);
  const actions = $derived(
    filterVisibleEditMenuActions(
      buildEditMenuActions(context, customActions, {
        includeStandard: includeStandardActions,
        onStandardAction,
      }),
    ),
  );
  const showCompact = $derived(resolvedVariant === 'compact' && !expanded);

  function setOpen(next: boolean) {
    if (!next) expanded = false;
    if (open === undefined) internalOpen = next;
    onOpenChange?.(next);
  }

  function measureAndOpen(pointerType: string, anchorRect?: DOMRect) {
    const resolved = resolveEditMenuVariant(variant, inputMode, pointerType);
    resolvedVariant = expanded ? 'context' : resolved;
    const rect =
      anchorRect ??
      triggerEl?.getBoundingClientRect() ??
      new DOMRect(window.innerWidth / 2 - 40, window.innerHeight / 2, 80, 24);
    const menuWidth =
      resolved === 'compact' && !expanded
        ? Math.min(320, actions.length * 72 + 48)
        : 220;
    const menuHeight =
      resolved === 'compact' && !expanded
        ? 40
        : Math.min(360, actions.length * 36 + 16);
    position = resolveEditMenuPosition(rect, menuWidth, menuHeight, placement);
    setOpen(true);
  }

  function clearLongPress() {
    if (longPressTimer !== null) {
      window.clearTimeout(longPressTimer);
      longPressTimer = null;
    }
  }

  function handleSelect(action: EditMenuResolvedAction) {
    action.onSelect?.();
    onAction?.(action.id);
    setOpen(false);
  }

  function handleExpand() {
    expanded = true;
    resolvedVariant = 'context';
    const rect =
      triggerEl?.getBoundingClientRect() ?? new DOMRect(position.x, position.y, 80, 24);
    position = resolveEditMenuPosition(
      rect,
      220,
      Math.min(360, actions.length * 36 + 16),
      placement,
    );
  }

  $effect(() => {
    if (!isOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setOpen(false);
    };
    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  });
</script>

<span
  bind:this={triggerEl}
  class={cn(styles.triggerWrap, className)}
  {style}
  oncontextmenu={(event) => {
    event.preventDefault();
    measureAndOpen('mouse', new DOMRect(event.clientX, event.clientY, 1, 1));
  }}
  ondblclick={(event) =>
    measureAndOpen('touch', (event.currentTarget as HTMLElement).getBoundingClientRect())}
  onpointerdown={(event) => {
    if (!longPress || event.pointerType === 'mouse') return;
    clearLongPress();
    longPressTimer = window.setTimeout(() => {
      measureAndOpen(
        event.pointerType,
        (event.currentTarget as HTMLElement).getBoundingClientRect(),
      );
    }, LONG_PRESS_MS);
  }}
  onpointerup={clearLongPress}
  onpointercancel={clearLongPress}
  onpointerleave={clearLongPress}
>
  {@render children?.()}
</span>

{#if isOpen && actions.length > 0}
  <div use:portal>
    {#if dimBackground}
      <div class={styles.menuBackdrop} role="presentation" onclick={() => setOpen(false)}></div>
    {/if}
    <div
      class={showCompact ? styles.compactWrap : styles.contextWrap}
      role={showCompact ? 'toolbar' : undefined}
      aria-label="Edit menu"
      data-placement={position.placement}
      style={`position:fixed;left:${position.x}px;top:${position.y}px;--lr-edit-menu-pointer-x:${position.pointerOffset}px;z-index:1000;${style ?? ''}`}
    >
      <span
        class={styles.pointer}
        aria-hidden="true"
        data-placement={position.placement}
        style="--lr-edit-menu-pointer-offset:var(--lr-edit-menu-pointer-x)"
      ></span>
      {#if showCompact}
        <div id={menuId} class={styles.compactBar}>
          {#each actions.slice(0, compactVisibleCount(actions.length)) as action, index (action.id)}
            {#if index > 0}<span class={styles.compactDivider} aria-hidden="true"></span>{/if}
            <button
              type="button"
              class={styles.compactItem}
              data-destructive={action.destructive ? 'true' : undefined}
              disabled={action.disabled}
              onclick={() => handleSelect(action)}
            >
              {action.label}
            </button>
          {/each}
          {#if canExpandCompactMenu(actions.length)}
            <span class={styles.compactDivider} aria-hidden="true"></span>
            <button
              type="button"
              class={styles.expandButton}
              aria-label="More edit actions"
              aria-haspopup="menu"
              onclick={handleExpand}
            >
              <svg viewBox="0 0 12 12" width="0.75rem" height="0.75rem" aria-hidden="true">
                <path
                  d="M4 2.5 8 6l-4 3.5"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="1.5"
                  stroke-linecap="round"
                />
              </svg>
            </button>
          {/if}
        </div>
      {:else}
        <div
          id={menuId}
          class={styles.contextMenu}
          role="menu"
          aria-label="Edit menu"
          style="position:relative"
        >
          <ul class={styles.list}>
            {#each actions as action, index (action.id)}
              {@const prev = actions[index - 1]}
              {@const showSeparator =
                index > 0 && (prev?.group ?? 'other') !== (action.group ?? 'other')}
              {#if showSeparator}<li class={styles.separator} role="separator"></li>{/if}
              <li>
                <button
                  type="button"
                  class={styles.contextItem}
                  role="menuitem"
                  data-destructive={action.destructive ? 'true' : undefined}
                  disabled={action.disabled}
                  onclick={() => handleSelect(action)}
                >
                  {#if action.icon}<span class={styles.icon}></span>{/if}
                  <span class={styles.label}>{action.label}</span>
                </button>
              </li>
            {/each}
          </ul>
        </div>
      {/if}
    </div>
  </div>
{/if}

// packages/react/src/EditMenu/EditMenu.tsx
import {
  cloneElement,
  Fragment,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type MouseEvent as ReactMouseEvent,
  type ReactElement,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import type {
  EditMenuContext,
  EditMenuInputMode,
  EditMenuItemConfig,
  EditMenuPosition,
  EditMenuResolvedAction,
  EditMenuVariant,
  StandardEditActionId,
} from './types';
import {
  buildEditMenuActions,
  canExpandCompactMenu,
  compactVisibleCount,
  filterVisibleEditMenuActions,
  LONG_PRESS_MS,
  resolveEditMenuPosition,
  resolveEditMenuVariant,
} from './utils';
import styles from './EditMenu.module.css';

export interface EditMenuProps {
  children: ReactElement;
  context: EditMenuContext;
  /** Custom commands listed near related system-provided ones. */
  customActions?: EditMenuItemConfig[];
  /** Include standard Cut, Copy, Paste, etc. Defaults to true. */
  includeStandardActions?: boolean;
  variant?: EditMenuVariant;
  inputMode?: EditMenuInputMode;
  placement?: 'above' | 'below' | 'auto';
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  onAction?: (actionId: string) => void;
  onStandardAction?: (actionId: StandardEditActionId) => void;
  /** Touch-and-hold / long-press to reveal compact edit menu. */
  longPress?: boolean;
  dimBackground?: boolean;
}

function ChevronIcon() {
  return (
    <svg viewBox="0 0 12 12" width="0.75rem" height="0.75rem" aria-hidden="true">
      <path d="M4 2.5 8 6l-4 3.5" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    </svg>
  );
}

function EditMenuPointer({ placement }: { placement: EditMenuPosition['placement'] }) {
  return (
    <span
      className={styles.pointer}
      aria-hidden="true"
      data-placement={placement}
      style={{ ['--lr-edit-menu-pointer-offset' as string]: 'var(--lr-edit-menu-pointer-x)' }}
    />
  );
}

function CompactEditMenu({
  actions,
  position,
  menuId,
  onSelect,
  onExpand,
  canExpand,
}: {
  actions: EditMenuResolvedAction[];
  position: EditMenuPosition;
  menuId: string;
  onSelect: (action: EditMenuResolvedAction) => void;
  onExpand: () => void;
  canExpand: boolean;
}) {
  const visible = actions.slice(0, compactVisibleCount(actions.length));

  return (
    <div
      className={styles.compactWrap}
      data-placement={position.placement}
      style={{
        left: position.x,
        top: position.y,
        ['--lr-edit-menu-pointer-x' as string]: `${position.pointerOffset}px`,
      }}
      role="toolbar"
      aria-label="Edit menu"
    >
      <EditMenuPointer placement={position.placement} />
      <div id={menuId} className={styles.compactBar}>
        {visible.map((action, index) => (
          <span key={action.id} style={{ display: 'contents' }}>
            {index > 0 && <span className={styles.compactDivider} aria-hidden="true" />}
            <button
              type="button"
              className={styles.compactItem}
              role="button"
              data-destructive={action.destructive ? 'true' : undefined}
              disabled={action.disabled}
              onClick={() => onSelect(action)}
            >
              {action.label}
            </button>
          </span>
        ))}
        {canExpand && (
          <>
            <span className={styles.compactDivider} aria-hidden="true" />
            <button
              type="button"
              className={styles.expandButton}
              aria-label="More edit actions"
              aria-haspopup="menu"
              onClick={onExpand}
            >
              <ChevronIcon />
            </button>
          </>
        )}
      </div>
    </div>
  );
}

function ContextEditMenu({
  actions,
  position,
  menuId,
  onSelect,
}: {
  actions: EditMenuResolvedAction[];
  position: EditMenuPosition;
  menuId: string;
  onSelect: (action: EditMenuResolvedAction) => void;
}) {
  return (
    <div
      className={styles.contextWrap}
      data-placement={position.placement}
      style={{
        left: position.x,
        top: position.y,
        ['--lr-edit-menu-pointer-x' as string]: `${position.pointerOffset}px`,
      }}
    >
      <EditMenuPointer placement={position.placement} />
      <div
        id={menuId}
        className={styles.contextMenu}
        role="menu"
        aria-label="Edit menu"
        style={{ position: 'relative' }}
      >
        <ul className={styles.list}>
          {actions.map((action, index) => {
            const prev = actions[index - 1];
            const showSeparator =
              index > 0 && (prev?.group ?? 'other') !== (action.group ?? 'other');
            return (
              <Fragment key={action.id}>
                {showSeparator && <li className={styles.separator} role="separator" />}
                <li>
                  <button
                    type="button"
                    className={styles.contextItem}
                    role="menuitem"
                    data-destructive={action.destructive ? 'true' : undefined}
                    disabled={action.disabled}
                    onClick={() => onSelect(action)}
                  >
                    {action.icon && <span className={styles.icon}>{action.icon}</span>}
                    <span className={styles.label}>{action.label}</span>
                  </button>
                </li>
              </Fragment>
            );
          })}
        </ul>
      </div>
    </div>
  );
}

/**
 * Edit menu for changing selected content — compact horizontal bar or vertical context menu.
 * @see https://developer.apple.com/design/human-interface-guidelines/edit-menus
 */
export function EditMenu({
  children,
  context,
  customActions = [],
  includeStandardActions = true,
  variant = 'auto',
  inputMode = 'auto',
  placement = 'auto',
  open,
  onOpenChange,
  onAction,
  onStandardAction,
  longPress = true,
  dimBackground = true,
}: EditMenuProps) {
  const menuId = useId();
  const triggerRef = useRef<HTMLSpanElement>(null);
  const [internalOpen, setInternalOpen] = useState(false);
  const [resolvedVariant, setResolvedVariant] = useState<'compact' | 'context'>(() =>
    resolveEditMenuVariant(variant, inputMode, 'mouse'),
  );
  const [expanded, setExpanded] = useState(false);
  const [position, setPosition] = useState<EditMenuPosition>({
    x: 100,
    y: 100,
    placement: 'below',
    pointerOffset: 110,
  });
  const longPressTimer = useRef<number | null>(null);
  const isControlled = open !== undefined;
  const isOpen = isControlled ? open : internalOpen;

  const actions = useMemo(
    () =>
      filterVisibleEditMenuActions(
        buildEditMenuActions(context, customActions, {
          includeStandard: includeStandardActions,
          onStandardAction,
        }),
      ),
    [context, customActions, includeStandardActions, onStandardAction],
  );

  const setOpen = useCallback(
    (next: boolean) => {
      if (!next) setExpanded(false);
      if (!isControlled) setInternalOpen(next);
      onOpenChange?.(next);
    },
    [isControlled, onOpenChange],
  );

  const measureAndOpen = useCallback(
    (pointerType: string, anchorRect?: DOMRect) => {
      const resolved = resolveEditMenuVariant(variant, inputMode, pointerType);
      setResolvedVariant(expanded ? 'context' : resolved);

      const rect =
        anchorRect ??
        triggerRef.current?.getBoundingClientRect() ??
        new DOMRect(window.innerWidth / 2 - 40, window.innerHeight / 2, 80, 24);

      const menuWidth = resolved === 'compact' && !expanded ? Math.min(320, actions.length * 72 + 48) : 220;
      const menuHeight = resolved === 'compact' && !expanded ? 40 : Math.min(360, actions.length * 36 + 16);
      setPosition(resolveEditMenuPosition(rect, menuWidth, menuHeight, placement));
      setOpen(true);
    },
    [actions.length, expanded, inputMode, placement, setOpen, variant],
  );

  const close = useCallback(() => setOpen(false), [setOpen]);

  const handleSelect = useCallback(
    (action: EditMenuResolvedAction) => {
      action.onSelect?.();
      onAction?.(action.id);
      close();
    },
    [close, onAction],
  );

  const handleExpand = useCallback(() => {
    setExpanded(true);
    setResolvedVariant('context');
    const rect =
      triggerRef.current?.getBoundingClientRect() ??
      new DOMRect(position.x, position.y, 80, 24);
    setPosition(resolveEditMenuPosition(rect, 220, Math.min(360, actions.length * 36 + 16), placement));
  }, [actions.length, placement, position.x, position.y]);

  useEffect(() => {
    if (!isOpen || variant === 'auto') return;
    setResolvedVariant(variant);
    const rect =
      triggerRef.current?.getBoundingClientRect() ?? new DOMRect(100, 100, 160, 32);
    const menuWidth = variant === 'compact' ? Math.min(320, actions.length * 72 + 48) : 220;
    const menuHeight = variant === 'compact' ? 40 : Math.min(360, actions.length * 36 + 16);
    setPosition(resolveEditMenuPosition(rect, menuWidth, menuHeight, placement));
  }, [actions.length, isOpen, placement, variant]);

  useEffect(() => {
    if (!isOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
    };
    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  }, [close, isOpen]);

  const clearLongPress = useCallback(() => {
    if (longPressTimer.current !== null) {
      window.clearTimeout(longPressTimer.current);
      longPressTimer.current = null;
    }
  }, []);

  const bindTrigger = (child: ReactElement<Record<string, unknown>>) =>
    cloneElement(child, {
      onContextMenu: (event: ReactMouseEvent<Element>) => {
        (child.props.onContextMenu as ((event: ReactMouseEvent<Element>) => void) | undefined)?.(event);
        event.preventDefault();
        measureAndOpen('mouse', new DOMRect(event.clientX, event.clientY, 1, 1));
      },
      onDoubleClick: (event: React.MouseEvent<Element>) => {
        (child.props.onDoubleClick as ((event: React.MouseEvent<Element>) => void) | undefined)?.(event);
        measureAndOpen('touch', (event.currentTarget as HTMLElement).getBoundingClientRect());
      },
      onPointerDown: (event: React.PointerEvent<Element>) => {
        (child.props.onPointerDown as ((event: React.PointerEvent<Element>) => void) | undefined)?.(event);
        if (!longPress || event.pointerType === 'mouse') return;
        clearLongPress();
        longPressTimer.current = window.setTimeout(() => {
          measureAndOpen(event.pointerType, (event.currentTarget as HTMLElement).getBoundingClientRect());
        }, LONG_PRESS_MS);
      },
      onPointerUp: (event: React.PointerEvent<Element>) => {
        (child.props.onPointerUp as ((event: React.PointerEvent<Element>) => void) | undefined)?.(event);
        clearLongPress();
      },
      onPointerCancel: (event: React.PointerEvent<Element>) => {
        (child.props.onPointerCancel as ((event: React.PointerEvent<Element>) => void) | undefined)?.(event);
        clearLongPress();
      },
      onPointerLeave: (event: React.PointerEvent<Element>) => {
        (child.props.onPointerLeave as ((event: React.PointerEvent<Element>) => void) | undefined)?.(event);
        clearLongPress();
      },
    });

  if (!isValidElement(children)) {
    throw new Error('EditMenu expects a single React element child.');
  }

  const showCompact = resolvedVariant === 'compact' && !expanded;
  const showContext = resolvedVariant === 'context' || expanded;

  return (
    <>
      <span ref={triggerRef} className={styles.triggerWrap}>
        {bindTrigger(children as ReactElement<Record<string, unknown>>)}
      </span>
      {isOpen &&
        actions.length > 0 &&
        createPortal(
          <>
            {dimBackground && (
              <div className={styles.menuBackdrop} role="presentation" onClick={close} />
            )}
            {showCompact && (
              <CompactEditMenu
                menuId={menuId}
                actions={actions}
                position={position}
                onSelect={handleSelect}
                onExpand={handleExpand}
                canExpand={canExpandCompactMenu(actions.length)}
              />
            )}
            {showContext && (
              <ContextEditMenu
                menuId={menuId}
                actions={actions}
                position={position}
                onSelect={handleSelect}
              />
            )}
          </>,
          document.body,
        )}
    </>
  );
}

/** Read-only selectable text region for edit menu demos. */
export function EditMenuSelection({
  children,
  selected = false,
  className,
  ...rest
}: {
  children: ReactNode;
  selected?: boolean;
  className?: string;
} & React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      {...rest}
      className={[styles.selectionPreview, className].filter(Boolean).join(' ')}
      data-selected={selected ? 'true' : undefined}
    >
      {children}
    </div>
  );
}

export type {
  EditMenuContext,
  EditMenuItemConfig,
  EditMenuVariant,
  EditMenuInputMode,
  EditMenuContentType,
  StandardEditActionId,
} from './types';
export {
  buildEditMenuActions,
  resolveEditMenuPosition,
  resolveEditMenuVariant,
  isStandardActionAvailable,
  filterVisibleEditMenuActions,
} from './utils';
