// packages/vue/src/components/Card/Card.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/Card/Card.module.css';
import { cn } from '../../utils/cn';
import { useComponentDefaults } from '../../composables/useComponentDefaults';
import { computed, useSlots } from 'vue';

const props = withDefaults(
  defineProps<{
    title?: string;
    description?: string;
    padding?: 'none' | 'sm' | 'md' | 'lg';
    class?: string;
  }>(),
  {
    padding: 'md',
  },
);

const merged = useComponentDefaults('Card', props);
const slots = useSlots();

/** Match React: convenience props + slots compose together; bare default-only = composition passthrough. */
const usesConvenienceApi = computed(() =>
  Boolean(props.title || props.description || slots.body || slots.footer),
);
</script>

<template>
  <article :class="cn(styles.card, merged.class)" :data-padding="merged.padding">
    <template v-if="usesConvenienceApi">
      <header v-if="merged.title || merged.description" :class="styles.header">
        <h3 v-if="merged.title" :class="styles.title">{{ merged.title }}</h3>
        <p v-if="merged.description" :class="styles.description">{{ merged.description }}</p>
      </header>
      <div v-if="$slots.default || $slots.body" :class="styles.body">
        <slot />
        <slot name="body" />
      </div>
      <footer v-if="$slots.footer" :class="styles.footer">
        <slot name="footer" />
      </footer>
    </template>
    <slot v-else />
  </article>
</template>

// packages/svelte/src/lib/components/Card/Card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Card/Card.module.css';
  import { cn } from '../../utils/cn';
  import { getComponentDefaults } from '../../theme/context';

  interface Props {
    title?: string;
    description?: string;
    padding?: 'none' | 'sm' | 'md' | 'lg';
    class?: string;
    style?: string;
    children?: Snippet;
    body?: Snippet;
    footer?: Snippet;
  }

  let props: Props = $props();
  const merged = $derived(getComponentDefaults('Card', props));

  /** Match React: convenience props + snippets compose together; children-only = composition passthrough. */
  const usesConvenienceApi = $derived(
    Boolean(merged.title || merged.description || merged.body || merged.footer),
  );
</script>

<article class={cn(styles.card, merged.class)} style={merged.style} data-padding={merged.padding ?? 'md'}>
  {#if usesConvenienceApi}
    {#if merged.title || merged.description}
      <header class={styles.header}>
        {#if merged.title}<h3 class={styles.title}>{merged.title}</h3>{/if}
        {#if merged.description}<p class={styles.description}>{merged.description}</p>{/if}
      </header>
    {/if}
    {#if merged.children || merged.body}
      <div class={styles.body}>
        {#if merged.children}{@render merged.children()}{/if}
        {#if merged.body}{@render merged.body()}{/if}
      </div>
    {/if}
    {#if merged.footer}
      <footer class={styles.footer}>{@render merged.footer()}</footer>
    {/if}
  {:else if merged.children}
    {@render merged.children()}
  {/if}
</article>
