// packages/react/src/provider/LaRoseProvider.tsx
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useRef,
  type ReactNode,
} from 'react';
import type { Density, ThemeMode } from '@larose-ui/core';
import { applyResolvedTheme, type ColorTokens } from '@larose-ui/tokens';
import {
  createTheme,
  normalizeThemeInput,
  resolveTheme,
  type ComponentConfiguration,
  type LaRoseTheme,
  type LaRoseThemeInput,
} from '@larose-ui/themes';
import { MotionProvider, type MotionConfig } from '../Motion/MotionContext';
import {
  ThemeCustomizationContext,
  type ThemeCustomizationContextValue,
} from '../theme/ThemeCustomizationContext';

export interface LaRoseConfig {
  theme?: ThemeMode;
  density?: Density;
  tenantId?: string;
  brandColors?: Partial<ColorTokens>;
  motion?: MotionConfig;
  /** Full theme configuration with token overrides. */
  themeConfig?: LaRoseThemeInput | LaRoseTheme;
  /** Per-component defaults, tokens, and motion overrides. */
  components?: ComponentConfiguration;
}

const LaRoseContext = createContext<LaRoseConfig>({
  theme: 'light',
  density: 'comfortable',
});

export function useLaRose(): LaRoseConfig {
  return useContext(LaRoseContext);
}

export interface LaRoseProviderProps extends LaRoseConfig {
  children: ReactNode;
}

export function LaRoseProvider({
  children,
  theme = 'light',
  density = 'comfortable',
  tenantId,
  brandColors,
  motion,
  themeConfig,
  components = {},
}: LaRoseProviderProps) {
  const ref = useRef<HTMLDivElement>(null);

  const normalizedTheme = useMemo(
    () =>
      themeConfig
        ? 'tokens' in themeConfig && themeConfig.tokens
          ? (themeConfig as LaRoseTheme)
          : createTheme(themeConfig)
        : createTheme({ preset: 'refined' }),
    [themeConfig],
  );

  const resolved = useMemo(
    () =>
      resolveTheme({
        theme: normalizedTheme,
        density,
        mode: theme,
        brandColors,
        components,
      }),
    [normalizedTheme, density, theme, brandColors, components],
  );

  const customizationValue = useMemo<ThemeCustomizationContextValue>(
    () => ({
      theme: normalizedTheme,
      resolved,
      components,
    }),
    [normalizedTheme, resolved, components],
  );

  const providerConfig = useMemo<LaRoseConfig>(
    () => ({
      theme,
      density,
      tenantId,
      brandColors,
      motion,
      themeConfig: normalizedTheme,
      components,
    }),
    [theme, density, tenantId, brandColors, motion, normalizedTheme, components],
  );

  useEffect(() => {
    if (!ref.current) return;

    applyResolvedTheme(ref.current, {
      mode: resolved.mode,
      density: resolved.density,
      tokenOverrides: resolved.tokenOverrides,
      brandColors: resolved.brandColors,
      componentTokenOverrides: resolved.componentTokenOverrides,
      presetId: resolved.preset,
    });

    if (tenantId) {
      ref.current.dataset.lrTenant = tenantId;
    }
  }, [resolved, tenantId]);

  const motionConfig = useMemo<MotionConfig>(
    () => ({
      preset: motion?.preset ?? normalizedTheme.motion?.preset,
      reducedMotion: motion?.reducedMotion ?? normalizedTheme.motion?.reducedMotion,
    }),
    [motion, normalizedTheme.motion],
  );

  return (
    <LaRoseContext.Provider value={providerConfig}>
      <ThemeCustomizationContext.Provider value={customizationValue}>
        <MotionProvider {...motionConfig}>
          <div ref={ref} data-lr-provider style={{ minHeight: 'inherit' }}>
            {children}
          </div>
        </MotionProvider>
      </ThemeCustomizationContext.Provider>
    </LaRoseContext.Provider>
  );
}

export { createTheme, normalizeThemeInput, resolveTheme };
export type {
  LaRoseTheme,
  LaRoseThemeInput,
  ComponentConfiguration,
} from '@larose-ui/themes';

// packages/vue/src/provider/LaRoseProvider.vue
<script setup lang="ts">
import { computed, onMounted, provide, ref, watch } from 'vue';
import type { Density, ThemeMode } from '@larose-ui/core';
import { applyResolvedTheme, type ColorTokens } from '@larose-ui/tokens';
import {
  createTheme,
  resolveTheme,
  type ComponentConfiguration,
  type LaRoseTheme,
  type LaRoseThemeInput,
} from '@larose-ui/themes';
import { themeCustomizationKey } from '../theme/types';
import type { ThemeCustomizationContextValue } from '../theme/types';

export interface LaRoseProviderProps {
  theme?: ThemeMode;
  density?: Density;
  tenantId?: string;
  brandColors?: Partial<ColorTokens>;
  themeConfig?: LaRoseThemeInput | LaRoseTheme;
  components?: ComponentConfiguration;
}

const props = withDefaults(defineProps<LaRoseProviderProps>(), {
  theme: 'light',
  density: 'comfortable',
  components: () => ({}),
});

const rootRef = ref<HTMLDivElement | null>(null);

const normalizedTheme = computed(() =>
  props.themeConfig
    ? 'tokens' in props.themeConfig && props.themeConfig.tokens
      ? (props.themeConfig as LaRoseTheme)
      : createTheme(props.themeConfig)
    : createTheme({ preset: 'refined' }),
);

const resolved = computed(() =>
  resolveTheme({
    theme: normalizedTheme.value,
    density: props.density,
    mode: props.theme,
    brandColors: props.brandColors,
    components: props.components,
  }),
);

const customizationValue = computed<ThemeCustomizationContextValue>(() => ({
  theme: normalizedTheme.value,
  resolved: resolved.value,
  components: props.components,
}));

provide(themeCustomizationKey, customizationValue);

function applyTheme() {
  if (!rootRef.value) return;
  applyResolvedTheme(rootRef.value, {
    mode: resolved.value.mode,
    density: resolved.value.density,
    tokenOverrides: resolved.value.tokenOverrides,
    brandColors: resolved.value.brandColors,
    componentTokenOverrides: resolved.value.componentTokenOverrides,
    presetId: resolved.value.preset,
  });
  if (props.tenantId) {
    rootRef.value.dataset.lrTenant = props.tenantId;
  }
}

onMounted(applyTheme);
watch(resolved, applyTheme);
watch(() => props.tenantId, applyTheme);
</script>

<template>
  <div ref="rootRef" data-lr-provider style="min-height: inherit">
    <slot />
  </div>
</template>
