// packages/enterprise-react/src/security/SensitiveAction.tsx
import { useCallback, useState } from 'react';
import { Dialog, Button } from '@larose-ui/react';
import { useEnvironment } from '@larose-ui/runtime-react';
import { useOptionalObservability } from '@larose-ui/observability-react';

export interface SensitiveActionProps {
  label: string;
  description?: string;
  confirmLabel?: string;
  cancelLabel?: string;
  requireProductionConfirm?: boolean;
  onConfirm: () => void | Promise<void>;
}

export function SensitiveAction({
  label,
  description = 'This action may have irreversible consequences.',
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  requireProductionConfirm = true,
  onConfirm,
}: SensitiveActionProps) {
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const environment = useEnvironment();
  const observability = useOptionalObservability();
  const isProduction = environment === 'production';

  const handleConfirm = useCallback(async () => {
    setBusy(true);
    try {
      observability?.track({
        type: 'interaction',
        component: 'SensitiveAction',
        metadata: { label, environment },
      });
      await onConfirm();
      setOpen(false);
    } finally {
      setBusy(false);
    }
  }, [environment, label, observability, onConfirm]);

  return (
    <>
      <Button variant="destructive" onClick={() => setOpen(true)}>
        {label}
      </Button>
      <Dialog
        open={open}
        onClose={() => setOpen(false)}
        title={label}
        description={
          isProduction && requireProductionConfirm
            ? `${description} You are in production.`
            : description
        }
        confirmLabel={confirmLabel}
        cancelLabel={cancelLabel}
        onConfirm={() => void handleConfirm()}
        loading={busy}
        variant="destructive"
      />
    </>
  );
}

// packages/enterprise-vue/src/SensitiveAction.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Dialog, Button } from '@larose-ui/vue';
import { useEnvironment } from '@larose-ui/runtime-vue';
import { useOptionalObservability } from '@larose-ui/observability-vue';

const props = withDefaults(
  defineProps<{
    label: string;
    description?: string;
    confirmLabel?: string;
    cancelLabel?: string;
    requireProductionConfirm?: boolean;
  }>(),
  {
    description: 'This action may have irreversible consequences.',
    confirmLabel: 'Confirm',
    cancelLabel: 'Cancel',
    requireProductionConfirm: true,
  },
);

const emit = defineEmits<{ confirm: [] }>();

const open = ref(false);
const busy = ref(false);
const environment = useEnvironment();
const observability = useOptionalObservability();
const isProduction = environment === 'production';

async function handleConfirm() {
  busy.value = true;
  try {
    observability?.track({
      type: 'interaction',
      component: 'SensitiveAction',
      metadata: { label: props.label, environment },
    });
    emit('confirm');
    open.value = false;
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <Button variant="destructive" @click="open = true">{{ label }}</Button>
  <Dialog
    :open="open"
    :title="label"
    :description="
      isProduction && requireProductionConfirm
        ? `${description} You are in production.`
        : description
    "
    :confirm-label="confirmLabel"
    :cancel-label="cancelLabel"
    :loading="busy"
    variant="destructive"
    @close="open = false"
    @confirm="handleConfirm"
  />
</template>
