// packages/enterprise-svelte/src/SessionGuard.svelte
<script lang="ts">
  import { onDestroy, onMount, type Snippet } from 'svelte';
  import { isSafeRedirectPath } from '@larose-ui/core';
  import { Dialog } from '@larose-ui/svelte';

  interface Props {
    loginUrl?: string;
    onSessionExpired?: (returnUrl: string) => void;
    children?: Snippet;
  }

  let { loginUrl = '/login', onSessionExpired, children }: Props = $props();
  let expired = $state(false);

  function handler(event: Event) {
    const detail = (event as CustomEvent<{ code?: number }>).detail;
    if (detail?.code === 401) expired = true;
  }

  onMount(() => {
    window.addEventListener('larose:session-expired', handler);
  });
  onDestroy(() => {
    window.removeEventListener('larose:session-expired', handler);
  });

  const safeLoginUrl = isSafeRedirectPath(loginUrl) ? loginUrl : '/login';

  function handleRedirect() {
    const returnUrl = window.location.pathname + window.location.search;
    onSessionExpired?.(returnUrl);
    window.location.href = `${safeLoginUrl}?returnUrl=${encodeURIComponent(returnUrl)}`;
  }
</script>

{@render children?.()}
<Dialog
  open={expired}
  title="Session expired"
  description="Your session has expired. Sign in again to continue."
  confirmLabel="Sign in"
  cancelLabel="Dismiss"
  onclose={() => (expired = false)}
  onconfirm={handleRedirect}
/>

// packages/enterprise-vue/src/SessionGuard.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { isSafeRedirectPath } from '@larose-ui/core';
import { Dialog } from '@larose-ui/vue';

const props = withDefaults(
  defineProps<{
    loginUrl?: string;
  }>(),
  { loginUrl: '/login' },
);

const emit = defineEmits<{ sessionExpired: [returnUrl: string] }>();

const expired = ref(false);

function handler(event: Event) {
  const detail = (event as CustomEvent<{ code?: number }>).detail;
  if (detail?.code === 401) expired.value = true;
}

onMounted(() => {
  window.addEventListener('larose:session-expired', handler);
});
onUnmounted(() => {
  window.removeEventListener('larose:session-expired', handler);
});

const safeLoginUrl = isSafeRedirectPath(props.loginUrl) ? props.loginUrl : '/login';

function handleRedirect() {
  const returnUrl = window.location.pathname + window.location.search;
  emit('sessionExpired', returnUrl);
  window.location.href = `${safeLoginUrl}?returnUrl=${encodeURIComponent(returnUrl)}`;
}
</script>

<template>
  <slot />
  <Dialog
    :open="expired"
    title="Session expired"
    description="Your session has expired. Sign in again to continue."
    confirm-label="Sign in"
    cancel-label="Dismiss"
    @close="expired = false"
    @confirm="handleRedirect"
  />
</template>
