// packages/svelte/src/lib/components/Toolbar/ToolbarMoreButton.svelte
<script lang="ts">
  import Menu from '../Menu/Menu.svelte';
  import OverflowIcon from './OverflowIcon.svelte';
  import { prepareMenuEntries } from '../../Menu/utils';
  import type { MenuEntry, MenuItemConfig } from '../../Menu/types';
  import styles from '@larose-ui/styles/components/Toolbar/Toolbar.module.css';

  let {
    entries,
    'aria-label': ariaLabel = 'More',
    onAction,
    disabled,
  }: { entries: MenuEntry[]; 'aria-label'?: string; onAction?: (entryId: string) => void; disabled?: boolean } =
    $props();

  const prepared = $derived(prepareMenuEntries(entries));
</script>

<div class={styles.moreWrap}>
  <Menu entries={prepared} layout="large" dimBackground={false} onEntrySelect={(entry: MenuItemConfig) => onAction?.(entry.id)}>
    {#snippet children()}
      <button type="button" aria-label={ariaLabel} {disabled}><OverflowIcon /></button>
    {/snippet}
  </Menu>
</div>

// packages/vue/src/components/Toolbar/ToolbarMoreButton.vue
<script setup lang="ts">
import { computed } from 'vue';
import styles from '@larose-ui/styles/components/Toolbar/Toolbar.module.css';
import type { MenuEntry } from '../../Menu/types';
import { prepareMenuEntries } from '../../Menu/utils';
import Menu from '../Menu/Menu.vue';
import { OverflowIcon } from './icons';
const props = defineProps<{ entries: MenuEntry[]; 'aria-label'?: string; disabled?: boolean }>();
const emit = defineEmits<{ action: [string] }>();
const prepared = computed(() => prepareMenuEntries(props.entries));
</script>
<template>
  <div :class="styles.moreWrap">
    <Menu :entries="prepared" layout="large" :dim-background="false" @entry-select="(e) => emit('action', e.id)">
      <button type="button" :aria-label="props['aria-label'] ?? 'More'" :disabled="disabled"><OverflowIcon /></button>
    </Menu>
  </div>
</template>
