// packages/svelte/src/lib/components/WebView/WebViewNavigation.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/WebView/WebView.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    canGoBack?: boolean;
    canGoForward?: boolean;
    title?: string;
    class?: string;
    style?: string;
    onBack?: () => void;
    onForward?: () => void;
    onReload?: () => void;
    children?: Snippet;
  }

  let {
    canGoBack,
    canGoForward,
    title,
    class: className,
    style,
    onBack,
    onForward,
    onReload,
    children,
  }: Props = $props();
</script>

<div class={cn(styles.toolbar, className)} {style} role="toolbar" aria-label="Web navigation">
  <button type="button" class={styles.navButton} disabled={!canGoBack} aria-label="Back" onclick={onBack}>‹</button>
  <button type="button" class={styles.navButton} disabled={!canGoForward} aria-label="Forward" onclick={onForward}>›</button>
  <button type="button" class={styles.navButton} aria-label="Reload" onclick={onReload}>↻</button>
  {#if title}<span class={styles.toolbarTitle}>{title}</span>{/if}
  {#if children}{@render children()}{/if}
</div>

// packages/react/src/WebView/WebViewNavigation.tsx
import styles from '@larose-ui/styles/components/WebView/WebView.module.css';

export interface WebViewNavigationProps {
  canGoBack?: boolean;
  canGoForward?: boolean;
  onBack?: () => void;
  onForward?: () => void;
  title?: string;
  backLabel?: string;
  forwardLabel?: string;
}

function ChevronLeft() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
      <path d="M9 2L4 7l5 5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
    </svg>
  );
}

function ChevronRight() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
      <path d="M5 2l5 5-5 5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
    </svg>
  );
}

export function WebViewNavigation({
  canGoBack = false,
  canGoForward = false,
  onBack,
  onForward,
  title,
  backLabel = 'Back',
  forwardLabel = 'Forward',
}: WebViewNavigationProps) {
  return (
    <div className={styles.toolbar} role="toolbar" aria-label="Web view navigation">
      <button
        type="button"
        className={styles.navButton}
        aria-label={backLabel}
        disabled={!canGoBack}
        onClick={onBack}
      >
        <ChevronLeft />
      </button>
      <button
        type="button"
        className={styles.navButton}
        aria-label={forwardLabel}
        disabled={!canGoForward}
        onClick={onForward}
      >
        <ChevronRight />
      </button>
      {title && <span className={styles.toolbarTitle}>{title}</span>}
    </div>
  );
}
