// packages/svelte/src/lib/components/Button/ButtonGroup.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Button/Button.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    children: Snippet;
    orientation?: 'horizontal' | 'vertical';
    fullWidth?: boolean;
    class?: string;
    style?: string;
    'aria-label'?: string;
  }

  let {
    children,
    orientation = 'horizontal',
    fullWidth = false,
    class: className,
    style,
    'aria-label': ariaLabel,
  }: Props = $props();
</script>

<div
  class={cn(styles.group, className)}
  {style}
  data-orientation={orientation}
  data-full-width={fullWidth ? 'true' : undefined}
  role="group"
  aria-label={ariaLabel}
>
  {@render children()}
</div>

// packages/react/src/Button/ButtonGroup.tsx
import type { ReactNode } from 'react';
import styles from '@larose-ui/styles/components/Button/Button.module.css';

export interface ButtonGroupProps {
  children: ReactNode;
  /** Horizontal row (default) or vertical stack for visionOS guidance. */
  orientation?: 'horizontal' | 'vertical';
  /** Full-width buttons for watchOS-style primary actions. */
  fullWidth?: boolean;
  className?: string;
  'aria-label'?: string;
}

/**
 * Same-size button set — use style, not size, to distinguish the preferred option.
 */
export function ButtonGroup({
  children,
  orientation = 'horizontal',
  fullWidth = false,
  className,
  'aria-label': ariaLabel,
}: ButtonGroupProps) {
  return (
    <div
      className={[styles.group, className].filter(Boolean).join(' ')}
      data-orientation={orientation}
      data-full-width={fullWidth ? 'true' : undefined}
      role="group"
      aria-label={ariaLabel}
    >
      {children}
    </div>
  );
}
