// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue';
import type { ButtonHTMLAttributes } from 'vue';
import type { ButtonRole, Size, UIState, Variant } from '@larose-ui/core';
import { resolveUIState } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/Button/Button.module.css';
import { useComponentDefaults } from '../../composables/useComponentDefaults';
import { cn } from '../../utils/cn';
import { hasDefaultSlotText } from '../../utils/slots';
import type { ButtonShape } from '../../button/types';
import { resolveButtonShape } from '../../button/utils';
import Spinner from '../Spinner/Spinner.vue';

const props = withDefaults(
  defineProps<{
    variant?: Variant;
    size?: Size;
    buttonRole?: ButtonRole;
    shape?: ButtonShape;
    state?: UIState;
    loading?: boolean;
    loadingLabel?: string;
    error?: string | null;
    disabled?: boolean;
    opensAnotherView?: boolean;
    flexible?: boolean;
    iconOnly?: boolean;
    fullWidth?: boolean;
    tooltip?: string;
    class?: string;
    style?: ButtonHTMLAttributes['style'];
    type?: 'button' | 'submit' | 'reset';
  }>(),
  {
    variant: 'primary',
    size: 'md',
    buttonRole: 'normal',
    loading: false,
    error: null,
    disabled: false,
    opensAnotherView: false,
    flexible: false,
    iconOnly: false,
    fullWidth: false,
    type: 'button',
  },
);

const merged = useComponentDefaults('Button', props);
const slots = useSlots();

const uiState = computed(() =>
  resolveUIState({
    state: merged.state,
    loading: merged.loading,
    error: merged.error,
    disabled: merged.disabled,
  }),
);

const isDisabled = computed(
  () =>
    merged.disabled ||
    uiState.value === 'loading' ||
    uiState.value === 'disabled',
);

const isLoading = computed(() => uiState.value === 'loading');
const hasText = computed(() => hasDefaultSlotText(slots));
const hasIcon = computed(() => Boolean(slots.leftIcon || slots.rightIcon));

const resolvedShape = computed(() =>
  resolveButtonShape({
    shape: merged.shape,
    iconOnly: merged.iconOnly,
    hasText: hasText.value && !isLoading.value,
    hasIcon: hasIcon.value,
  }),
);

const resolvedVariant = computed(() =>
  merged.buttonRole === 'primary' && merged.variant !== 'destructive'
    ? 'primary'
    : merged.variant,
);
</script>

<template>
  <button
    :type="merged.type"
    :class="cn(styles.button, merged.class)"
    :style="merged.style"
    :data-variant="resolvedVariant"
    :data-size="merged.size"
    :data-shape="resolvedShape"
    :data-role="merged.buttonRole !== 'normal' ? merged.buttonRole : undefined"
    :data-state="uiState"
    :data-flexible="merged.flexible ? 'true' : undefined"
    :data-full-width="merged.fullWidth ? 'true' : undefined"
    :disabled="isDisabled"
    :aria-busy="isLoading"
    :aria-disabled="isDisabled"
    :title="merged.tooltip && !isDisabled ? merged.tooltip : undefined"
  >
    <span v-if="isLoading" :class="styles.spinner" aria-hidden="true">
      <Spinner size="sm" />
    </span>
    <span v-if="!isLoading && $slots.leftIcon" :class="styles.icon">
      <slot name="leftIcon" />
    </span>
    <span v-if="hasText || isLoading" :class="styles.content">
      <slot v-if="!isLoading || !merged.loadingLabel" />
      <template v-else>{{ merged.loadingLabel }}</template>
    </span>
    <span v-if="!isLoading && $slots.rightIcon" :class="styles.icon">
      <slot name="rightIcon" />
    </span>
    <span v-if="uiState === 'error' && merged.error" :class="styles.errorMessage" role="alert">
      {{ merged.error }}
    </span>
  </button>
</template>

// packages/react/src/Button/Button.tsx
import { forwardRef, type ButtonHTMLAttributes, type ReactNode } from 'react';
import type { ButtonRole, Size, UIState, Variant } from '@larose-ui/core';
import { resolveUIState } from '@larose-ui/core';
import { useComponentDefaults } from '../theme/useComponentDefaults';
import { Spinner } from '../Spinner/Spinner';
import { Tooltip } from '../Tooltip/Tooltip';
import type { ButtonShape } from './types';
import { formatButtonLabel, hasTextContent, resolveButtonShape } from './utils';
import styles from '@larose-ui/styles/components/Button/Button.module.css';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant;
  size?: Size;
  /** Apple HIG semantic role — affects appearance in alerts and sheets. */
  buttonRole?: ButtonRole;
  /** Capsule (default), circle (icon-only), or roundedRect (vertical stacks). */
  shape?: ButtonShape;
  state?: UIState;
  loading?: boolean;
  /** Alternative label shown while loading (Apple HIG activity indicator pattern). */
  loadingLabel?: string;
  error?: string | null;
  leftIcon?: ReactNode;
  rightIcon?: ReactNode;
  /** macOS: append trailing ellipsis when the button opens another view. */
  opensAnotherView?: boolean;
  /** macOS flexible-height push button for multi-line content. */
  flexible?: boolean;
  iconOnly?: boolean;
  /** watchOS-style full-width primary actions. */
  fullWidth?: boolean;
  /** macOS / visionOS hover tooltip. */
  tooltip?: string;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>((incomingProps, ref) => {
  const {
    variant = 'primary',
    size = 'md',
    buttonRole = 'normal',
    shape,
    state,
    loading = false,
    loadingLabel,
    error = null,
    disabled,
    leftIcon,
    rightIcon,
    opensAnotherView = false,
    flexible = false,
    iconOnly = false,
    fullWidth = false,
    tooltip,
    children,
    className,
    style,
    ...props
  } = useComponentDefaults('Button', incomingProps);
    const uiState = resolveUIState({ state, loading, error, disabled });
    const isDisabled =
      disabled || uiState === 'loading' || uiState === 'disabled';
    const isLoading = uiState === 'loading';
    const hasText = hasTextContent(children);
    const hasIcon = Boolean(leftIcon || rightIcon);
    const resolvedShape = resolveButtonShape({
      shape,
      iconOnly,
      hasText: hasText && !isLoading,
      hasIcon,
    });

    let label: ReactNode = children;
    if (isLoading && loadingLabel) {
      label = loadingLabel;
    } else if (typeof children === 'string') {
      label = formatButtonLabel(children, opensAnotherView);
    }

    const resolvedVariant =
      buttonRole === 'primary' && variant !== 'destructive' ? 'primary' : variant;

    const button = (
      <button
        ref={ref}
        type="button"
        className={[styles.button, className].filter(Boolean).join(' ')}
        style={style}
        data-variant={resolvedVariant}
        data-size={size}
        data-shape={resolvedShape}
        data-role={buttonRole !== 'normal' ? buttonRole : undefined}
        data-state={uiState}
        data-flexible={flexible ? 'true' : undefined}
        data-full-width={fullWidth ? 'true' : undefined}
        disabled={isDisabled}
        aria-busy={isLoading}
        aria-disabled={isDisabled}
        {...props}
      >
        {isLoading && (
          <span className={styles.spinner} aria-hidden="true">
            <Spinner size="sm" />
          </span>
        )}
        {!isLoading && leftIcon && (
          <span className={styles.icon}>{leftIcon}</span>
        )}
        {(hasText || isLoading) && (
          <span className={styles.content}>{label}</span>
        )}
        {!isLoading && rightIcon && (
          <span className={styles.icon}>{rightIcon}</span>
        )}
        {uiState === 'error' && error && (
          <span className={styles.errorMessage} role="alert">
            {error}
          </span>
        )}
      </button>
    );

    if (tooltip && !isDisabled) {
      return <Tooltip content={tooltip}>{button}</Tooltip>;
    }

    return button;
});

Button.displayName = 'Button';
