// packages/react/src/Select/Select.tsx
import { forwardRef, type SelectHTMLAttributes } from 'react';
import type { Size, UIState } from '@larose-ui/core';
import { resolveUIState } from '@larose-ui/core';
import { FieldShell } from '../DataEntry/FieldShell';
import { Spinner } from '../Spinner/Spinner';
import { fieldIdFromLabel } from '../DataEntry/utils';
import styles from '@larose-ui/styles/components/Select/Select.module.css';

export interface SelectOption {
  label: string;
  value: string;
}

export interface SelectProps extends SelectHTMLAttributes<HTMLSelectElement> {
  label?: string;
  hint?: string;
  options: SelectOption[];
  placeholder?: string;
  state?: UIState;
  loading?: boolean;
  error?: string | null;
  inputSize?: Size;
  required?: boolean;
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(
  (
    {
      label,
      hint,
      options,
      placeholder = 'Select...',
      state,
      loading = false,
      error = null,
      disabled,
      required = false,
      inputSize = 'md',
      className,
      id,
      ...props
    },
    ref,
  ) => {
    const inputId = id ?? (label ? fieldIdFromLabel(label) : undefined);
    const uiState = resolveUIState({ state, loading, error, disabled });
    const errorMessage = typeof error === 'string' ? error : null;

    return (
      <FieldShell
        label={label}
        hint={hint}
        error={errorMessage}
        required={required}
        htmlFor={inputId}
        uiState={uiState}
      >
        <div className={styles.inputContainer}>
          <select
            ref={ref}
            id={inputId}
            className={[styles.select, className].filter(Boolean).join(' ')}
            data-size={inputSize}
            data-state={uiState}
            disabled={disabled || uiState === 'disabled' || uiState === 'loading'}
            required={required}
            aria-invalid={uiState === 'error'}
            aria-busy={uiState === 'loading'}
            aria-describedby={
              errorMessage ? `${inputId}-error` : hint ? `${inputId}-hint` : undefined
            }
            {...props}
          >
            <option value="">{placeholder}</option>
            {options.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          {uiState === 'loading' && (
            <span className={styles.loadingIndicator} aria-hidden="true">
              <Spinner size="sm" />
            </span>
          )}
        </div>
      </FieldShell>
    );
  },
);

Select.displayName = 'Select';

// packages/svelte/src/lib/components/Select/Select.svelte
<script lang="ts">
  import type { Size, UIState } from '@larose-ui/core';
  import { resolveUIState } from '@larose-ui/core';
  import styles from '@larose-ui/styles/components/Select/Select.module.css';
  import FieldShell from '../FieldShell/FieldShell.svelte';
  import Spinner from '../Spinner/Spinner.svelte';
  import { cn } from '../../utils/cn';
  import { fieldIdFromLabel } from '../../data-entry/utils';

  export interface SelectOption {
    label: string;
    value: string;
  }

  interface Props {
    label?: string;
    hint?: string;
    options: SelectOption[];
    placeholder?: string;
    state?: UIState;
    loading?: boolean;
    error?: string | null;
    disabled?: boolean;
    required?: boolean;
    inputSize?: Size;
    id?: string;
    class?: string;
    style?: string;
    value?: string;
  }

  let {
    label,
    hint,
    options,
    placeholder = 'Select...',
    state,
    loading = false,
    error = null,
    disabled,
    required = false,
    inputSize = 'md',
    id,
    class: className,
    style,
    value = $bindable(''),
  }: Props = $props();

  const inputId = $derived(id ?? (label ? fieldIdFromLabel(label) : undefined));
  const uiState = $derived(resolveUIState({ state, loading, error, disabled }));
  const errorMessage = $derived(typeof error === 'string' ? error : null);
</script>

<FieldShell
  {label}
  {hint}
  error={errorMessage}
  {required}
  htmlFor={inputId}
  {uiState}
  class={className}
  {style}
>
  <div class={styles.inputContainer}>
    <select
      id={inputId}
      class={cn(styles.select, className)}
      data-size={inputSize}
      data-state={uiState}
      bind:value
      disabled={disabled || uiState === 'disabled'}
      {required}
      aria-invalid={uiState === 'error'}
      aria-busy={uiState === 'loading'}
    >
      <option value="" disabled>{placeholder}</option>
      {#each options as option (option.value)}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
    {#if uiState === 'loading'}
      <span class={styles.loadingIndicator} aria-hidden="true">
        <Spinner size="sm" />
      </span>
    {/if}
  </div>
</FieldShell>
