// packages/react/src/Progress/Progress.tsx
import type { UIState } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/Progress/Progress.module.css';

export type ProgressVariant = 'default' | 'success' | 'error';

export interface ProgressProps {
  value: number;
  max?: number;
  label?: string;
  variant?: ProgressVariant;
  state?: UIState;
  showValue?: boolean;
}

export function Progress({
  value,
  max = 100,
  label,
  variant = 'default',
  state = 'idle',
  showValue = false,
}: ProgressProps) {
  const clamped = Math.min(max, Math.max(0, value));
  const percent = max > 0 ? Math.round((clamped / max) * 100) : 0;

  return (
    <div className={styles.wrapper} data-state={state}>
      {(label || showValue) && (
        <div className={styles.header}>
          {label && <span className={styles.label}>{label}</span>}
          {showValue && <span className={styles.value}>{percent}%</span>}
        </div>
      )}
      <div
        className={styles.track}
        role="progressbar"
        aria-valuemin={0}
        aria-valuemax={max}
        aria-valuenow={clamped}
        aria-label={label}
        data-variant={variant}
        data-state={state}
      >
        <div className={styles.bar} style={{ width: `${percent}%` }} />
      </div>
    </div>
  );
}

// packages/svelte/src/lib/components/Progress/Progress.svelte
<script lang="ts">
  import type { UIState } from '@larose-ui/core';
  import styles from '@larose-ui/styles/components/Progress/Progress.module.css';

  export type ProgressVariant = 'default' | 'success' | 'error';

  interface Props {
    value: number;
    max?: number;
    label?: string;
    variant?: ProgressVariant;
    state?: UIState;
    showValue?: boolean;
  }

  let {
    value,
    max = 100,
    label,
    variant = 'default',
    state = 'idle',
    showValue = false,
  }: Props = $props();

  const clamped = $derived(Math.min(max, Math.max(0, value)));
  const percent = $derived(max > 0 ? Math.round((clamped / max) * 100) : 0);
</script>

<div class={styles.wrapper} data-state={state}>
  {#if label || showValue}
    <div class={styles.header}>
      {#if label}<span class={styles.label}>{label}</span>{/if}
      {#if showValue}<span class={styles.value}>{percent}%</span>{/if}
    </div>
  {/if}
  <div
    class={styles.track}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={max}
    aria-valuenow={clamped}
    aria-label={label}
    data-variant={variant}
    data-state={state}
  >
    <div class={styles.bar} style={`width: ${percent}%`}></div>
  </div>
</div>
