// packages/svelte/src/lib/components/Button/ButtonGroup.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Button/Button.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    children: Snippet;
    orientation?: 'horizontal' | 'vertical';
    fullWidth?: boolean;
    class?: string;
    style?: string;
    'aria-label'?: string;
  }

  let {
    children,
    orientation = 'horizontal',
    fullWidth = false,
    class: className,
    style,
    'aria-label': ariaLabel,
  }: Props = $props();
</script>

<div
  class={cn(styles.group, className)}
  {style}
  data-orientation={orientation}
  data-full-width={fullWidth ? 'true' : undefined}
  role="group"
  aria-label={ariaLabel}
>
  {@render children()}
</div>

// packages/vue/src/components/Button/ButtonGroup.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Button/Button.module.css';
import { cn } from '../../utils/cn';

withDefaults(
  defineProps<{
    orientation?: 'horizontal' | 'vertical';
    fullWidth?: boolean;
    class?: string;
    style?: CSSProperties;
    ariaLabel?: string;
  }>(),
  {
    orientation: 'horizontal',
    fullWidth: false,
  },
);
</script>

<template>
  <div
    :class="cn(styles.group, $props.class)"
    :style="style"
    :data-orientation="orientation"
    :data-full-width="fullWidth ? 'true' : undefined"
    role="group"
    :aria-label="ariaLabel"
  >
    <slot />
  </div>
</template>
