// packages/react/src/Button/HelpButton.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { Tooltip } from '../Tooltip/Tooltip';
import styles from '@larose-ui/styles/components/Button/Button.module.css';

export interface HelpButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Brief phrase explaining what help covers (macOS / visionOS tooltip). */
  helpTopic?: string;
}

/**
 * Circular help button — one per window, lower corner of dialogs/settings.
 * @see https://developer.apple.com/design/human-interface-guidelines/buttons
 */
export const HelpButton = forwardRef<HTMLButtonElement, HelpButtonProps>(
  ({ helpTopic, className, 'aria-label': ariaLabel = 'Help', ...props }, ref) => {
    const button = (
      <button
        ref={ref}
        type="button"
        className={[styles.helpButton, className].filter(Boolean).join(' ')}
        aria-label={ariaLabel}
        {...props}
      >
        ?
      </button>
    );

    if (helpTopic) {
      return <Tooltip content={helpTopic}>{button}</Tooltip>;
    }

    return button;
  },
);

HelpButton.displayName = 'HelpButton';

// packages/vue/src/components/Button/HelpButton.vue
<script setup lang="ts">
import type { ButtonHTMLAttributes } from 'vue';
import styles from '@larose-ui/styles/components/Button/Button.module.css';
import { cn } from '../../utils/cn';
import Tooltip from '../Tooltip/Tooltip.vue';

withDefaults(
  defineProps<{
    helpTopic?: string;
    class?: string;
    style?: ButtonHTMLAttributes['style'];
    disabled?: boolean;
    ariaLabel?: string;
  }>(),
  {
    ariaLabel: 'Help',
  },
);
</script>

<template>
  <Tooltip v-if="helpTopic" :content="helpTopic">
    <button
      type="button"
      :class="cn(styles.helpButton, $props.class)"
      :style="style"
      :aria-label="ariaLabel"
      :disabled="disabled"
    >
      ?
    </button>
  </Tooltip>
  <button
    v-else
    type="button"
    :class="cn(styles.helpButton, $props.class)"
    :style="style"
    :aria-label="ariaLabel"
    :disabled="disabled"
  >
    ?
  </button>
</template>
