// packages/react/src/FileManagement/UnsavedIndicator.tsx
import { documentTitleWithEditedSuffix } from './utils';
import type { CSSProperties } from 'react';
import styles from '@larose-ui/styles/components/FileManagement/FileManagement.module.css';

export interface UnsavedIndicatorProps {
  title: string;
  edited?: boolean;
  /** When false, show the unsaved dot (manual save mode). */
  autosaveEnabled?: boolean;
  className?: string;
  style?: CSSProperties;
}

/**
 * Shows unsaved-change feedback per Apple HIG autosave guidance.
 * @see https://developer.apple.com/design/human-interface-guidelines/file-management
 */
export function UnsavedIndicator({
  title,
  edited = false,
  autosaveEnabled = true,
  className,
  style,
}: UnsavedIndicatorProps) {
  const showDot = edited && !autosaveEnabled;
  const displayTitle = documentTitleWithEditedSuffix(title, edited, autosaveEnabled);

  return (
    <span className={[styles.unsaved, className].filter(Boolean).join(' ')} style={style}>
      <span
        className={styles.unsavedDot}
        data-hidden={showDot ? 'false' : 'true'}
        aria-hidden={!showDot}
        title="Unsaved changes"
      />
      <span>{displayTitle}</span>
    </span>
  );
}

// packages/svelte/src/lib/components/FileManagement/UnsavedIndicator.svelte
<script lang="ts">
  import { documentTitleWithEditedSuffix } from '../../FileManagement/utils';
  import styles from '@larose-ui/styles/components/FileManagement/FileManagement.module.css';

  let {
    title,
    edited = false,
    autosaveEnabled = true,
    class: className,
    style,
  }: { title: string; edited?: boolean; autosaveEnabled?: boolean; class?: string; style?: string } = $props();

  const showDot = $derived(edited && !autosaveEnabled);
  const displayTitle = $derived(documentTitleWithEditedSuffix(title, edited, autosaveEnabled));
</script>

<span class={[styles.unsaved, className].filter(Boolean).join(' ')} {style}>
  <span class={styles.unsavedDot} data-hidden={showDot ? 'false' : 'true'} aria-hidden={!showDot} title="Unsaved changes"></span>
  <span>{displayTitle}</span>
</span>
