// packages/vue/src/components/Popover/Popover.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, useId, watch } from 'vue';
import type { CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Popover/Popover.module.css';
import { cn } from '../../utils/cn';

export type PopoverSide = 'top' | 'bottom' | 'left' | 'right';

const props = withDefaults(
  defineProps<{
    open?: boolean;
    defaultOpen?: boolean;
    side?: PopoverSide;
    panelClass?: string;
    class?: string;
    style?: CSSProperties;
    ariaLabel?: string;
  }>(),
  {
    defaultOpen: false,
    side: 'bottom',
    ariaLabel: 'Popover',
  },
);

const emit = defineEmits<{
  openChange: [open: boolean];
}>();

const internalOpen = ref(props.defaultOpen);
const isControlled = computed(() => props.open !== undefined);
const isOpen = computed(() => (isControlled.value ? Boolean(props.open) : internalOpen.value));
const popoverId = useId();
const rootRef = ref<HTMLElement | null>(null);

function setOpen(next: boolean) {
  if (!isControlled.value) internalOpen.value = next;
  emit('openChange', next);
}

function onPointerDown(event: MouseEvent) {
  if (!rootRef.value?.contains(event.target as Node)) {
    setOpen(false);
  }
}

function onKeyDown(event: KeyboardEvent) {
  if (event.key === 'Escape') setOpen(false);
}

watch(
  isOpen,
  (open) => {
    if (!open) {
      document.removeEventListener('mousedown', onPointerDown);
      document.removeEventListener('keydown', onKeyDown);
      return;
    }
    document.addEventListener('mousedown', onPointerDown);
    document.addEventListener('keydown', onKeyDown);
  },
  { immediate: true },
);

onUnmounted(() => {
  document.removeEventListener('mousedown', onPointerDown);
  document.removeEventListener('keydown', onKeyDown);
});
</script>

<template>
  <span ref="rootRef" :class="cn(styles.wrapper, $props.class)" :style="style">
    <span
      :aria-expanded="isOpen"
      :aria-controls="isOpen ? popoverId : undefined"
      @click="setOpen(!isOpen)"
    >
      <slot name="trigger" />
    </span>
    <div
      v-if="isOpen"
      :id="popoverId"
      role="dialog"
      :aria-label="ariaLabel"
      :class="cn(styles.popover, panelClass)"
      :data-side="side"
    >
      <slot name="content" />
    </div>
  </span>
</template>

// packages/react/src/Popover/Popover.tsx
import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import styles from './Popover.module.css';

export type PopoverSide = 'top' | 'bottom' | 'left' | 'right';

export interface PopoverProps {
  trigger: ReactNode;
  content: ReactNode;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  side?: PopoverSide;
  'aria-label'?: string;
}

export function Popover({
  trigger,
  content,
  open,
  defaultOpen = false,
  onOpenChange,
  side = 'bottom',
  'aria-label': ariaLabel = 'Popover',
}: PopoverProps) {
  const [internalOpen, setInternalOpen] = useState(defaultOpen);
  const isControlled = open !== undefined;
  const isOpen = isControlled ? open : internalOpen;
  const popoverId = useId();
  const rootRef = useRef<HTMLSpanElement>(null);

  const setOpen = useCallback(
    (next: boolean) => {
      if (!isControlled) setInternalOpen(next);
      onOpenChange?.(next);
    },
    [isControlled, onOpenChange],
  );

  useEffect(() => {
    if (!isOpen) return;

    const onPointerDown = (event: MouseEvent) => {
      if (!rootRef.current?.contains(event.target as Node)) {
        setOpen(false);
      }
    };

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setOpen(false);
    };

    document.addEventListener('mousedown', onPointerDown);
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('mousedown', onPointerDown);
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [isOpen, setOpen]);

  return (
    <span ref={rootRef} className={styles.wrapper}>
      <span
        onClick={() => setOpen(!isOpen)}
        aria-expanded={isOpen}
        aria-controls={isOpen ? popoverId : undefined}
      >
        {trigger}
      </span>
      {isOpen && (
        <div
          id={popoverId}
          role="dialog"
          aria-label={ariaLabel}
          className={styles.popover}
          data-side={side}
        >
          {content}
        </div>
      )}
    </span>
  );
}
