// packages/vue/src/components/FileUpload/FileUpload.vue
<script setup lang="ts">
import { ref, useId, type CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/FileUpload/FileUpload.module.css';
import { cn } from '../../utils/cn';

const props = withDefaults(
  defineProps<{
    label?: string;
    hint?: string;
    error?: string | null;
    accept?: string;
    multiple?: boolean;
    disabled?: boolean;
    buttonLabel?: string;
    class?: string;
    style?: CSSProperties;
  }>(),
  { error: null, multiple: false, disabled: false, buttonLabel: 'Choose files or drag here' },
);

const emit = defineEmits<{ filesChange: [files: File[]] }>();
const inputId = useId();
const files = ref<File[]>([]);
const dragOver = ref(false);
const errorMessage = () => (typeof props.error === 'string' ? props.error : null);
const uiState = () =>
  props.disabled ? 'disabled' : errorMessage() ? 'error' : dragOver.value ? 'dragover' : 'default';

function update(next: File[]) {
  files.value = next;
  emit('filesChange', next);
}

function handleFiles(list: FileList | null) {
  if (!list || props.disabled) return;
  update(Array.from(list));
}
</script>

<template>
  <div :class="cn(styles.wrapper, props.class)" :style="props.style">
    <label v-if="label" :for="inputId" :class="styles.label">{{ label }}</label>
    <label
      :for="inputId"
      :class="styles.dropzone"
      :data-state="uiState()"
      @dragover.prevent="dragOver = true"
      @dragleave.prevent="dragOver = false"
      @drop.prevent="
        dragOver = false;
        handleFiles(($event as DragEvent).dataTransfer?.files ?? null);
      "
    >
      <span>{{ buttonLabel }}</span>
      <input
        :id="inputId"
        type="file"
        :class="styles.input"
        :accept="accept"
        :multiple="multiple"
        :disabled="disabled"
        @change="handleFiles(($event.target as HTMLInputElement).files)"
      />
    </label>
    <ul v-if="files.length" :class="styles.fileList">
      <li v-for="file in files" :key="file.name + file.size" :class="styles.fileItem">{{ file.name }}</li>
    </ul>
    <span v-if="hint && !errorMessage()" :class="styles.hint">{{ hint }}</span>
    <span v-if="errorMessage()" :class="styles.error" role="alert">{{ errorMessage() }}</span>
  </div>
</template>

// packages/svelte/src/lib/components/FileUpload/FileUpload.svelte
<script lang="ts">
  import styles from '@larose-ui/styles/components/FileUpload/FileUpload.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    label?: string;
    hint?: string;
    error?: string | null;
    accept?: string;
    multiple?: boolean;
    disabled?: boolean;
    buttonLabel?: string;
    class?: string;
    style?: string;
    onFilesChange?: (files: File[]) => void;
  }

  let {
    label,
    hint,
    error = null,
    accept,
    multiple = false,
    disabled = false,
    buttonLabel = 'Choose files or drag here',
    class: className,
    style,
    onFilesChange,
  }: Props = $props();

  let files = $state<File[]>([]);
  let dragOver = $state(false);
  const inputId = `file-upload-${Math.random().toString(36).slice(2)}`;
  const errorMessage = $derived(typeof error === 'string' ? error : null);
  const uiState = $derived(
    disabled ? 'disabled' : errorMessage ? 'error' : dragOver ? 'dragover' : 'default',
  );

  function handleFiles(list: FileList | null) {
    if (!list || disabled) return;
    files = Array.from(list);
    onFilesChange?.(files);
  }
</script>

<div class={cn(styles.wrapper, className)} {style}>
  {#if label}<label for={inputId} class={styles.label}>{label}</label>{/if}
  <label
    for={inputId}
    class={styles.dropzone}
    data-state={uiState}
    ondragover={(e) => {
      e.preventDefault();
      dragOver = true;
    }}
    ondragleave={(e) => {
      e.preventDefault();
      dragOver = false;
    }}
    ondrop={(e) => {
      e.preventDefault();
      dragOver = false;
      handleFiles(e.dataTransfer?.files ?? null);
    }}
  >
    <span>{buttonLabel}</span>
    <input
      id={inputId}
      type="file"
      class={styles.input}
      {accept}
      {multiple}
      {disabled}
      onchange={(e) => handleFiles((e.currentTarget as HTMLInputElement).files)}
    />
  </label>
  {#if files.length}
    <ul class={styles.fileList}>
      {#each files as file (file.name + file.size)}
        <li class={styles.fileItem}>{file.name}</li>
      {/each}
    </ul>
  {/if}
  {#if hint && !errorMessage}<span class={styles.hint}>{hint}</span>{/if}
  {#if errorMessage}<span class={styles.error} role="alert">{errorMessage}</span>{/if}
</div>
