// packages/svelte/src/lib/components/Accordion/AccordionContent.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Accordion/Accordion.module.css';
  import { cn } from '../../utils/cn';
  import { getAccordionContext, getAccordionItemContext } from './context';

  interface Props {
    children: Snippet;
    class?: string;
    style?: string;
  }

  let { children, class: className, style }: Props = $props();

  const itemValue = getAccordionItemContext('AccordionContent');
  const accordion = getAccordionContext('AccordionContent');
  const isOpen = $derived(accordion.openItems.includes(itemValue));
  const triggerId = $derived(`${accordion.baseId}-trigger-${itemValue}`);
  const panelId = $derived(`${accordion.baseId}-panel-${itemValue}`);
</script>

{#if isOpen}
  <div
    id={panelId}
    role="region"
    class={cn(styles.content, className)}
    {style}
    aria-labelledby={triggerId}
    data-state="open"
  >
    {@render children()}
  </div>
{/if}

// packages/vue/src/components/Accordion/AccordionContent.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Accordion/Accordion.module.css';
import { cn } from '../../utils/cn';
import { useAccordionContext, useAccordionItemContext } from './context';

const props = defineProps<{ class?: string; style?: CSSProperties }>();
const ctx = useAccordionContext('AccordionContent');
const itemValue = useAccordionItemContext('AccordionContent');
const open = computed(() => ctx.openItems.value.has(itemValue));
const triggerId = computed(() => `${ctx.baseId}-trigger-${itemValue}`);
const contentId = computed(() => `${ctx.baseId}-content-${itemValue}`);
</script>

<template>
  <div
    v-show="open"
    :id="contentId"
    role="region"
    :aria-labelledby="triggerId"
    :class="cn(styles.content, props.class)"
    :style="props.style"
  >
    <slot />
  </div>
</template>
