// packages/svelte/src/lib/components/Ornament/Ornament.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Ornament/Ornament.module.css';
  import { cn } from '../../utils/cn';

  let {
    children,
    class: className,
    style,
  }: {
    children?: Snippet;
    class?: string;
    style?: string;
  } = $props();
</script>

<div class={cn(styles.ornament, className)} {style} role="toolbar">
  <div class={styles.ornamentInner}>
    {#if children}{@render children()}{/if}
  </div>
</div>

// packages/vue/src/components/Ornament/Ornament.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Ornament/Ornament.module.css';
import { cn } from '../../utils/cn';

defineProps<{
  class?: string;
  style?: CSSProperties;
}>();
</script>

<template>
  <div
    :class="cn(styles.ornament, $props.class)"
    :style="$props.style"
    role="toolbar"
  >
    <div :class="styles.ornamentInner">
      <slot />
    </div>
  </div>
</template>
