// packages/svelte/src/lib/components/DragDrop/DragPreview.svelte
<script lang="ts">
  import type { DragSession } from '../../DragDrop/types';
  import { portal } from '../../utils/portal';
  import styles from '@larose-ui/styles/components/DragDrop/DragDrop.module.css';

  let { session, revert }: { session: DragSession | null; revert: boolean } = $props();
  const primary = $derived(session?.items[0]);
  const count = $derived(session?.items.length ?? 0);
</script>

{#if session}
  <div use:portal class={styles.previewLayer} aria-hidden="true">
    <div
      class={styles.preview}
      data-revert={revert ? 'true' : undefined}
      style={`left:${session.x}px;top:${session.y}px;transform:${revert ? 'translate(-50%, -50%) scale(0.85)' : 'translate(-50%, -50%)'}`}
    >
      {primary?.label ?? 'Dragging…'}
      {#if count > 1}<span class={styles.badge}>{count}</span>{/if}
    </div>
  </div>
{/if}

// packages/react/src/DragDrop/DragPreview.tsx
import { createPortal } from 'react-dom';
import type { DragSession } from './types';
import styles from '@larose-ui/styles/components/DragDrop/DragDrop.module.css';
import { getLaRosePortalTarget } from '@larose-ui/core';

export function DragPreviewLayer({
  session,
  revert,
}: {
  session: DragSession | null;
  revert: boolean;
}) {
  if (!session) return null;

  const primary = session.items[0];
  const count = session.items.length;

  return createPortal(<div className={styles.previewLayer} aria-hidden="true">
      <div
        className={styles.preview}
        data-revert={revert ? 'true' : undefined}
        style={{
          left: session.x,
          top: session.y,
          transform: revert
            ? `translate(-50%, -50%) scale(0.85)`
            : 'translate(-50%, -50%)',
        }}
      >
        {primary?.preview ?? primary?.label ?? 'Dragging…'}
        {count > 1 && <span className={styles.badge}>{count}</span>}
      </div>
    </div>,
    getLaRosePortalTarget(),
  );
}
