// packages/react/src/QuickActions/HomeScreenQuickActions.tsx
import {
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import { LONG_PRESS_MS } from '../ContextMenu/utils';
import type { QuickActionIconPlacement, QuickActionItem } from './types';
import {
  estimateQuickActionMenuHeight,
  prepareQuickActions,
  resolveQuickActionMenuPosition,
} from './utils';
import styles from './QuickActions.module.css';

export interface HomeScreenQuickActionsProps {
  appName: string;
  icon: ReactNode;
  actions: QuickActionItem[];
  /** Icon appears on leading or trailing edge depending on Home Screen position. */
  iconPlacement?: QuickActionIconPlacement;
  includeSystemActions?: boolean;
  systemActions?: QuickActionItem[];
  onActionSelect?: (action: QuickActionItem) => void;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
}

function QuickActionRow({
  action,
  iconPlacement,
  onSelect,
}: {
  action: QuickActionItem;
  iconPlacement: QuickActionIconPlacement;
  onSelect: (action: QuickActionItem) => void;
}) {
  return (
    <button
      type="button"
      className={styles.row}
      role="menuitem"
      data-icon-placement={iconPlacement}
      data-destructive={action.destructive ? 'true' : undefined}
      disabled={action.disabled}
      onClick={() => {
        if (action.disabled) return;
        action.onSelect?.();
        onSelect(action);
      }}
    >
      {action.icon && <span className={styles.rowIcon}>{action.icon}</span>}
      <span className={styles.textBlock}>
        <span className={styles.title}>{action.label}</span>
        {action.subtitle && <span className={styles.subtitle}>{action.subtitle}</span>}
      </span>
    </button>
  );
}

/**
 * iOS/iPadOS Home Screen quick actions — touch and hold an app icon for high-value tasks.
 * @see https://developer.apple.com/design/human-interface-guidelines/home-screen-quick-actions
 */
export function HomeScreenQuickActions({
  appName,
  icon,
  actions,
  iconPlacement = 'leading',
  includeSystemActions = true,
  systemActions,
  onActionSelect,
  open,
  onOpenChange,
}: HomeScreenQuickActionsProps) {
  const menuId = useId();
  const iconRef = useRef<HTMLDivElement>(null);
  const longPressTimer = useRef<number | null>(null);
  const [internalOpen, setInternalOpen] = useState(false);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const isControlled = open !== undefined;
  const isOpen = isControlled ? open : internalOpen;

  const preparedActions = useMemo(
    () => prepareQuickActions(actions, { includeSystemActions, systemActions }),
    [actions, includeSystemActions, systemActions],
  );

  const appActions = useMemo(
    () => preparedActions.filter((action) => !action.system),
    [preparedActions],
  );
  const systemGroup = useMemo(
    () => preparedActions.filter((action) => action.system),
    [preparedActions],
  );

  const setOpen = useCallback(
    (next: boolean) => {
      if (!isControlled) setInternalOpen(next);
      onOpenChange?.(next);
    },
    [isControlled, onOpenChange],
  );

  const openAboveIcon = useCallback(() => {
    const rect = iconRef.current?.getBoundingClientRect();
    if (!rect) return;
    const menuWidth = 260;
    const menuHeight = estimateQuickActionMenuHeight(preparedActions.length);
    setPosition(resolveQuickActionMenuPosition(rect, menuWidth, menuHeight));
    setOpen(true);
  }, [preparedActions.length, setOpen]);

  const close = useCallback(() => setOpen(false), [setOpen]);

  const clearLongPress = useCallback(() => {
    if (longPressTimer.current !== null) {
      window.clearTimeout(longPressTimer.current);
      longPressTimer.current = null;
    }
  }, []);

  const handleSelect = useCallback(
    (action: QuickActionItem) => {
      onActionSelect?.(action);
      close();
    },
    [close, onActionSelect],
  );

  useEffect(() => {
    if (!isOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
    };
    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  }, [close, isOpen]);

  return (
    <div className={styles.quickActionsWrap}>
      <div
        ref={iconRef}
        className={styles.appIcon}
        role="button"
        tabIndex={0}
        aria-label={appName}
        aria-haspopup="menu"
        aria-expanded={isOpen}
        aria-controls={isOpen ? menuId : undefined}
        onPointerDown={(event) => {
          if (event.pointerType === 'mouse') return;
          clearLongPress();
          longPressTimer.current = window.setTimeout(openAboveIcon, LONG_PRESS_MS);
        }}
        onPointerUp={clearLongPress}
        onPointerCancel={clearLongPress}
        onPointerLeave={clearLongPress}
        onContextMenu={(event) => {
          event.preventDefault();
          openAboveIcon();
        }}
      >
        {icon}
      </div>
      <span className={styles.hint}>Touch and hold for quick actions</span>
      {isOpen &&
        createPortal(
          <>
            <div className={styles.menuBackdrop} role="presentation" onClick={close} />
            <div
              id={menuId}
              className={styles.menu}
              role="menu"
              aria-label={`${appName} quick actions`}
              style={{ left: position.x, top: position.y }}
              onClick={(event) => event.stopPropagation()}
            >
              <ul className={styles.list}>
                {appActions.map((action) => (
                  <li key={action.id}>
                    <QuickActionRow
                      action={action}
                      iconPlacement={iconPlacement}
                      onSelect={handleSelect}
                    />
                  </li>
                ))}
                {systemGroup.length > 0 && (
                  <li className={styles.systemGroup} role="presentation">
                    <ul className={styles.list}>
                      {systemGroup.map((action) => (
                        <li key={action.id}>
                          <QuickActionRow
                            action={action}
                            iconPlacement={iconPlacement}
                            onSelect={handleSelect}
                          />
                        </li>
                      ))}
                    </ul>
                  </li>
                )}
              </ul>
            </div>
          </>,
          document.body,
        )}
    </div>
  );
}

// packages/svelte/src/lib/components/QuickActions/HomeScreenQuickActions.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { LONG_PRESS_MS } from '../../ContextMenu/utils';
  import type { QuickActionIconPlacement, QuickActionItem } from '../../QuickActions/types';
  import {
    estimateQuickActionMenuHeight,
    prepareQuickActions,
    resolveQuickActionMenuPosition,
  } from '../../QuickActions/utils';
  import styles from '@larose-ui/styles/components/QuickActions/QuickActions.module.css';
  import { cn } from '../../utils/cn';
  import { portal } from '../../utils/portal';

  let {
    appName,
    icon,
    actions,
    iconPlacement = 'leading',
    includeSystemActions = true,
    systemActions,
    onActionSelect,
    open,
    onOpenChange,
    class: className,
    style,
  }: {
    appName: string;
    icon?: Snippet;
    actions: QuickActionItem[];
    iconPlacement?: QuickActionIconPlacement;
    includeSystemActions?: boolean;
    systemActions?: QuickActionItem[];
    onActionSelect?: (action: QuickActionItem) => void;
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    class?: string;
    style?: string;
  } = $props();

  const menuId = $props.id();
  let iconEl = $state<HTMLDivElement | null>(null);
  let longPressTimer = $state<number | null>(null);
  let internalOpen = $state(false);
  let position = $state({ x: 0, y: 0 });

  const isOpen = $derived(open ?? internalOpen);
  const preparedActions = $derived(
    prepareQuickActions(actions, { includeSystemActions, systemActions }),
  );
  const appActions = $derived(preparedActions.filter((action) => !action.system));
  const systemGroup = $derived(preparedActions.filter((action) => action.system));

  function setOpen(next: boolean) {
    if (open === undefined) internalOpen = next;
    onOpenChange?.(next);
  }

  function openAboveIcon() {
    const rect = iconEl?.getBoundingClientRect();
    if (!rect) return;
    const menuWidth = 260;
    const menuHeight = estimateQuickActionMenuHeight(preparedActions.length);
    position = resolveQuickActionMenuPosition(rect, menuWidth, menuHeight);
    setOpen(true);
  }

  function close() {
    setOpen(false);
  }

  function clearLongPress() {
    if (longPressTimer !== null) {
      window.clearTimeout(longPressTimer);
      longPressTimer = null;
    }
  }

  function handleSelect(action: QuickActionItem) {
    if (action.disabled) return;
    action.onSelect?.();
    onActionSelect?.(action);
    close();
  }

  $effect(() => {
    if (!isOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
    };
    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  });
</script>

<div class={cn(styles.quickActionsWrap, className)} {style}>
  <div
    bind:this={iconEl}
    class={styles.appIcon}
    role="button"
    tabindex="0"
    aria-label={appName}
    aria-haspopup="menu"
    aria-expanded={isOpen}
    aria-controls={isOpen ? menuId : undefined}
    onpointerdown={(event) => {
      if (event.pointerType === 'mouse') return;
      clearLongPress();
      longPressTimer = window.setTimeout(openAboveIcon, LONG_PRESS_MS);
    }}
    onpointerup={clearLongPress}
    onpointercancel={clearLongPress}
    onpointerleave={clearLongPress}
    oncontextmenu={(event) => {
      event.preventDefault();
      openAboveIcon();
    }}
  >
    {#if icon}{@render icon()}{/if}
  </div>
  <span class={styles.hint}>Touch and hold for quick actions</span>

  {#if isOpen}
    <div use:portal>
      <div class={styles.menuBackdrop} role="presentation" onclick={close}></div>
      <div
        id={menuId}
        class={styles.menu}
        role="menu"
        aria-label={`${appName} quick actions`}
        style={`position:fixed;left:${position.x}px;top:${position.y}px;z-index:1000;`}
        onclick={(event) => event.stopPropagation()}
      >
        <ul class={styles.list}>
          {#each appActions as action (action.id)}
            <li>
              <button
                type="button"
                class={styles.row}
                role="menuitem"
                data-icon-placement={iconPlacement}
                data-destructive={action.destructive ? 'true' : undefined}
                disabled={action.disabled}
                onclick={() => handleSelect(action)}
              >
                <span class={styles.textBlock}>
                  <span class={styles.title}>{action.label}</span>
                  {#if action.subtitle}
                    <span class={styles.subtitle}>{action.subtitle}</span>
                  {/if}
                </span>
              </button>
            </li>
          {/each}
          {#if systemGroup.length > 0}
            <li class={styles.systemGroup} role="presentation">
              <ul class={styles.list}>
                {#each systemGroup as action (action.id)}
                  <li>
                    <button
                      type="button"
                      class={styles.row}
                      role="menuitem"
                      data-icon-placement={iconPlacement}
                      data-destructive={action.destructive ? 'true' : undefined}
                      disabled={action.disabled}
                      onclick={() => handleSelect(action)}
                    >
                      <span class={styles.textBlock}>
                        <span class={styles.title}>{action.label}</span>
                      </span>
                    </button>
                  </li>
                {/each}
              </ul>
            </li>
          {/if}
        </ul>
      </div>
    </div>
  {/if}
</div>
