// packages/vue/src/components/QuickActions/HomeScreenQuickActions.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, useId, watch } from 'vue';
import { LONG_PRESS_MS } from '../../ContextMenu/utils';
import type { QuickActionIconPlacement, QuickActionItem } from '../../QuickActions/types';
import { estimateQuickActionMenuHeight, prepareQuickActions, resolveQuickActionMenuPosition } from '../../QuickActions/utils';
import styles from '@larose-ui/styles/components/QuickActions/QuickActions.module.css';
import { cn } from '../../utils/cn';

const props = withDefaults(defineProps<{
  appName: string; actions: QuickActionItem[]; iconPlacement?: QuickActionIconPlacement;
  includeSystemActions?: boolean; systemActions?: QuickActionItem[]; open?: boolean;
  class?: string; style?: Record<string, string | number>;
}>(), { iconPlacement: 'leading', includeSystemActions: true });

const emit = defineEmits<{ 'update:open': [boolean]; openChange: [boolean]; actionSelect: [QuickActionItem] }>();
const menuId = useId();
const iconRef = ref<HTMLElement | null>(null);
const longPressTimer = ref<number | null>(null);
const internal = ref(false);
const position = ref({ x: 0, y: 0 });
const isOpen = computed(() => (props.open !== undefined ? props.open : internal.value));
const prepared = computed(() => prepareQuickActions(props.actions, { includeSystemActions: props.includeSystemActions, systemActions: props.systemActions }));
const appActions = computed(() => prepared.value.filter((a) => !a.system));
const systemGroup = computed(() => prepared.value.filter((a) => a.system));

function setOpen(next: boolean) { if (props.open === undefined) internal.value = next; emit('update:open', next); emit('openChange', next); }
function openAbove() {
  const rect = iconRef.value?.getBoundingClientRect();
  if (!rect) return;
  position.value = resolveQuickActionMenuPosition(rect, 260, estimateQuickActionMenuHeight(prepared.value.length));
  setOpen(true);
}
function close() { setOpen(false); }
function clear() { if (longPressTimer.value !== null) { window.clearTimeout(longPressTimer.value); longPressTimer.value = null; } }
function select(action: QuickActionItem) { action.onSelect?.(); emit('actionSelect', action); close(); }
function onPointerDown(e: PointerEvent) {
  if (e.pointerType === 'mouse') return;
  clear();
  longPressTimer.value = window.setTimeout(openAbove, LONG_PRESS_MS);
}
function onKeyDown(event: KeyboardEvent) {
  if (event.key === 'Escape') close();
}
function onPointerDownOutside(event: PointerEvent) {
  const target = event.target as Node | null;
  if (!target) return;
  const surface = document.getElementById(menuId);
  if (surface?.contains(target)) return;
  if (iconRef.value?.contains(target)) return;
  close();
}
watch(isOpen, (open) => {
  if (open) {
    document.addEventListener('keydown', onKeyDown);
    window.setTimeout(() => {
      if (!isOpen.value) return;
      document.addEventListener('pointerdown', onPointerDownOutside, true);
    }, 0);
  } else {
    document.removeEventListener('keydown', onKeyDown);
    document.removeEventListener('pointerdown', onPointerDownOutside, true);
  }
});
onUnmounted(() => {
  document.removeEventListener('keydown', onKeyDown);
  document.removeEventListener('pointerdown', onPointerDownOutside, true);
});
</script>

<template>
  <div :class="cn(styles.quickActionsWrap, props.class)" :style="props.style">
    <div
      ref="iconRef"
      :class="styles.appIcon"
      role="button"
      tabindex="0"
      :aria-label="appName"
      aria-haspopup="menu"
      :aria-expanded="isOpen"
      @pointerdown="onPointerDown"
      @pointerup="clear" @pointercancel="clear" @pointerleave="clear"
      @contextmenu.prevent="openAbove"
    ><slot name="icon" /></div>
    <span :class="styles.hint">Touch and hold for quick actions</span>
    <Teleport to="[data-lr-portal-root], [data-lr-provider], body">
      <div v-if="isOpen">
        <div :class="styles.menuBackdrop" @click="close" />
        <div :id="menuId" :class="styles.menu" role="menu" :aria-label="`${appName} quick actions`" :style="{ left: `${position.x}px`, top: `${position.y}px`, position: 'fixed', zIndex: 1000 }" @click.stop>
          <ul :class="styles.list">
            <li v-for="action in appActions" :key="action.id">
              <button type="button" :class="styles.row" role="menuitem" :data-icon-placement="iconPlacement" :data-destructive="action.destructive ? 'true' : undefined" :disabled="action.disabled" @click="select(action)">
                <span :class="styles.textBlock"><span :class="styles.title">{{ action.label }}</span><span v-if="action.subtitle" :class="styles.subtitle">{{ action.subtitle }}</span></span>
              </button>
            </li>
            <li v-if="systemGroup.length" :class="styles.systemGroup" role="presentation">
              <ul :class="styles.list">
                <li v-for="action in systemGroup" :key="action.id">
                  <button type="button" :class="styles.row" role="menuitem" :data-icon-placement="iconPlacement" :disabled="action.disabled" @click="select(action)">
                    <span :class="styles.textBlock"><span :class="styles.title">{{ action.label }}</span></span>
                  </button>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </Teleport>
  </div>
</template>

// packages/svelte/src/lib/components/QuickActions/HomeScreenQuickActions.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { LONG_PRESS_MS } from '../../ContextMenu/utils';
  import type { QuickActionIconPlacement, QuickActionItem } from '../../QuickActions/types';
  import {
    estimateQuickActionMenuHeight,
    prepareQuickActions,
    resolveQuickActionMenuPosition,
  } from '../../QuickActions/utils';
  import styles from '@larose-ui/styles/components/QuickActions/QuickActions.module.css';
  import { cn } from '../../utils/cn';
  import { portal } from '../../utils/portal';

  let {
    appName,
    icon,
    actions,
    iconPlacement = 'leading',
    includeSystemActions = true,
    systemActions,
    onActionSelect,
    open,
    onOpenChange,
    class: className,
    style,
  }: {
    appName: string;
    icon?: Snippet;
    actions: QuickActionItem[];
    iconPlacement?: QuickActionIconPlacement;
    includeSystemActions?: boolean;
    systemActions?: QuickActionItem[];
    onActionSelect?: (action: QuickActionItem) => void;
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    class?: string;
    style?: string;
  } = $props();

  const menuId = $props.id();
  let iconEl = $state<HTMLDivElement | null>(null);
  let longPressTimer = $state<number | null>(null);
  let internalOpen = $state(false);
  let position = $state({ x: 0, y: 0 });

  const isOpen = $derived(open ?? internalOpen);
  const preparedActions = $derived(
    prepareQuickActions(actions, { includeSystemActions, systemActions }),
  );
  const appActions = $derived(preparedActions.filter((action) => !action.system));
  const systemGroup = $derived(preparedActions.filter((action) => action.system));

  function setOpen(next: boolean) {
    if (open === undefined) internalOpen = next;
    onOpenChange?.(next);
  }

  function openAboveIcon() {
    const rect = iconEl?.getBoundingClientRect();
    if (!rect) return;
    const menuWidth = 260;
    const menuHeight = estimateQuickActionMenuHeight(preparedActions.length);
    position = resolveQuickActionMenuPosition(rect, menuWidth, menuHeight);
    setOpen(true);
  }

  function close() {
    setOpen(false);
  }

  function clearLongPress() {
    if (longPressTimer !== null) {
      window.clearTimeout(longPressTimer);
      longPressTimer = null;
    }
  }

  function handleSelect(action: QuickActionItem) {
    if (action.disabled) return;
    action.onSelect?.();
    onActionSelect?.(action);
    close();
  }

  $effect(() => {
    if (!isOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
    };
    const onPointerDownOutside = (event: PointerEvent) => {
      const target = event.target as Node | null;
      if (!target) return;
      const surface = document.getElementById(menuId);
      if (surface?.contains(target)) return;
      if (iconEl?.contains(target)) return;
      close();
    };
    document.addEventListener('keydown', onKeyDown);
    const timer = window.setTimeout(() => {
      document.addEventListener('pointerdown', onPointerDownOutside, true);
    }, 0);
    return () => {
      window.clearTimeout(timer);
      document.removeEventListener('keydown', onKeyDown);
      document.removeEventListener('pointerdown', onPointerDownOutside, true);
    };
  });
</script>

<div class={cn(styles.quickActionsWrap, className)} {style}>
  <div
    bind:this={iconEl}
    class={styles.appIcon}
    role="button"
    tabindex="0"
    aria-label={appName}
    aria-haspopup="menu"
    aria-expanded={isOpen}
    aria-controls={isOpen ? menuId : undefined}
    onpointerdown={(event) => {
      if (event.pointerType === 'mouse') return;
      clearLongPress();
      longPressTimer = window.setTimeout(openAboveIcon, LONG_PRESS_MS);
    }}
    onpointerup={clearLongPress}
    onpointercancel={clearLongPress}
    onpointerleave={clearLongPress}
    oncontextmenu={(event) => {
      event.preventDefault();
      openAboveIcon();
    }}
  >
    {#if icon}{@render icon()}{/if}
  </div>
  <span class={styles.hint}>Touch and hold for quick actions</span>

  {#if isOpen}
    <div use:portal>
      <div class={styles.menuBackdrop} role="presentation" onclick={close}></div>
      <div
        id={menuId}
        class={styles.menu}
        role="menu"
        aria-label={`${appName} quick actions`}
        style={`position:fixed;left:${position.x}px;top:${position.y}px;z-index:1000;`}
        onclick={(event) => event.stopPropagation()}
      >
        <ul class={styles.list}>
          {#each appActions as action (action.id)}
            <li>
              <button
                type="button"
                class={styles.row}
                role="menuitem"
                data-icon-placement={iconPlacement}
                data-destructive={action.destructive ? 'true' : undefined}
                disabled={action.disabled}
                onclick={() => handleSelect(action)}
              >
                <span class={styles.textBlock}>
                  <span class={styles.title}>{action.label}</span>
                  {#if action.subtitle}
                    <span class={styles.subtitle}>{action.subtitle}</span>
                  {/if}
                </span>
              </button>
            </li>
          {/each}
          {#if systemGroup.length > 0}
            <li class={styles.systemGroup} role="presentation">
              <ul class={styles.list}>
                {#each systemGroup as action (action.id)}
                  <li>
                    <button
                      type="button"
                      class={styles.row}
                      role="menuitem"
                      data-icon-placement={iconPlacement}
                      data-destructive={action.destructive ? 'true' : undefined}
                      disabled={action.disabled}
                      onclick={() => handleSelect(action)}
                    >
                      <span class={styles.textBlock}>
                        <span class={styles.title}>{action.label}</span>
                      </span>
                    </button>
                  </li>
                {/each}
              </ul>
            </li>
          {/if}
        </ul>
      </div>
    </div>
  {/if}
</div>
