// packages/vue/src/components/SplitView/SplitViewToolbar.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/SplitView/SplitView.module.css';
import { cn } from '../../utils/cn';
import { useSplitView } from '../../composables/useSplitView';

defineProps<{
  class?: string;
  style?: Record<string, string | number>;
}>();

const { hiddenPanes, showPane } = useSplitView();
</script>

<template>
  <div
    v-if="$slots.actions || hiddenPanes.length > 0"
    :class="cn(styles.toolbar, $props.class)"
    :style="$props.style"
    role="toolbar"
    aria-label="Split view toolbar"
  >
    <slot name="actions" />
    <button
      v-for="pane in hiddenPanes"
      :key="pane.id"
      type="button"
      :class="styles.toolbarButton"
      @click="showPane(pane.id)"
    >
      Show {{ pane.label }}
    </button>
  </div>
</template>

// packages/svelte/src/lib/components/SplitView/SplitViewToolbar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getSplitViewContext } from '../../SplitView/context';
  import styles from '@larose-ui/styles/components/SplitView/SplitView.module.css';

  let {
    actions,
    class: className,
    style,
  }: { actions?: Snippet; class?: string; style?: string } = $props();

  const ctx = getSplitViewContext();
  const hiddenPanes = $derived(ctx.hiddenPanes);
</script>

{#if actions || hiddenPanes.length > 0}
  <div
    class={[styles.toolbar, className].filter(Boolean).join(' ')}
    {style}
    role="toolbar"
    aria-label="Split view toolbar"
  >
    {@render actions?.()}
    {#each hiddenPanes as pane (pane.id)}
      <button type="button" class={styles.toolbarButton} onclick={() => ctx.showPane(pane.id)}>
        Show {pane.label}
      </button>
    {/each}
  </div>
{/if}
