// packages/react/src/DataTable/DataTable.tsx
import type { ReactNode } from 'react';
import { EmptyState } from '../EmptyState/EmptyState';
import { Skeleton } from '../Skeleton/Skeleton';
import styles from '@larose-ui/styles/components/DataTable/DataTable.module.css';

export interface DataTableColumn<T> {
  key: string;
  header: string;
  accessor?: (row: T) => ReactNode;
  render?: (row: T) => ReactNode;
}

export interface DataTableProps<T> {
  data: T[];
  columns: DataTableColumn<T>[];
  keyExtractor: (row: T) => string;
  caption?: string;
  'aria-label'?: string;
  loading?: boolean;
  emptyTitle?: string;
  emptyDescription?: string;
  emptyMessage?: string;
  striped?: boolean;
  skeletonRows?: number;
  className?: string;
}

function renderCell<T>(row: T, column: DataTableColumn<T>): ReactNode {
  if (column.render) return column.render(row);
  if (column.accessor) return column.accessor(row);
  return null;
}

export function DataTable<T>({
  data,
  columns,
  keyExtractor,
  caption,
  'aria-label': ariaLabel,
  loading = false,
  emptyTitle = 'No data',
  emptyDescription,
  emptyMessage,
  striped = false,
  skeletonRows = 3,
  className,
}: DataTableProps<T>) {
  if (loading) {
    return (
      <div
        className={[styles.wrapper, className].filter(Boolean).join(' ')}
        data-state="loading"
        aria-busy="true"
        aria-label={ariaLabel ?? caption ?? 'Loading table'}
      >
        {Array.from({ length: skeletonRows }).map((_, index) => (
          <div key={index} className={styles.skeletonRow}>
            {columns.map((column) => (
              <Skeleton key={column.key} height="1rem" width={`${100 / columns.length}%`} />
            ))}
          </div>
        ))}
      </div>
    );
  }

  if (data.length === 0) {
    return (
      <div
        className={[styles.wrapper, className].filter(Boolean).join(' ')}
        data-state="empty"
      >
        <div className={styles.empty}>
          <EmptyState
            title={emptyTitle}
            description={emptyDescription ?? emptyMessage}
            state="empty"
          />
        </div>
      </div>
    );
  }

  return (
    <div className={[styles.wrapper, className].filter(Boolean).join(' ')} data-state="ready">
      <table className={styles.table} aria-label={ariaLabel}>
        {caption && <caption className={styles.caption}>{caption}</caption>}
        <thead>
          <tr>
            {columns.map((column) => (
              <th key={column.key} scope="col" className={styles.headCell}>
                {column.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row) => (
            <tr key={keyExtractor(row)} className={styles.row} data-striped={striped ? 'true' : undefined}>
              {columns.map((column) => (
                <td key={column.key} className={styles.cell}>
                  {renderCell(row, column)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// packages/svelte/src/lib/components/DataTable/DataTable.svelte
<script lang="ts">
  import styles from '@larose-ui/styles/components/DataTable/DataTable.module.css';
  import { cn } from '../../utils/cn';
  import EmptyState from '../EmptyState/EmptyState.svelte';
  import Skeleton from '../Skeleton/Skeleton.svelte';

  export interface DataTableColumn<T = Record<string, unknown>> {
    key: string;
    header: string;
    accessor?: (row: T) => unknown;
    render?: (row: T) => unknown;
  }

  interface Props {
    data: Record<string, unknown>[];
    columns: DataTableColumn[];
    keyExtractor: (row: Record<string, unknown>) => string;
    caption?: string;
    ariaLabel?: string;
    loading?: boolean;
    emptyTitle?: string;
    emptyDescription?: string;
    striped?: boolean;
    skeletonRows?: number;
    class?: string;
    style?: string;
  }

  let {
    data,
    columns,
    keyExtractor,
    caption,
    ariaLabel,
    loading = false,
    emptyTitle = 'No data',
    emptyDescription,
    striped = false,
    skeletonRows = 3,
    class: className,
    style,
  }: Props = $props();

  function cell(row: Record<string, unknown>, column: DataTableColumn) {
    if (column.render) return column.render(row);
    if (column.accessor) return column.accessor(row);
    return row[column.key];
  }
</script>

<div class={cn(styles.wrapper, className)} {style}>
  {#if loading}
    {#each Array.from({ length: skeletonRows }) as _, i (i)}
      <div class={styles.skeletonRow}><Skeleton /></div>
    {/each}
  {:else if !data.length}
    <EmptyState title={emptyTitle} description={emptyDescription} class={styles.empty} />
  {:else}
    <table class={styles.table} aria-label={ariaLabel} data-striped={striped ? 'true' : undefined}>
      {#if caption}<caption class={styles.caption}>{caption}</caption>{/if}
      <thead>
        <tr>
          {#each columns as column (column.key)}
            <th class={styles.headCell} scope="col">{column.header}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each data as row (keyExtractor(row))}
          <tr class={styles.row}>
            {#each columns as column (column.key)}
              <td class={styles.cell}>{cell(row, column)}</td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</div>
