// packages/vue/src/components/Sharing/ShareToolbar.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { CollaborationAction, Collaborator, ShareDestination, SharePermissionOption, ShareSettings } from '../../Sharing/types';
import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';
import { cn } from '../../utils/cn';
import ShareButton from './ShareButton.vue';
import ShareSheet from './ShareSheet.vue';
import CollaborationButton from './CollaborationButton.vue';
import CollaborationPopover from './CollaborationPopover.vue';

const props = withDefaults(defineProps<{
  shareTitle?: string; collaborating?: boolean; collaborators?: Collaborator[];
  shareSettings?: ShareSettings; destinations?: ShareDestination[]; permissionOptions?: SharePermissionOption[];
  collaborationActions?: CollaborationAction[]; manageLabel?: string; class?: string; style?: Record<string, string | number>;
}>(), {
  shareTitle: 'Share Document',
  collaborating: false,
  collaborators: () => [],
  shareSettings: () => ({ audience: 'invited', permission: 'edit' }),
  destinations: () => [{ id: 'copy-link', label: 'Copy Link' }, { id: 'copy', label: 'Send Copy' }, { id: 'messages', label: 'Messages' }],
});

const emit = defineEmits<{ shareSettingsChange: [ShareSettings]; manage: []; message: []; video: [] }>();
const shareOpen = ref(false);
const settings = ref(props.shareSettings);
</script>

<template>
  <div :class="cn(styles.toolbar, props.class)" :style="props.style">
    <ShareButton @click="shareOpen = true" />
    <CollaborationPopover v-if="collaborating" :collaborators="collaborators" :actions="collaborationActions" :manage-label="manageLabel" @manage="emit('manage')" @message="emit('message')" @video="emit('video')">
      <template #trigger><CollaborationButton :collaborators="collaborators" /></template>
    </CollaborationPopover>
    <slot />
    <ShareSheet :open="shareOpen" :title="shareTitle" :settings="settings" :destinations="destinations" :permission-options="permissionOptions" @close="shareOpen = false" @settings-change="settings = $event; emit('shareSettingsChange', $event)" />
  </div>
</template>

// packages/svelte/src/lib/components/Sharing/ShareToolbar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { CollaborationAction, Collaborator, ShareDestination, SharePermissionOption, ShareSettings } from '../../Sharing/types';
  import ShareButton from './ShareButton.svelte';
  import ShareSheet from './ShareSheet.svelte';
  import CollaborationButton from './CollaborationButton.svelte';
  import CollaborationPopover from './CollaborationPopover.svelte';
  import LinkIcon from './LinkIcon.svelte';
  import CopyIcon from './CopyIcon.svelte';
  import MessageIcon from './MessageIcon.svelte';
  import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';

  const defaultShareSettings: ShareSettings = { audience: 'invited', permission: 'edit' };
  const defaultDestinations: ShareDestination[] = [
    { id: 'copy-link', label: 'Copy Link', icon: LinkIcon },
    { id: 'copy', label: 'Send Copy', icon: CopyIcon },
    { id: 'messages', label: 'Messages', icon: MessageIcon },
  ];

  let {
    shareTitle = 'Share Document',
    collaborating = false,
    collaborators = [],
    shareSettings = defaultShareSettings,
    onShareSettingsChange,
    destinations = defaultDestinations,
    permissionOptions,
    collaborationActions,
    onManageSharedFile,
    manageLabel,
    onMessage,
    onVideo,
    trailing,
    class: className,
    style,
  }: {
    shareTitle?: string;
    collaborating?: boolean;
    collaborators?: Collaborator[];
    shareSettings?: ShareSettings;
    onShareSettingsChange?: (settings: ShareSettings) => void;
    destinations?: ShareDestination[];
    permissionOptions?: SharePermissionOption[];
    collaborationActions?: CollaborationAction[];
    onManageSharedFile?: () => void;
    manageLabel?: string;
    onMessage?: () => void;
    onVideo?: () => void;
    trailing?: Snippet;
    class?: string;
    style?: string;
  } = $props();

  let shareOpen = $state(false);
  let settings = $state(shareSettings);
</script>

<div class={[styles.toolbar, className].filter(Boolean).join(' ')} {style}>
  <ShareButton onclick={() => (shareOpen = true)} />
  {#if collaborating}
    <CollaborationPopover
      {collaborators}
      actions={collaborationActions}
      {manageLabel}
      onManage={onManageSharedFile}
      {onMessage}
      {onVideo}
    >
      {#snippet trigger()}
        <CollaborationButton {collaborators} />
      {/snippet}
    </CollaborationPopover>
  {/if}
  {@render trailing?.()}
  <ShareSheet open={shareOpen} onClose={() => (shareOpen = false)} title={shareTitle} {settings} onSettingsChange={(next) => { settings = next; onShareSettingsChange?.(next); }} {destinations} {permissionOptions} />
</div>
