// packages/react/src/EmptyState/EmptyState.tsx
import type { ReactNode } from 'react';
import type { UIState } from '@larose-ui/core';
import { Button } from '../Button/Button';
import styles from '@larose-ui/styles/components/EmptyState/EmptyState.module.css';

export interface EmptyStateProps {
  title: string;
  description?: string;
  icon?: ReactNode;
  actionLabel?: string;
  onAction?: () => void;
  state?: UIState;
}

export function EmptyState({
  title,
  description,
  icon,
  actionLabel,
  onAction,
  state = 'empty',
}: EmptyStateProps) {
  return (
    <div className={styles.empty} data-state={state} role="status">
      {icon && <div className={styles.icon}>{icon}</div>}
      <h3 className={styles.title}>{title}</h3>
      {description && <p className={styles.description}>{description}</p>}
      {actionLabel && onAction && (
        <div className={styles.action}>
          <Button variant="primary" onClick={onAction}>
            {actionLabel}
          </Button>
        </div>
      )}
    </div>
  );
}

// packages/vue/src/components/EmptyState/EmptyState.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import type { UIState } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/EmptyState/EmptyState.module.css';
import { cn } from '../../utils/cn';
import Button from '../Button/Button.vue';

withDefaults(
  defineProps<{
    title: string;
    description?: string;
    actionLabel?: string;
    state?: UIState;
    class?: string;
    style?: CSSProperties;
  }>(),
  {
    state: 'empty',
  },
);

const emit = defineEmits<{
  action: [];
}>();
</script>

<template>
  <div
    :class="cn(styles.empty, $props.class)"
    :style="style"
    :data-state="state"
    role="status"
  >
    <div v-if="$slots.icon" :class="styles.icon">
      <slot name="icon" />
    </div>
    <h3 :class="styles.title">{{ title }}</h3>
    <p v-if="description" :class="styles.description">{{ description }}</p>
    <div v-if="actionLabel" :class="styles.action">
      <Button variant="primary" @click="emit('action')">
        {{ actionLabel }}
      </Button>
    </div>
  </div>
</template>
