// packages/react/src/Tooltip/Tooltip.tsx
import { useId, useState, type ReactNode } from 'react';
import styles from './Tooltip.module.css';

export type TooltipSide = 'top' | 'bottom' | 'left' | 'right';

export interface TooltipProps {
  content: ReactNode;
  children: ReactNode;
  side?: TooltipSide;
}

export function Tooltip({ content, children, side = 'top' }: TooltipProps) {
  const [visible, setVisible] = useState(false);
  const tooltipId = useId();

  return (
    <span
      className={styles.wrapper}
      onMouseEnter={() => setVisible(true)}
      onMouseLeave={() => setVisible(false)}
      onFocusCapture={() => setVisible(true)}
      onBlurCapture={() => setVisible(false)}
    >
      <span aria-describedby={visible ? tooltipId : undefined}>{children}</span>
      {visible && (
        <span id={tooltipId} role="tooltip" className={styles.tooltip} data-side={side}>
          {content}
        </span>
      )}
    </span>
  );
}

// packages/svelte/src/lib/components/Tooltip/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Tooltip/Tooltip.module.css';
  import { cn } from '../../utils/cn';

  export type TooltipSide = 'top' | 'bottom' | 'left' | 'right';

  interface Props {
    content: string | Snippet;
    children: Snippet;
    side?: TooltipSide;
    class?: string;
    style?: string;
  }

  let { content, children, side = 'top', class: className, style }: Props = $props();

  let visible = $state(false);
  const tooltipId = `lr-tooltip-${Math.random().toString(36).slice(2, 9)}`;
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<span
  class={cn(styles.wrapper, className)}
  {style}
  role="group"
  onmouseenter={() => (visible = true)}
  onmouseleave={() => (visible = false)}
  onfocuscapture={() => (visible = true)}
  onblurcapture={() => (visible = false)}
>
  <span aria-describedby={visible ? tooltipId : undefined}>{@render children()}</span>
  {#if visible}
    <span id={tooltipId} role="tooltip" class={styles.tooltip} data-side={side}>
      {#if typeof content === 'function'}
        {@render content()}
      {:else}
        {content}
      {/if}
    </span>
  {/if}
</span>
