// packages/react/src/DragDrop/Draggable.tsx
import {
  useEffect,
  useRef,
  useState,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from 'react';
import { DRAG_START_THRESHOLD_PX } from '@larose-ui/tokens';
import { useDragDropContext } from './DragDropContext';
import type { DragItem } from './types';
import { distance } from './utils';
import styles from '@larose-ui/styles/components/DragDrop/DragDrop.module.css';

export interface DraggableProps<T = unknown> {
  id: string;
  sourceId: string;
  data: T;
  type?: string;
  label?: string;
  preview?: ReactNode;
  disabled?: boolean;
  children: ReactNode;
  className?: string;
}

export function Draggable<T>({
  id,
  sourceId,
  data,
  type,
  label,
  preview,
  disabled = false,
  children,
  className,
}: DraggableProps<T>) {
  const {
    session,
    beginPointerDrag,
    addItemToSession,
    updatePointer,
    endPointer,
    cancelPointer,
  } = useDragDropContext<T>();

  const ref = useRef<HTMLDivElement>(null);
  const [pending, setPending] = useState(false);
  const originRef = useRef<{ x: number; y: number; pointerId: number } | null>(null);

  const isDragging =
    session?.items.some((item) => item.id === id) ?? false;

  useEffect(() => {
    if (!session) {
      setPending(false);
      originRef.current = null;
    }
  }, [session]);

  useEffect(() => {
    if (!session || session.pointerId !== originRef.current?.pointerId) return;

    const onMove = (event: globalThis.PointerEvent) => {
      if (event.pointerId !== session.pointerId) return;
      updatePointer(event.clientX, event.clientY);
    };

    const onUp = (event: globalThis.PointerEvent) => {
      if (event.pointerId !== session.pointerId) return;
      void endPointer(event.clientX, event.clientY, event.altKey);
    };

    const onCancel = (event: globalThis.PointerEvent) => {
      if (event.pointerId !== session.pointerId) return;
      cancelPointer();
    };

    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
    window.addEventListener('pointercancel', onCancel);
    return () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
      window.removeEventListener('pointercancel', onCancel);
    };
  }, [session, updatePointer, endPointer, cancelPointer]);

  const buildItem = (): DragItem<T> => ({
    id,
    sourceId,
    data,
    type,
    label,
    preview,
  });

  const onPointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (disabled || event.button !== 0) return;
    originRef.current = {
      x: event.clientX,
      y: event.clientY,
      pointerId: event.pointerId,
    };
    setPending(true);
    ref.current?.setPointerCapture(event.pointerId);
  };

  const onPointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (!pending || !originRef.current) return;
    if (event.pointerId !== originRef.current.pointerId) return;

    const moved = distance(
      originRef.current.x,
      originRef.current.y,
      event.clientX,
      event.clientY,
    );

    if (!session && moved >= DRAG_START_THRESHOLD_PX) {
      beginPointerDrag(
        buildItem(),
        event.pointerId,
        event.clientX,
        event.clientY,
        ref.current!,
      );
      setPending(false);
      return;
    }

    if (session && session.pointerId === event.pointerId) {
      updatePointer(event.clientX, event.clientY);
    }
  };

  const onPointerUp = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (session && session.pointerId === event.pointerId) {
      void endPointer(event.clientX, event.clientY, event.altKey);
    }
    if (pending && session && event.shiftKey) {
      addItemToSession(buildItem());
    }
    setPending(false);
    originRef.current = null;
  };

  return (
    <div
      ref={ref}
      className={[styles.draggable, className].filter(Boolean).join(' ')}
      data-dragging={isDragging ? 'true' : undefined}
      data-disabled={disabled ? 'true' : undefined}
      aria-grabbed={isDragging ? true : undefined}
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
    >
      {children}
    </div>
  );
}

// packages/svelte/src/lib/components/DragDrop/Draggable.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { DRAG_START_THRESHOLD_PX } from '@larose-ui/tokens';
  import { getDragDropContext } from '../../DragDrop/context';
  import type { DragItem } from '../../DragDrop/types';
  import { distance } from '../../DragDrop/utils';
  import styles from '@larose-ui/styles/components/DragDrop/DragDrop.module.css';
  import { cn } from '../../utils/cn';

  let {
    id,
    sourceId,
    data,
    type,
    label,
    disabled = false,
    class: className,
    style,
    children,
  }: {
    id: string;
    sourceId: string;
    data: unknown;
    type?: string;
    label?: string;
    disabled?: boolean;
    class?: string;
    style?: string;
    children?: Snippet;
  } = $props();

  const ctx = getDragDropContext();
  let el = $state<HTMLDivElement | null>(null);
  let pending = $state(false);
  let origin: { x: number; y: number; pointerId: number } | null = null;
  const isDragging = $derived(ctx.getSession()?.items.some((item) => item.id === id) ?? false);

  function buildItem(): DragItem {
    return { id, sourceId, data, type, label };
  }

  $effect(() => {
    if (!ctx.getSession()) {
      pending = false;
      origin = null;
    }
  });
</script>

<div
  bind:this={el}
  class={cn(styles.draggable, className)}
  {style}
  data-dragging={isDragging ? 'true' : undefined}
  data-disabled={disabled ? 'true' : undefined}
  aria-grabbed={isDragging ? true : undefined}
  onpointerdown={(event) => {
    if (disabled || event.button !== 0) return;
    origin = { x: event.clientX, y: event.clientY, pointerId: event.pointerId };
    pending = true;
    el?.setPointerCapture(event.pointerId);
  }}
  onpointermove={(event) => {
    if (!pending || !origin || event.pointerId !== origin.pointerId) return;
    const moved = distance(origin.x, origin.y, event.clientX, event.clientY);
    const session = ctx.getSession();
    if (!session && moved >= DRAG_START_THRESHOLD_PX && el) {
      ctx.beginPointerDrag(buildItem(), event.pointerId, event.clientX, event.clientY, el);
      pending = false;
      return;
    }
    if (session && session.pointerId === event.pointerId) {
      ctx.updatePointer(event.clientX, event.clientY);
    }
  }}
  onpointerup={(event) => {
    const session = ctx.getSession();
    if (session && session.pointerId === event.pointerId) {
      void ctx.endPointer(event.clientX, event.clientY, event.altKey);
    }
    if (pending && session && event.shiftKey) {
      ctx.addItemToSession(buildItem());
    }
    pending = false;
    origin = null;
  }}
>
  {@render children?.()}
</div>
