// apps/playground/cross-framework/ButtonGroupDemo.svelte
<script lang="ts">
  import Button from '../../../packages/svelte/src/lib/components/Button/Button.svelte';
  import ButtonGroup from '../../../packages/svelte/src/lib/components/Button/ButtonGroup.svelte';

  interface Props {
    orientation?: 'horizontal' | 'vertical';
    fullWidth?: boolean;
    ariaLabel?: string;
  }

  let {
    orientation = 'horizontal',
    fullWidth = false,
    ariaLabel = 'Save options',
  }: Props = $props();
</script>

<ButtonGroup {orientation} {fullWidth} aria-label={ariaLabel}>
  <Button variant="primary" buttonRole="primary" {fullWidth}>Save</Button>
  <Button variant="secondary" {fullWidth}>Save As…</Button>
  <Button variant="secondary" buttonRole="cancel" {fullWidth}>Cancel</Button>
</ButtonGroup>

// apps/playground/cross-framework/ButtonGroupDemo.vue
<script setup lang="ts">
import Button from '../../../packages/vue/src/components/Button/Button.vue';
import ButtonGroup from '../../../packages/vue/src/components/Button/ButtonGroup.vue';

withDefaults(
  defineProps<{
    orientation?: 'horizontal' | 'vertical';
    fullWidth?: boolean;
    ariaLabel?: string;
  }>(),
  {
    orientation: 'horizontal',
    fullWidth: false,
    ariaLabel: 'Save options',
  },
);
</script>

<template>
  <ButtonGroup :orientation="orientation" :full-width="fullWidth" :aria-label="ariaLabel">
    <Button variant="primary" button-role="primary" :full-width="fullWidth">Save</Button>
    <Button variant="secondary" :full-width="fullWidth">Save As…</Button>
    <Button variant="secondary" button-role="cancel" :full-width="fullWidth">Cancel</Button>
  </ButtonGroup>
</template>
