// apps/playground/cross-framework/CardDemo.vue
<script setup lang="ts">
import Card from '../../../packages/vue/src/components/Card/Card.vue';
import Button from '../../../packages/vue/src/components/Button/Button.vue';

withDefaults(
  defineProps<{
    title?: string;
    description?: string;
    padding?: 'none' | 'sm' | 'md' | 'lg';
    bodyText?: string;
    footerLabel?: string;
  }>(),
  {
    padding: 'md',
    bodyText: 'Card body content',
  },
);
</script>

<template>
  <Card :title="title" :description="description" :padding="padding">
    {{ bodyText }}
    <template v-if="footerLabel" #footer>
      <Button size="sm">{{ footerLabel }}</Button>
    </template>
  </Card>
</template>

// apps/playground/cross-framework/CardDemo.svelte
<script lang="ts">
  import { createRawSnippet } from 'svelte';
  import Card from '../../../packages/svelte/src/lib/components/Card/Card.svelte';
  import Button from '../../../packages/svelte/src/lib/components/Button/Button.svelte';

  interface Props {
    title?: string;
    description?: string;
    padding?: 'none' | 'sm' | 'md' | 'lg';
    bodyText?: string;
    footerLabel?: string;
  }

  let {
    title,
    description,
    padding = 'md',
    bodyText = 'Card body content',
    footerLabel,
  }: Props = $props();

  const bodySnippet = $derived(
    createRawSnippet(() => ({
      render: () => bodyText ?? '',
    })),
  );
</script>

{#if footerLabel}
  <Card {title} {description} {padding} children={bodySnippet}>
    {#snippet footer()}
      <Button size="sm">{footerLabel}</Button>
    {/snippet}
  </Card>
{:else}
  <Card {title} {description} {padding} children={bodySnippet} />
{/if}
