// apps/playground/cross-framework/DisclosureGroupDemo.vue
<script setup lang="ts">
import DisclosureTriangle from '../../../packages/vue/src/components/Disclosure/DisclosureTriangle.vue';
import Input from '../../../packages/vue/src/components/Input/Input.vue';

withDefaults(
  defineProps<{
    label?: string;
    defaultExpanded?: boolean;
  }>(),
  {
    label: 'Delivery details',
    defaultExpanded: true,
  },
);
</script>

<template>
  <DisclosureTriangle :label="label" :default-expanded="defaultExpanded">
    <Input label="Recipient" model-value="sara@company.com" />
    <Input label="Notes" model-value="Leave at front desk" />
  </DisclosureTriangle>
</template>

// apps/playground/cross-framework/DisclosureGroupDemo.svelte
<script lang="ts">
  import DisclosureTriangle from '../../../packages/svelte/src/lib/components/Disclosure/DisclosureTriangle.svelte';
  import Input from '../../../packages/svelte/src/lib/components/Input/Input.svelte';

  interface Props {
    label?: string;
    defaultExpanded?: boolean;
  }

  let { label = 'Delivery details', defaultExpanded = true }: Props = $props();
</script>

<DisclosureTriangle {label} {defaultExpanded}>
  <Input label="Recipient" value="sara@company.com" />
  <Input label="Notes" value="Leave at front desk" />
</DisclosureTriangle>
