// apps/playground/cross-framework/SquareButtonsDemo.svelte
<script lang="ts">
  import SquareButton from '../../../packages/svelte/src/lib/components/Button/SquareButton.svelte';
</script>

<div style="display: flex; gap: 0.5rem; align-items: center">
  <SquareButton aria-label="Add row" tooltip="Add row">
    {#snippet icon()}+{/snippet}
  </SquareButton>
  <SquareButton aria-label="Remove row" tooltip="Remove row">
    {#snippet icon()}−{/snippet}
  </SquareButton>
</div>

// apps/playground/cross-framework/SquareButtonsDemo.vue
<script setup lang="ts">
import SquareButton from '../../../packages/vue/src/components/Button/SquareButton.vue';
</script>

<template>
  <div style="display: flex; gap: 0.5rem; align-items: center">
    <SquareButton aria-label="Add row" tooltip="Add row">+</SquareButton>
    <SquareButton aria-label="Remove row" tooltip="Remove row">−</SquareButton>
  </div>
</template>
