// apps/playground/cross-framework/ToastDemoBody.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import Button from '../../../packages/vue/src/components/Button/Button.vue';
import { useToast } from '../../../packages/vue/src/composables/useToast';

const props = withDefaults(
  defineProps<{
    autoTitle?: string;
    autoMessage?: string;
    buttonLabel?: string;
  }>(),
  {
    autoTitle: 'Welcome',
    autoMessage: 'laRose toast notifications are ready.',
    buttonLabel: 'Show toast',
  },
);

const { toast } = useToast();

onMounted(() => {
  toast({
    title: props.autoTitle,
    message: props.autoMessage,
    variant: 'info',
  });
});

function show() {
  toast({ title: 'Saved', message: 'Employee record updated.', variant: 'success' });
}
</script>

<template>
  <Button @click="show">{{ buttonLabel }}</Button>
</template>

// apps/playground/cross-framework/ToastDemoBody.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Button from '../../../packages/svelte/src/lib/components/Button/Button.svelte';
  import { getToast } from '../../../packages/svelte/src/lib/toast/context';

  let {
    autoTitle = 'Welcome',
    autoMessage = 'laRose toast notifications are ready.',
    buttonLabel = 'Show toast',
  }: {
    autoTitle?: string;
    autoMessage?: string;
    buttonLabel?: string;
  } = $props();

  const { toast } = getToast();

  onMount(() => {
    toast({
      title: autoTitle,
      message: autoMessage,
      variant: 'info',
    });
  });

  function show() {
    toast({ title: 'Saved', message: 'Employee record updated.', variant: 'success' });
  }
</script>

<Button onclick={show}>{buttonLabel}</Button>
