// packages/vue/src/components/Button/SquareButton.vue
<script setup lang="ts">
import type { ButtonHTMLAttributes } from 'vue';
import styles from '@larose-ui/styles/components/Button/Button.module.css';
import { cn } from '../../utils/cn';
import Tooltip from '../Tooltip/Tooltip.vue';

withDefaults(
  defineProps<{
    tooltip?: string;
    pressed?: boolean;
    class?: string;
    style?: ButtonHTMLAttributes['style'];
    disabled?: boolean;
    ariaLabel?: string;
  }>(),
  {
    pressed: false,
  },
);
</script>

<template>
  <Tooltip v-if="tooltip" :content="tooltip">
    <button
      type="button"
      :class="cn(styles.squareButton, $props.class)"
      :style="style"
      :data-pressed="pressed ? 'true' : undefined"
      :aria-label="ariaLabel"
      :aria-pressed="pressed ? 'true' : undefined"
      :disabled="disabled"
    >
      <span :class="styles.squareButtonIcon">
        <slot />
      </span>
    </button>
  </Tooltip>
  <button
    v-else
    type="button"
    :class="cn(styles.squareButton, $props.class)"
    :style="style"
    :data-pressed="pressed ? 'true' : undefined"
    :aria-label="ariaLabel"
    :aria-pressed="pressed ? 'true' : undefined"
    :disabled="disabled"
  >
    <span :class="styles.squareButtonIcon">
      <slot />
    </span>
  </button>
</template>

// packages/svelte/src/lib/components/Button/SquareButton.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Button/Button.module.css';
  import Tooltip from '../Tooltip/Tooltip.svelte';
  import { cn } from '../../utils/cn';

  interface Props {
    icon: Snippet;
    tooltip?: string;
    pressed?: boolean;
    class?: string;
    style?: string;
    disabled?: boolean;
    'aria-label'?: string;
    onclick?: (event: MouseEvent) => void;
  }

  let {
    icon,
    tooltip,
    pressed = false,
    class: className,
    style,
    disabled,
    'aria-label': ariaLabel,
    onclick,
  }: Props = $props();
</script>

{#snippet button()}
  <button
    type="button"
    class={cn(styles.squareButton, className)}
    {style}
    data-pressed={pressed ? 'true' : undefined}
    aria-label={ariaLabel}
    aria-pressed={pressed ? 'true' : undefined}
    {disabled}
    {onclick}
  >
    <span class={styles.squareButtonIcon}>{@render icon()}</span>
  </button>
{/snippet}

{#if tooltip}
  <Tooltip content={tooltip}>
    {@render button()}
  </Tooltip>
{:else}
  {@render button()}
{/if}
