// packages/svelte/src/lib/components/Disclosure/DisclosureButton.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Disclosure/Disclosure.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    label?: string;
    expanded?: boolean;
    defaultExpanded?: boolean;
    disabled?: boolean;
    class?: string;
    style?: string;
    ariaLabel?: string;
    onExpandedChange?: (expanded: boolean) => void;
    children: Snippet;
    detail?: Snippet;
  }

  let {
    label,
    expanded,
    defaultExpanded = false,
    disabled = false,
    class: className,
    style,
    ariaLabel = 'Show more options',
    onExpandedChange,
    children,
    detail,
  }: Props = $props();

  let internal = $state(defaultExpanded);
  const isExpanded = $derived(expanded !== undefined ? expanded : internal);
  const panelId = `disclosure-btn-${Math.random().toString(36).slice(2)}`;

  function toggle() {
    if (disabled) return;
    const next = !isExpanded;
    if (expanded === undefined) internal = next;
    onExpandedChange?.(next);
  }
</script>

<div class={cn(styles.group, className)} {style}>
  <div class={styles.buttonRow}>
    <div class={styles.buttonContent}>
      {#if label}<div class={styles.triangleLabel}>{label}</div>{/if}
      {@render children()}
    </div>
    {#if detail}
      <button
        type="button"
        class={styles.disclosureButton}
        data-expanded={isExpanded ? 'true' : 'false'}
        aria-expanded={isExpanded}
        aria-controls={panelId}
        aria-label={ariaLabel}
        {disabled}
        onclick={toggle}
      >
        <svg class={styles.disclosureButtonIcon} viewBox="0 0 10 10" fill="none" aria-hidden="true">
          <path d="M2 3.5 5 6.5 8 3.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
        </svg>
      </button>
    {/if}
  </div>
  {#if detail && isExpanded}
    <div id={panelId} class={styles.buttonPanel} role="region" aria-label={ariaLabel}>
      {@render detail()}
    </div>
  {/if}
</div>

// packages/react/src/Disclosure/DisclosureButton.tsx
import { useCallback, useId, useState, type ReactNode } from 'react';
import styles from '@larose-ui/styles/components/Disclosure/Disclosure.module.css';

function ChevronIcon() {
  return (
    <svg className={styles.disclosureButtonIcon} viewBox="0 0 10 10" fill="none" aria-hidden="true">
      <path d="M2 3.5 5 6.5 8 3.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    </svg>
  );
}

export interface DisclosureButtonProps {
  /** Visible label for the adjacent control region. */
  label?: string;
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  /** Control placed beside the disclosure button, e.g. Save As field. */
  children: ReactNode;
  /** Content revealed when expanded. Use only one disclosure button per view. */
  detail?: ReactNode;
  disabled?: boolean;
  'aria-label'?: string;
}

/**
 * Push disclosure button — down when collapsed, up when expanded (macOS Save sheet pattern).
 * @see https://developer.apple.com/design/human-interface-guidelines/disclosure-controls
 */
export function DisclosureButton({
  label,
  expanded,
  defaultExpanded = false,
  onExpandedChange,
  children,
  detail,
  disabled = false,
  'aria-label': ariaLabel = 'Show more options',
}: DisclosureButtonProps) {
  const panelId = useId();
  const isControlled = expanded !== undefined;
  const [internalExpanded, setInternalExpanded] = useState(defaultExpanded);
  const isExpanded = isControlled ? expanded : internalExpanded;

  const toggle = useCallback(() => {
    if (disabled) return;
    const next = !isExpanded;
    if (!isControlled) setInternalExpanded(next);
    onExpandedChange?.(next);
  }, [disabled, isControlled, isExpanded, onExpandedChange]);

  return (
    <div className={styles.group}>
      <div className={styles.buttonRow}>
        <div className={styles.buttonContent}>
          {label && <div className={styles.triangleLabel}>{label}</div>}
          {children}
        </div>
        {detail && (
          <button
            type="button"
            className={styles.disclosureButton}
            data-expanded={isExpanded ? 'true' : 'false'}
            aria-expanded={isExpanded}
            aria-controls={panelId}
            aria-label={ariaLabel}
            disabled={disabled}
            onClick={toggle}
          >
            <ChevronIcon />
          </button>
        )}
      </div>
      {detail && isExpanded && (
        <div id={panelId} className={styles.buttonPanel} role="region" aria-label={ariaLabel}>
          {detail}
        </div>
      )}
    </div>
  );
}
