// packages/vue/src/components/SearchField/SearchTokenChip.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/SearchField/SearchField.module.css';
import type { SearchToken } from '../../SearchField/types';

defineProps<{ token: SearchToken }>();
const emit = defineEmits<{ remove: []; select: [] }>();
</script>

<template>
  <button type="button" :class="styles.token" @click="emit('select')">
    <span>{{ token.label }}</span>
    <span
      :class="styles.tokenRemove"
      aria-hidden="true"
      @click.stop="emit('remove')"
    >×</span>
  </button>
</template>

// packages/svelte/src/lib/components/SearchField/SearchTokenChip.svelte
<script lang="ts">
  import styles from '@larose-ui/styles/components/SearchField/SearchField.module.css';
  import type { SearchToken } from '../../SearchField/types';

  interface Props {
    token: SearchToken;
    onRemove?: () => void;
    onSelect?: () => void;
  }

  let { token, onRemove, onSelect }: Props = $props();
</script>

<button type="button" class={styles.token} onclick={onSelect}>
  <span>{token.label}</span>
  <span
    class={styles.tokenRemove}
    aria-hidden="true"
    onclick={(e) => {
      e.stopPropagation();
      onRemove?.();
    }}
  >×</span>
</button>
