// packages/vue/src/components/Switch/Switch.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { Size } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/Switch/Switch.module.css';
import { cn } from '../../utils/cn';

const props = withDefaults(
  defineProps<{
    label: string;
    modelValue?: boolean;
    defaultChecked?: boolean;
    hint?: string;
    disabled?: boolean;
    switchSize?: Size;
    id?: string;
    class?: string;
  }>(),
  {
    switchSize: 'md',
    defaultChecked: false,
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
}>();

const inputId = props.id ?? props.label.toLowerCase().replace(/\s+/g, '-');
const uncontrolled = ref(props.defaultChecked);
const isControlled = computed(() => props.modelValue !== undefined);
const isOn = computed(() => (isControlled.value ? props.modelValue : uncontrolled.value) ?? false);

function handleClick() {
  if (props.disabled) return;
  const next = !isOn.value;
  if (!isControlled.value) uncontrolled.value = next;
  emit('update:modelValue', next);
}
</script>

<template>
  <div :class="styles.wrapper">
    <div :class="styles.row">
      <button
        :id="inputId"
        type="button"
        role="switch"
        :aria-checked="isOn"
        :aria-label="label"
        :aria-describedby="hint ? `${inputId}-hint` : undefined"
        :class="cn(styles.track, props.class)"
        :data-size="switchSize"
        :data-state="isOn ? 'on' : 'off'"
        :disabled="disabled"
        @click="handleClick"
      >
        <span :class="styles.thumb" aria-hidden="true" />
      </button>
      <span :class="styles.label">{{ label }}</span>
    </div>
    <span v-if="hint" :id="`${inputId}-hint`" :class="styles.hint">{{ hint }}</span>
  </div>
</template>

// packages/react/src/Switch/Switch.tsx
import { useCallback, type ButtonHTMLAttributes } from 'react';
import type { Size } from '@larose/core';
import styles from './Switch.module.css';

export interface SwitchProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> {
  label: string;
  checked?: boolean;
  defaultChecked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  hint?: string;
  switchSize?: Size;
}

export function Switch({
  label,
  checked,
  defaultChecked,
  onCheckedChange,
  hint,
  disabled,
  switchSize = 'md',
  className,
  id,
  ...props
}: SwitchProps) {
  const inputId = id ?? label.toLowerCase().replace(/\s+/g, '-');
  const isControlled = checked !== undefined;
  const isOn = isControlled ? checked : defaultChecked ?? false;

  const handleClick = useCallback(() => {
    if (disabled) return;
    const next = isControlled ? !checked : !isOn;
    onCheckedChange?.(next);
  }, [checked, disabled, isControlled, isOn, onCheckedChange]);

  return (
    <div className={styles.wrapper}>
      <div className={styles.row}>
        <button
          id={inputId}
          type="button"
          role="switch"
          aria-checked={isOn}
          aria-label={label}
          aria-describedby={hint ? `${inputId}-hint` : undefined}
          className={[styles.track, className].filter(Boolean).join(' ')}
          data-size={switchSize}
          data-state={isOn ? 'on' : 'off'}
          disabled={disabled}
          onClick={handleClick}
          {...props}
        >
          <span className={styles.thumb} aria-hidden="true" />
        </button>
        <span className={styles.label}>{label}</span>
      </div>
      {hint && (
        <span className={styles.hint} id={`${inputId}-hint`}>
          {hint}
        </span>
      )}
    </div>
  );
}
