// packages/svelte/src/lib/components/TabView/TabViewTab.svelte
<script lang="ts">
  import { getTabViewContext } from '../../TabView/context';
  import { formatTabLabel } from '../../TabView/utils';
  import styles from '@larose-ui/styles/components/TabView/TabView.module.css';

  let {
    value,
    label,
    disabled,
    class: className,
    style,
  }: { value: string; label: string; disabled?: boolean; class?: string; style?: string } = $props();

  const ctx = $derived(getTabViewContext('TabViewTab'));
  const selected = $derived(ctx.value === value);
</script>

<li role="presentation" class={className} {style}>
  <button
    type="button"
    id={`${ctx.baseId}-tab-${value}`}
    role="tab"
    class={styles.tab}
    aria-selected={selected}
    aria-controls={`${ctx.baseId}-panel-${value}`}
    tabindex={selected ? 0 : -1}
    data-selected={selected ? 'true' : undefined}
    {disabled}
    onclick={() => ctx.onValueChange(value)}
  >
    {formatTabLabel(label)}
  </button>
</li>

// packages/vue/src/components/TabView/TabViewTab.vue
<script setup lang="ts">
import { computed } from 'vue';
import { formatTabLabel } from '../../TabView/utils';
import styles from '@larose-ui/styles/components/TabView/TabView.module.css';
import { useTabViewContext } from '../../composables/useTabView';

const props = defineProps<{
  value: string;
  label: string;
  disabled?: boolean;
  class?: string;
  style?: Record<string, string | number>;
}>();

const ctx = useTabViewContext('TabViewTab');
const selected = computed(() => ctx.value.value === props.value);
const tabId = computed(() => `${ctx.baseId}-tab-${props.value}`);
const panelId = computed(() => `${ctx.baseId}-panel-${props.value}`);
</script>

<template>
  <li role="presentation" :class="props.class" :style="props.style">
    <button
      type="button"
      :id="tabId"
      role="tab"
      :class="styles.tab"
      :aria-selected="selected"
      :aria-controls="panelId"
      :tabindex="selected ? 0 : -1"
      :data-selected="selected ? 'true' : undefined"
      :disabled="disabled"
      @click="ctx.onValueChange(value)"
    >
      {{ formatTabLabel(label) }}
    </button>
  </li>
</template>
