// packages/react/src/TextView/TextView.tsx
import {
  forwardRef,
  type CSSProperties,
  type ReactNode,
  type TextareaHTMLAttributes,
} from 'react';
import type { TypographyRole } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/TextView/TextView.module.css';

export interface TextViewProps extends Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'readOnly'> {
  /** When true, shows a keyboard-capable editor. */
  editable?: boolean;
  /** Allows selecting/copying useful text in read-only mode. */
  selectable?: boolean;
  maxHeight?: string;
  typographyRole?: TypographyRole;
  children?: ReactNode;
}

/**
 * Multiline styled text for long, editable, or specially formatted content.
 * @see https://developer.apple.com/design/human-interface-guidelines/text-views
 */
export const TextView = forwardRef<HTMLTextAreaElement, TextViewProps>(
  (
    {
      editable = false,
      selectable = true,
      maxHeight,
      typographyRole = 'body',
      className,
      children,
      value,
      defaultValue,
      disabled,
      inputMode,
      ...props
    },
    ref,
  ) => {
    const style = maxHeight
      ? ({ '--lr-text-view-max-height': maxHeight } as CSSProperties)
      : undefined;

    if (editable) {
      return (
        <div
          className={[styles.view, styles.scrollable, className].filter(Boolean).join(' ')}
          data-lr-type={typographyRole}
          style={style}
        >
          <textarea
            ref={ref}
            className={styles.editable}
            disabled={disabled}
            value={value}
            defaultValue={defaultValue}
            inputMode={inputMode}
            {...props}
          />
        </div>
      );
    }

    return (
      <div
        className={[styles.view, styles.display, styles.scrollable, className].filter(Boolean).join(' ')}
        data-lr-type={typographyRole}
        data-selectable={selectable ? 'true' : 'false'}
        style={style}
        aria-readonly="true"
      >
        {children ?? value ?? defaultValue}
      </div>
    );
  },
);

TextView.displayName = 'TextView';

// packages/svelte/src/lib/components/TextView/TextView.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { TypographyRole } from '@larose-ui/core';
  import styles from '@larose-ui/styles/components/TextView/TextView.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    editable?: boolean;
    selectable?: boolean;
    maxHeight?: string;
    typographyRole?: TypographyRole;
    value?: string;
    class?: string;
    style?: string;
    disabled?: boolean;
    children?: Snippet;
  }

  let {
    editable = false,
    selectable = true,
    maxHeight,
    typographyRole = 'body',
    value = $bindable(''),
    class: className,
    style,
    disabled,
    children,
  }: Props = $props();
</script>

<div
  class={cn(styles.view, className)}
  style={`max-height:${maxHeight ?? ''};${style ?? ''}`}
  data-lr-type={typographyRole}
  data-selectable={selectable ? 'true' : undefined}
>
  {#if editable}
    <textarea class={styles.editable} bind:value {disabled}></textarea>
  {:else}
    <div class={cn(styles.display, maxHeight ? styles.scrollable : undefined)}>
      {#if children}{@render children()}{:else}{value}{/if}
    </div>
  {/if}
</div>
