// packages/react/src/Alert/Alert.tsx
import type { ReactNode } from 'react';
import styles from '@larose-ui/styles/components/Alert/Alert.module.css';

export type AlertVariant = 'info' | 'success' | 'warning' | 'error';

export interface AlertProps {
  variant?: AlertVariant;
  title?: string;
  children: ReactNode;
  onDismiss?: () => void;
}

export function Alert({
  variant = 'info',
  title,
  children,
  onDismiss,
}: AlertProps) {
  return (
    <div
      className={styles.alert}
      data-variant={variant}
      role="alert"
    >
      <div className={styles.content}>
        {title && <strong className={styles.title}>{title}</strong>}
        <div className={styles.message}>{children}</div>
      </div>
      {onDismiss && (
        <button
          type="button"
          className={styles.dismiss}
          onClick={onDismiss}
          aria-label="Dismiss alert"
        >
          ×
        </button>
      )}
    </div>
  );
}

// packages/svelte/src/lib/components/Alert/Alert.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Alert/Alert.module.css';

  export type AlertVariant = 'info' | 'success' | 'warning' | 'error';

  interface Props {
    variant?: AlertVariant;
    title?: string;
    onDismiss?: () => void;
    children: Snippet;
  }

  let { variant = 'info', title, onDismiss, children }: Props = $props();
</script>

<div class={styles.alert} data-variant={variant} role="alert">
  <div class={styles.content}>
    {#if title}<strong class={styles.title}>{title}</strong>{/if}
    <div class={styles.message}>{@render children()}</div>
  </div>
  {#if onDismiss}
    <button type="button" class={styles.dismiss} aria-label="Dismiss alert" onclick={onDismiss}>
      ×
    </button>
  {/if}
</div>
