// packages/react/src/DataEntry/SecureField.tsx
import { forwardRef } from 'react';
import { Input, type InputProps } from '../Input/Input';

export type SecureFieldProps = Omit<InputProps, 'type' | 'defaultValue'>;

/**
 * Password entry that follows Apple HIG: never prepopulate sensitive fields.
 * @see https://developer.apple.com/design/human-interface-guidelines/entering-data
 */
export const SecureField = forwardRef<HTMLInputElement, SecureFieldProps>(
  ({ autoComplete = 'current-password', ...props }, ref) => {
    if (process.env.NODE_ENV !== 'production' && props.value !== undefined && props.value !== '') {
      console.warn(
        '[SecureField] Avoid prepopulating password fields. Use biometric or keychain auth instead.',
      );
    }

    return (
      <Input
        ref={ref}
        type="password"
        autoComplete={autoComplete}
        spellCheck={false}
        {...props}
      />
    );
  },
);

SecureField.displayName = 'SecureField';

// packages/svelte/src/lib/components/DataEntry/SecureField.svelte
<script lang="ts">
  import type { Size, UIState } from '@larose-ui/core';
  import Input from '../Input/Input.svelte';

  interface Props {
    label?: string;
    hint?: string;
    fieldState?: UIState;
    loading?: boolean;
    error?: string | null;
    disabled?: boolean;
    readOnly?: boolean;
    required?: boolean;
    inputSize?: Size;
    id?: string;
    autocomplete?: string;
    placeholder?: string;
    name?: string;
    class?: string;
    style?: string;
    value?: string;
  }

  let {
    label,
    hint,
    fieldState,
    loading = false,
    error = null,
    disabled,
    readOnly,
    required = false,
    inputSize = 'md',
    id,
    autocomplete = 'current-password',
    placeholder,
    name,
    class: className,
    style,
    value = $bindable(''),
  }: Props = $props();

  $effect(() => {
    if (import.meta.env.DEV && value !== undefined && value !== '') {
      console.warn(
        '[SecureField] Avoid prepopulating password fields. Use biometric or keychain auth instead.',
      );
    }
  });
</script>

<Input
  type="password"
  {label}
  {hint}
  {fieldState}
  {loading}
  {error}
  {disabled}
  {readOnly}
  {required}
  {inputSize}
  {id}
  {autocomplete}
  spellcheck={false}
  {placeholder}
  {name}
  class={className}
  {style}
  bind:value
/>
