// packages/vue/src/components/Sharing/ShareSheet.vue
<script setup lang="ts">
import { ref, useId, watch } from 'vue';
import type { ShareDestination, SharePermissionOption, ShareSettings } from '../../Sharing/types';
import { formatSharePermissionSummary } from '../../Sharing/utils';
import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';
import { cn } from '../../utils/cn';
import { ChevronRightIcon } from './icons';

const props = withDefaults(defineProps<{
  open: boolean; title?: string; settings: ShareSettings; destinations?: ShareDestination[];
  permissionOptions?: SharePermissionOption[]; class?: string; style?: Record<string, string | number>;
}>(), {
  title: 'Share',
  destinations: () => [],
  permissionOptions: () => [
    { id: 'invited-edit', audience: 'invited', permission: 'edit', label: 'Only invited people', description: 'Can make changes' },
    { id: 'invited-view', audience: 'invited', permission: 'view', label: 'Only invited people', description: 'Can view only' },
    { id: 'everyone-edit', audience: 'everyone', permission: 'edit', label: 'Everyone', description: 'Can make changes' },
    { id: 'everyone-view', audience: 'everyone', permission: 'view', label: 'Everyone', description: 'Can view only' },
  ],
});

const emit = defineEmits<{ close: []; settingsChange: [ShareSettings] }>();
const titleId = useId();
const showPermissions = ref(false);
watch(() => props.open, (open) => {
  if (!open) return;
  showPermissions.value = false;
  const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') emit('close'); };
  document.addEventListener('keydown', onKey);
  document.body.style.overflow = 'hidden';
  return () => { document.removeEventListener('keydown', onKey); document.body.style.overflow = ''; };
});
</script>

<template>
  <Teleport to="body">
    <div v-if="open" :class="styles.sheetOverlay" role="presentation" @click.self="emit('close')">
      <div :class="cn(styles.sheet, props.class)" :style="props.style" role="dialog" aria-modal="true" :aria-labelledby="titleId">
        <div :class="styles.sheetHeader">
          <h2 :id="titleId" :class="styles.sheetTitle">{{ title }}</h2>
          <button type="button" :class="styles.permissionSummary" :aria-expanded="showPermissions" @click="showPermissions = !showPermissions">
            <span>{{ formatSharePermissionSummary(settings.audience, settings.permission) }}</span>
            <ChevronRightIcon />
          </button>
        </div>
        <div v-if="showPermissions" :class="styles.permissionPanel" role="group" aria-label="Sharing permissions">
          <button
            v-for="option in permissionOptions"
            :key="option.id"
            type="button"
            :class="styles.option"
            :data-selected="option.audience === settings.audience && option.permission === settings.permission ? 'true' : undefined"
            @click="emit('settingsChange', { ...settings, audience: option.audience, permission: option.permission }); showPermissions = false"
          >
            <span :class="styles.optionLabel">{{ option.label }}</span>
            <span v-if="option.description" :class="styles.optionDescription">{{ option.description }}</span>
          </button>
        </div>
        <div :class="styles.destinations" role="menu" aria-label="Share destinations">
          <button v-for="destination in destinations" :key="destination.id" type="button" :class="styles.destination" role="menuitem" @click="destination.onSelect?.(); emit('close')">
            <span>{{ destination.label }}</span>
          </button>
        </div>
        <div v-if="$slots.footer" :class="styles.section"><slot name="footer" /></div>
      </div>
    </div>
  </Teleport>
</template>

// packages/react/src/Sharing/ShareSheet.tsx
import { useEffect, useId, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import type {
  ShareAudience,
  ShareDestination,
  SharePermission,
  SharePermissionOption,
  ShareSettings,
} from './types';
import { formatSharePermissionSummary } from './utils';
import { ChevronRightIcon } from './icons';
import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';

export interface ShareSheetProps {
  open: boolean;
  onClose: () => void;
  title?: string;
  settings: ShareSettings;
  onSettingsChange?: (settings: ShareSettings) => void;
  destinations?: ShareDestination[];
  permissionOptions?: SharePermissionOption[];
  footer?: ReactNode;
}

const defaultDestinations: ShareDestination[] = [];

const defaultPermissionOptions: SharePermissionOption[] = [
  {
    id: 'invited-edit',
    audience: 'invited',
    permission: 'edit',
    label: 'Only invited people',
    description: 'Can make changes',
  },
  {
    id: 'invited-view',
    audience: 'invited',
    permission: 'view',
    label: 'Only invited people',
    description: 'Can view only',
  },
  {
    id: 'everyone-edit',
    audience: 'everyone',
    permission: 'edit',
    label: 'Everyone',
    description: 'Can make changes',
  },
  {
    id: 'everyone-view',
    audience: 'everyone',
    permission: 'view',
    label: 'Everyone',
    description: 'Can view only',
  },
];

export function ShareSheet({
  open,
  onClose,
  title = 'Share',
  settings,
  onSettingsChange,
  destinations = defaultDestinations,
  permissionOptions = defaultPermissionOptions,
  footer,
}: ShareSheetProps) {
  const titleId = useId();
  const [showPermissions, setShowPermissions] = useState(false);

  useEffect(() => {
    if (!open) return;
    setShowPermissions(false);
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', onKeyDown);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKeyDown);
      document.body.style.overflow = '';
    };
  }, [open, onClose]);

  if (!open) return null;

  const summary = formatSharePermissionSummary(settings.audience, settings.permission);

  const selectPermission = (audience: ShareAudience, permission: SharePermission) => {
    onSettingsChange?.({ ...settings, audience, permission });
    setShowPermissions(false);
  };

  return createPortal(
    <div
      className={styles.sheetOverlay}
      role="presentation"
      onClick={(event) => {
        if (event.target === event.currentTarget) onClose();
      }}
    >
      <div
        className={styles.sheet}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
      >
        <div className={styles.sheetHeader}>
          <h2 id={titleId} className={styles.sheetTitle}>
            {title}
          </h2>
          {onSettingsChange && (
            <button
              type="button"
              className={styles.permissionSummary}
              onClick={() => setShowPermissions((value) => !value)}
              aria-expanded={showPermissions}
            >
              <span>{summary}</span>
              <ChevronRightIcon />
            </button>
          )}
        </div>

        {showPermissions && onSettingsChange && (
          <div className={styles.permissionPanel} role="group" aria-label="Sharing permissions">
            {permissionOptions.map((option) => {
              const selected =
                option.audience === settings.audience &&
                option.permission === settings.permission;
              return (
                <button
                  key={option.id}
                  type="button"
                  className={styles.option}
                  data-selected={selected ? 'true' : undefined}
                  onClick={() => selectPermission(option.audience, option.permission)}
                >
                  <span className={styles.optionLabel}>{option.label}</span>
                  {option.description && (
                    <span className={styles.optionDescription}>{option.description}</span>
                  )}
                </button>
              );
            })}
          </div>
        )}

        <div className={styles.destinations} role="menu" aria-label="Share destinations">
          {destinations.map((destination) => (
            <button
              key={destination.id}
              type="button"
              className={styles.destination}
              role="menuitem"
              onClick={() => {
                destination.onSelect?.();
                onClose();
              }}
            >
              {destination.icon && (
                <span className={styles.destinationIcon}>{destination.icon}</span>
              )}
              <span>{destination.label}</span>
            </button>
          ))}
        </div>

        {footer && <div className={styles.section}>{footer}</div>}
      </div>
    </div>,
    document.body,
  );
}
