// packages/svelte/src/lib/components/Sharing/ShareButton.svelte
<script lang="ts">
  import ShareIcon from './ShareIcon.svelte';
  import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';

  let {
    label = 'Share',
    class: className,
    onclick,
    ...rest
  }: { label?: string; class?: string; onclick?: (event: MouseEvent) => void; [key: string]: unknown } = $props();
</script>

<button type="button" class={[styles.toolbarButton, className].filter(Boolean).join(' ')} aria-label={label} {onclick} {...rest}>
  <ShareIcon />
</button>

// packages/react/src/Sharing/ShareButton.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { ShareIcon } from './icons';
import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';

export interface ShareButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  label?: string;
}

/** Toolbar share control — Apple HIG placement next to document actions. */
export const ShareButton = forwardRef<HTMLButtonElement, ShareButtonProps>(
  ({ label = 'Share', className, ...props }, ref) => (
    <button
      ref={ref}
      type="button"
      className={[styles.toolbarButton, className].filter(Boolean).join(' ')}
      aria-label={label}
      {...props}
    >
      <ShareIcon />
    </button>
  ),
);

ShareButton.displayName = 'ShareButton';
