// packages/svelte/src/lib/components/Sharing/ShareToolbar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { CollaborationAction, Collaborator, ShareDestination, SharePermissionOption, ShareSettings } from '../../Sharing/types';
  import ShareButton from './ShareButton.svelte';
  import ShareSheet from './ShareSheet.svelte';
  import CollaborationButton from './CollaborationButton.svelte';
  import CollaborationPopover from './CollaborationPopover.svelte';
  import LinkIcon from './LinkIcon.svelte';
  import CopyIcon from './CopyIcon.svelte';
  import MessageIcon from './MessageIcon.svelte';
  import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';

  const defaultShareSettings: ShareSettings = { audience: 'invited', permission: 'edit' };
  const defaultDestinations: ShareDestination[] = [
    { id: 'copy-link', label: 'Copy Link', icon: LinkIcon },
    { id: 'copy', label: 'Send Copy', icon: CopyIcon },
    { id: 'messages', label: 'Messages', icon: MessageIcon },
  ];

  let {
    shareTitle = 'Share Document',
    collaborating = false,
    collaborators = [],
    shareSettings = defaultShareSettings,
    onShareSettingsChange,
    destinations = defaultDestinations,
    permissionOptions,
    collaborationActions,
    onManageSharedFile,
    manageLabel,
    onMessage,
    onVideo,
    trailing,
    class: className,
    style,
  }: {
    shareTitle?: string;
    collaborating?: boolean;
    collaborators?: Collaborator[];
    shareSettings?: ShareSettings;
    onShareSettingsChange?: (settings: ShareSettings) => void;
    destinations?: ShareDestination[];
    permissionOptions?: SharePermissionOption[];
    collaborationActions?: CollaborationAction[];
    onManageSharedFile?: () => void;
    manageLabel?: string;
    onMessage?: () => void;
    onVideo?: () => void;
    trailing?: Snippet;
    class?: string;
    style?: string;
  } = $props();

  let shareOpen = $state(false);
  let settings = $state(shareSettings);
</script>

<div class={[styles.toolbar, className].filter(Boolean).join(' ')} {style}>
  <ShareButton onclick={() => (shareOpen = true)} />
  {#if collaborating}
    <CollaborationPopover
      {collaborators}
      actions={collaborationActions}
      {manageLabel}
      onManage={onManageSharedFile}
      {onMessage}
      {onVideo}
    >
      {#snippet trigger()}
        <CollaborationButton {collaborators} />
      {/snippet}
    </CollaborationPopover>
  {/if}
  {@render trailing?.()}
  <ShareSheet open={shareOpen} onClose={() => (shareOpen = false)} title={shareTitle} {settings} onSettingsChange={(next) => { settings = next; onShareSettingsChange?.(next); }} {destinations} {permissionOptions} />
</div>

// packages/react/src/Sharing/ShareToolbar.tsx
import { useState, type CSSProperties, type ReactNode } from 'react';
import { ShareButton } from './ShareButton';
import { ShareSheet } from './ShareSheet';
import { CollaborationButton } from './CollaborationButton';
import { CollaborationPopover } from './CollaborationPopover';
import type {
  CollaborationAction,
  Collaborator,
  ShareDestination,
  SharePermissionOption,
  ShareSettings,
} from './types';
import { CopyIcon, LinkIcon, MessageIcon } from './icons';
import styles from '@larose-ui/styles/components/Sharing/Sharing.module.css';

export interface ShareToolbarProps {
  /** Document or item title shown in the share sheet. */
  shareTitle?: string;
  /** When true, shows the Collaboration button beside Share. */
  collaborating?: boolean;
  collaborators?: Collaborator[];
  shareSettings?: ShareSettings;
  onShareSettingsChange?: (settings: ShareSettings) => void;
  destinations?: ShareDestination[];
  permissionOptions?: SharePermissionOption[];
  collaborationActions?: CollaborationAction[];
  onManageSharedFile?: () => void;
  manageLabel?: string;
  onMessage?: () => void;
  onVideo?: () => void;
  trailing?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

const defaultShareSettings: ShareSettings = {
  audience: 'invited',
  permission: 'edit',
};

const defaultDestinations: ShareDestination[] = [
  { id: 'copy-link', label: 'Copy Link', icon: <LinkIcon /> },
  { id: 'copy', label: 'Send Copy', icon: <CopyIcon /> },
  { id: 'messages', label: 'Messages', icon: <MessageIcon /> },
];

export function ShareToolbar({
  shareTitle = 'Share Document',
  collaborating = false,
  collaborators = [],
  shareSettings = defaultShareSettings,
  onShareSettingsChange,
  destinations = defaultDestinations,
  permissionOptions,
  collaborationActions,
  onManageSharedFile,
  manageLabel,
  onMessage,
  onVideo,
  trailing,
  className,
  style,
}: ShareToolbarProps) {
  const [shareOpen, setShareOpen] = useState(false);
  const [settings, setSettings] = useState(shareSettings);

  const updateSettings = (next: ShareSettings) => {
    setSettings(next);
    onShareSettingsChange?.(next);
  };

  return (
    <div className={[styles.toolbar, className].filter(Boolean).join(' ')} style={style}>
      <ShareButton onClick={() => setShareOpen(true)} />

      {collaborating && (
        <CollaborationPopover
          trigger={<CollaborationButton collaborators={collaborators} />}
          collaborators={collaborators}
          actions={collaborationActions}
          manageLabel={manageLabel}
          onManage={onManageSharedFile}
          onMessage={onMessage}
          onVideo={onVideo}
        />
      )}

      {trailing}

      <ShareSheet
        open={shareOpen}
        onClose={() => setShareOpen(false)}
        title={shareTitle}
        settings={settings}
        onSettingsChange={updateSettings}
        destinations={destinations}
        permissionOptions={permissionOptions}
      />
    </div>
  );
}
