// packages/vue/src/components/Tabs/Tabs.vue
<script setup lang="ts">
import { computed, ref, useId, type CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Tabs/Tabs.module.css';
import { cn } from '../../utils/cn';
import { provideTabs } from './context';

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    defaultValue?: string;
    class?: string;
    style?: CSSProperties;
  }>(),
  { defaultValue: '' },
);

const emit = defineEmits<{ 'update:modelValue': [value: string] }>();
const internal = ref(props.defaultValue);
const current = computed(() => (props.modelValue !== undefined ? props.modelValue : internal.value));
const baseId = useId();

function onValueChange(next: string) {
  if (props.modelValue === undefined) internal.value = next;
  emit('update:modelValue', next);
}

provideTabs({ value: current as any, onValueChange, baseId });
</script>

<template>
  <div :class="cn(styles.tabs, props.class)" :style="props.style">
    <slot />
  </div>
</template>

// packages/svelte/src/lib/components/Tabs/Tabs.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/Tabs/Tabs.module.css';
  import { cn } from '../../utils/cn';
  import { setTabsContext } from './context';

  interface Props {
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    children: Snippet;
    class?: string;
    style?: string;
  }

  let {
    value,
    defaultValue = '',
    onValueChange,
    children,
    class: className,
    style,
  }: Props = $props();

  let internalValue = $state(defaultValue);
  const currentValue = $derived(value !== undefined ? value : internalValue);
  const baseId = `lr-tabs-${Math.random().toString(36).slice(2, 9)}`;

  function handleChange(next: string) {
    if (value === undefined) internalValue = next;
    onValueChange?.(next);
  }

  setTabsContext({
    get value() {
      return currentValue;
    },
    onValueChange: handleChange,
    baseId,
  });
</script>

<div class={cn(styles.tabs, className)} {style}>
  {@render children()}
</div>
