// packages/svelte/src/lib/components/FieldShell/FieldShell.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { UIState } from '@larose-ui/core';
  import styles from '@larose-ui/styles/components/DataEntry/FieldShell.module.css';

  interface Props {
    label?: string;
    hint?: string;
    error?: string | null;
    required?: boolean;
    htmlFor?: string;
    uiState?: UIState;
    children: Snippet;
  }

  let {
    label,
    hint,
    error = null,
    required = false,
    htmlFor,
    uiState = 'idle',
    children,
  }: Props = $props();
</script>

<div class={styles.wrapper} data-state={uiState}>
  {#if label}
    <label for={htmlFor} class={styles.label}>
      {label}
      {#if required}
        <span class={styles.required} aria-hidden="true">*</span>
        <span class={styles.srOnly}>(required)</span>
      {/if}
    </label>
  {/if}
  {@render children()}
  {#if hint && !error}
    <span id={htmlFor ? `${htmlFor}-hint` : undefined} class={styles.hint}>{hint}</span>
  {/if}
  {#if error}
    <span id={htmlFor ? `${htmlFor}-error` : undefined} class={styles.error} role="alert">
      {error}
    </span>
  {/if}
</div>

// packages/react/src/DataEntry/FieldShell.tsx
import type { ReactNode } from 'react';
import type { UIState } from '@larose-ui/core';
import styles from '@larose-ui/styles/components/DataEntry/FieldShell.module.css';

export interface FieldShellProps {
  label?: string;
  hint?: string;
  error?: string | null;
  required?: boolean;
  htmlFor?: string;
  uiState?: UIState;
  children: ReactNode;
}

export function FieldShell({
  label,
  hint,
  error = null,
  required = false,
  htmlFor,
  uiState = 'idle',
  children,
}: FieldShellProps) {
  const errorMessage = typeof error === 'string' ? error : null;

  return (
    <div className={styles.wrapper} data-state={uiState}>
      {label && (
        <label htmlFor={htmlFor} className={styles.label}>
          {label}
          {required && (
            <>
              <span className={styles.required} aria-hidden="true">
                *
              </span>
              <span className={styles.srOnly}>(required)</span>
            </>
          )}
        </label>
      )}
      {children}
      {hint && !errorMessage && (
        <span id={htmlFor ? `${htmlFor}-hint` : undefined} className={styles.hint}>
          {hint}
        </span>
      )}
      {errorMessage && (
        <span id={htmlFor ? `${htmlFor}-error` : undefined} className={styles.error} role="alert">
          {errorMessage}
        </span>
      )}
    </div>
  );
}
