// packages/vue/src/components/Dialog/Dialog.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/Dialog/Dialog.module.css';
import Modal from '../Modal/Modal.vue';
import Button from '../Button/Button.vue';

const props = withDefaults(
  defineProps<{
    open: boolean;
    title: string;
    description?: string;
    confirmLabel?: string;
    cancelLabel?: string;
    loading?: boolean;
    variant?: 'default' | 'destructive';
    showConfirm?: boolean;
  }>(),
  {
    confirmLabel: 'Confirm',
    cancelLabel: 'Cancel',
    variant: 'default',
    showConfirm: true,
  },
);

const emit = defineEmits<{
  close: [];
  confirm: [];
}>();
</script>

<template>
  <Modal :open="open" :title="title" :description="description" @close="emit('close')">
    <div v-if="$slots.default" :class="styles.body">
      <slot />
    </div>
    <div :class="styles.actions">
      <Button
        button-role="cancel"
        variant="secondary"
        :disabled="loading"
        @click="emit('close')"
      >
        {{ cancelLabel }}
      </Button>
      <Button
        v-if="showConfirm"
        :variant="variant === 'destructive' ? 'ghost' : 'primary'"
        :button-role="variant === 'destructive' ? 'destructive' : 'primary'"
        :loading="loading"
        @click="emit('confirm')"
      >
        {{ confirmLabel }}
      </Button>
    </div>
  </Modal>
</template>

// packages/react/src/Dialog/Dialog.tsx
import type { ReactNode } from 'react';
import { Button } from '../Button/Button';
import { Modal } from '../Modal/Modal';
import styles from '@larose-ui/styles/components/Dialog/Dialog.module.css';

export interface DialogProps {
  open: boolean;
  onClose: () => void;
  title: string;
  description?: string;
  children?: ReactNode;
  confirmLabel?: string;
  cancelLabel?: string;
  onConfirm?: () => void;
  loading?: boolean;
  variant?: 'default' | 'destructive';
}

export function Dialog({
  open,
  onClose,
  title,
  description,
  children,
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  onConfirm,
  loading,
  variant = 'default',
}: DialogProps) {
  return (
    <Modal open={open} onClose={onClose} title={title} description={description}>
      {children && <div className={styles.body}>{children}</div>}
      <div className={styles.actions}>
        <Button buttonRole="cancel" variant="secondary" onClick={onClose} disabled={loading}>
          {cancelLabel}
        </Button>
        {onConfirm && (
          <Button
            variant={variant === 'destructive' ? 'ghost' : 'primary'}
            buttonRole={variant === 'destructive' ? 'destructive' : 'primary'}
            onClick={onConfirm}
            loading={loading}
          >
            {confirmLabel}
          </Button>
        )}
      </div>
    </Modal>
  );
}
