// packages/svelte/src/lib/components/EmptyState/EmptyState.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { UIState } from '@larose-ui/core';
  import styles from '@larose-ui/styles/components/EmptyState/EmptyState.module.css';
  import Button from '../Button/Button.svelte';
  import { cn } from '../../utils/cn';

  interface Props {
    title: string;
    description?: string;
    icon?: Snippet;
    actionLabel?: string;
    onAction?: () => void;
    state?: UIState;
    class?: string;
    style?: string;
  }

  let {
    title,
    description,
    icon,
    actionLabel,
    onAction,
    state = 'empty',
    class: className,
    style,
  }: Props = $props();
</script>

<div class={cn(styles.empty, className)} {style} data-state={state} role="status">
  {#if icon}
    <div class={styles.icon}>{@render icon()}</div>
  {/if}
  <h3 class={styles.title}>{title}</h3>
  {#if description}
    <p class={styles.description}>{description}</p>
  {/if}
  {#if actionLabel && onAction}
    <div class={styles.action}>
      <Button variant="primary" onclick={onAction}>{actionLabel}</Button>
    </div>
  {/if}
</div>

// packages/react/src/EmptyState/EmptyState.tsx
import type { ReactNode } from 'react';
import type { UIState } from '@larose-ui/core';
import { Button } from '../Button/Button';
import styles from '@larose-ui/styles/components/EmptyState/EmptyState.module.css';

export interface EmptyStateProps {
  title: string;
  description?: string;
  icon?: ReactNode;
  actionLabel?: string;
  onAction?: () => void;
  state?: UIState;
}

export function EmptyState({
  title,
  description,
  icon,
  actionLabel,
  onAction,
  state = 'empty',
}: EmptyStateProps) {
  return (
    <div className={styles.empty} data-state={state} role="status">
      {icon && <div className={styles.icon}>{icon}</div>}
      <h3 className={styles.title}>{title}</h3>
      {description && <p className={styles.description}>{description}</p>}
      {actionLabel && onAction && (
        <div className={styles.action}>
          <Button variant="primary" onClick={onAction}>
            {actionLabel}
          </Button>
        </div>
      )}
    </div>
  );
}
