// packages/vue/src/components/DockMenu/DockBar.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/DockMenu/DockMenu.module.css';
import { cn } from '../../utils/cn';

defineProps<{
  class?: string;
  style?: CSSProperties;
  'aria-label'?: string;
}>();
</script>

<template>
  <div
    :class="cn(styles.dockBar, $props.class)"
    :style="$props.style"
    role="toolbar"
    :aria-label="$props['aria-label'] ?? 'Dock'"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/lib/components/DockMenu/DockBar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from '@larose-ui/styles/components/DockMenu/DockMenu.module.css';
  import { cn } from '../../utils/cn';

  let {
    children,
    class: className,
    style,
    'aria-label': ariaLabel = 'Dock',
  }: {
    children?: Snippet;
    class?: string;
    style?: string;
    'aria-label'?: string;
  } = $props();
</script>

<div class={cn(styles.dockBar, className)} {style} role="toolbar" aria-label={ariaLabel}>
  {#if children}{@render children()}{/if}
</div>
