// packages/svelte/src/lib/components/Lockup/Poster.svelte
<script lang="ts">
  import styles from '@larose-ui/styles/components/Lockup/Lockup.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    title: string;
    subtitle?: string;
    imageUrl: string;
    class?: string;
    style?: string;
  }

  let { title, subtitle, imageUrl, class: className, style }: Props = $props();
</script>

<figure class={cn(styles.posterFrame, className)} {style}>
  <img src={imageUrl} alt={title} class={styles.posterImage} />
  <figcaption class={styles.posterMeta}>
    <div class={styles.posterTitle}>{title}</div>
    {#if subtitle}<div class={styles.posterSubtitle}>{subtitle}</div>{/if}
  </figcaption>
</figure>

// packages/vue/src/components/Lockup/Poster.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/Lockup/Lockup.module.css';
import { cn } from '../../utils/cn';

defineProps<{
  title: string;
  subtitle?: string;
  imageUrl: string;
  class?: string;
  style?: CSSProperties;
}>();
</script>

<template>
  <figure :class="cn(styles.posterFrame, $props.class)" :style="$props.style">
    <img :src="imageUrl" :alt="title" :class="styles.posterImage" />
    <figcaption :class="styles.posterMeta">
      <div :class="styles.posterTitle">{{ title }}</div>
      <div v-if="subtitle" :class="styles.posterSubtitle">{{ subtitle }}</div>
    </figcaption>
  </figure>
</template>
