// packages/svelte/src/lib/components/WebView/WebView.svelte
<script lang="ts">
  import styles from '@larose-ui/styles/components/WebView/WebView.module.css';
  import { cn } from '../../utils/cn';

  interface Props {
    src: string;
    title?: string;
    class?: string;
    style?: string;
    sandbox?: string;
  }

  let {
    src,
    title = 'Web view',
    class: className,
    style,
    sandbox = 'allow-scripts allow-same-origin allow-forms',
  }: Props = $props();
</script>

<iframe {src} {title} class={cn(styles.frameOnly, className)} {style} {sandbox}></iframe>

// packages/vue/src/components/WebView/WebView.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/WebView/WebView.module.css';
import { cn } from '../../utils/cn';

defineProps<{
  src: string;
  title?: string;
  class?: string;
  style?: CSSProperties;
  sandbox?: string;
}>();
</script>

<template>
  <iframe
    :src="src"
    :title="title ?? 'Web view'"
    :class="cn(styles.frameOnly, $props.class)"
    :style="$props.style"
    :sandbox="sandbox ?? 'allow-scripts allow-same-origin allow-forms'"
  />
</template>
