// packages/permissions-vue/src/PermissionProvider.vue
<script setup lang="ts">
import { watch } from 'vue';
import type { AbacContext } from '@larose-ui/permissions-core';
import {
  createPermissionStore,
  providePermissions,
  syncPermissionStore,
} from './context';

const props = withDefaults(
  defineProps<{
    permissions?: string[];
    loading?: boolean;
    context?: AbacContext;
  }>(),
  {
    permissions: () => [],
    loading: false,
    context: () => ({}),
  },
);

const store = createPermissionStore({
  permissions: props.permissions,
  loading: props.loading,
  context: props.context,
});
providePermissions(store);

watch(
  () => [props.permissions, props.loading, props.context] as const,
  () => {
    syncPermissionStore(store, {
      permissions: props.permissions,
      loading: props.loading,
      context: props.context,
    });
  },
  { deep: true },
);
</script>

<template>
  <slot />
</template>

// packages/permissions-svelte/src/PermissionProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { AbacContext } from '@larose-ui/permissions-core';
  import { createPermissionsContext, setPermissionsContext } from './context';

  interface Props {
    permissions?: string[];
    loading?: boolean;
    context?: AbacContext;
    children: Snippet;
  }

  let {
    permissions = [],
    loading = false,
    context = {},
    children,
  }: Props = $props();

  const store = createPermissionsContext({ permissions, loading, context });
  setPermissionsContext(store);

  $effect(() => {
    store.set({ permissions, loading, context });
  });
</script>

{@render children()}
