// apps/sandbox-svelte/src/scenarios/ToastInner.svelte
<script lang="ts">
  import { getToast } from '@larose-ui/runtime-svelte/toast';

  const { toast } = getToast();
</script>

<div class="sbx-stage-pad sbx-stack">
  <p class="sbx-muted">Triggers a success toast via the runtime toast provider.</p>
  <button
    type="button"
    data-sbx="show-toast"
    onclick={() => toast({ title: 'Saved', message: 'Toast parity check.', variant: 'success' })}
  >
    Show toast
  </button>
</div>

// apps/sandbox-vue/src/scenarios/ToastInner.vue
<script setup lang="ts">
import { useToast } from '@larose-ui/runtime-vue/toast';

const { toast } = useToast();
</script>

<template>
  <div class="sbx-stage-pad sbx-stack">
    <p class="sbx-muted">Triggers a success toast via the runtime toast provider.</p>
    <button
      type="button"
      data-sbx="show-toast"
      @click="toast({ title: 'Saved', message: 'Toast parity check.', variant: 'success' })"
    >
      Show toast
    </button>
  </div>
</template>
