// packages/vue/src/components/SplitView/SplitViewToolbar.vue
<script setup lang="ts">
import styles from '@larose-ui/styles/components/SplitView/SplitView.module.css';
import { cn } from '../../utils/cn';
import { useSplitView } from '../../composables/useSplitView';

defineProps<{
  class?: string;
  style?: Record<string, string | number>;
}>();

const { hiddenPanes, showPane } = useSplitView();
</script>

<template>
  <div
    v-if="$slots.actions || hiddenPanes.length > 0"
    :class="cn(styles.toolbar, $props.class)"
    :style="$props.style"
    role="toolbar"
    aria-label="Split view toolbar"
  >
    <slot name="actions" />
    <button
      v-for="pane in hiddenPanes"
      :key="pane.id"
      type="button"
      :class="styles.toolbarButton"
      @click="showPane(pane.id)"
    >
      Show {{ pane.label }}
    </button>
  </div>
</template>

// packages/react/src/SplitView/SplitViewToolbar.tsx
import { useSplitView } from './SplitView';
import type { ReactNode } from 'react';
import styles from '@larose-ui/styles/components/SplitView/SplitView.module.css';

export interface SplitViewToolbarProps {
  /** Optional actions rendered before pane restore buttons. */
  actions?: ReactNode;
}

/** Toolbar with buttons to reveal hidden split view panes. */
export function SplitViewToolbar({ actions }: SplitViewToolbarProps) {
  const { hiddenPanes, showPane } = useSplitView();

  if (!actions && hiddenPanes.length === 0) return null;

  return (
    <div className={styles.toolbar} role="toolbar" aria-label="Split view toolbar">
      {actions}
      {hiddenPanes.map((pane) => (
        <button
          key={pane.id}
          type="button"
          className={styles.toolbarButton}
          onClick={() => showPane(pane.id)}
        >
          Show {pane.label}
        </button>
      ))}
    </div>
  );
}
