// packages/vue/src/components/ImageView/ImageView.vue
<script setup lang="ts">
import { onUnmounted, ref, watch, type CSSProperties } from 'vue';
import styles from '@larose-ui/styles/components/ImageView/ImageView.module.css';
import { cn } from '../../utils/cn';
import type { ImageBackground, ImageFit, ImageFrameSequence } from '../../ImageView/types';
import { nextFrameIndex, sequenceInterval } from '../../ImageView/utils';

const props = withDefaults(
  defineProps<{
    src?: string;
    alt: string;
    fit?: ImageFit;
    objectPosition?: string;
    background?: ImageBackground;
    sequence?: ImageFrameSequence;
    class?: string;
    style?: CSSProperties;
    frameClass?: string;
    frameStyle?: CSSProperties;
  }>(),
  { fit: 'contain', objectPosition: 'center', background: 'opaque' },
);

const frameIndex = ref(0);
let timer: number | undefined;

watch(
  () => props.sequence,
  (sequence) => {
    if (timer) window.clearInterval(timer);
    frameIndex.value = 0;
    if (!sequence?.frames.length) return;
    timer = window.setInterval(() => {
      frameIndex.value = nextFrameIndex(frameIndex.value, sequence.frames.length);
    }, sequenceInterval(sequence));
  },
  { immediate: true },
);

onUnmounted(() => {
  if (timer) window.clearInterval(timer);
});

const activeSrc = () =>
  props.sequence?.frames.length ? props.sequence.frames[frameIndex.value] : props.src;
</script>

<template>
  <div
    v-if="activeSrc()"
    :class="cn(styles.frame, frameClass)"
    :style="frameStyle"
    :data-background="background"
  >
    <img
      :src="activeSrc()"
      :alt="alt"
      :class="cn(styles.image, props.class)"
      :style="{ objectFit: fit, objectPosition, ...(($props.style as object) ?? {}) }"
    />
  </div>
</template>

// packages/react/src/ImageView/ImageView.tsx
import { useEffect, useState, type CSSProperties, type ImgHTMLAttributes } from 'react';
import type { ImageBackground, ImageFit, ImageFrameSequence } from './types';
import { nextFrameIndex, sequenceInterval } from './utils';
import styles from '@larose-ui/styles/components/ImageView/ImageView.module.css';

export interface ImageViewProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src'> {
  src?: string;
  alt: string;
  fit?: ImageFit;
  objectPosition?: string;
  background?: ImageBackground;
  /** Animated image sequence — frames should share dimensions when possible. */
  sequence?: ImageFrameSequence;
  frameClassName?: string;
  frameStyle?: CSSProperties;
}

const fitMap: Record<ImageFit, CSSProperties['objectFit']> = {
  fill: 'fill',
  contain: 'contain',
  cover: 'cover',
  'scale-down': 'scale-down',
  none: 'none',
};

/**
 * Non-interactive image display with Apple HIG fit modes.
 * @see https://developer.apple.com/design/human-interface-guidelines/image-views
 */
export function ImageView({
  src,
  alt,
  fit = 'contain',
  objectPosition = 'center',
  background = 'opaque',
  sequence,
  className,
  frameClassName,
  frameStyle,
  style,
  ...props
}: ImageViewProps) {
  const [frameIndex, setFrameIndex] = useState(0);
  const activeSrc = sequence?.frames.length
    ? sequence.frames[frameIndex]
    : src;

  useEffect(() => {
    if (!sequence?.frames.length) return;
    const timer = window.setInterval(() => {
      setFrameIndex((current) => nextFrameIndex(current, sequence.frames.length));
    }, sequenceInterval(sequence));
    return () => window.clearInterval(timer);
  }, [sequence]);

  if (!activeSrc) return null;

  return (
    <div
      className={[styles.frame, frameClassName].filter(Boolean).join(' ')}
      data-background={background}
      style={frameStyle}
    >
      <img
        src={activeSrc}
        alt={alt}
        className={[styles.image, className].filter(Boolean).join(' ')}
        style={{
          objectFit: fitMap[fit],
          objectPosition,
          ...style,
        }}
        {...props}
      />
    </div>
  );
}
