// packages/runtime-svelte/src/toast/OptionalToastProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { ToastProvider } from '@larose-ui/svelte';

  interface Props {
    enabled?: boolean;
    placement?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
    children?: Snippet;
  }

  let {
    enabled = true,
    placement = 'bottom-right',
    children,
  }: Props = $props();
</script>

{#if enabled}
  <ToastProvider {placement}>
    {@render children?.()}
  </ToastProvider>
{:else}
  {@render children?.()}
{/if}

// packages/runtime-vue/src/toast/OptionalToastProvider.vue
<script setup lang="ts">
/**
 * Optional toast wrapper — keeps toast host behind enableToasts without duplicating the platform tree.
 */
import { ToastProvider } from '@larose-ui/vue';

withDefaults(
  defineProps<{
    enabled?: boolean;
    placement?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
  }>(),
  {
    enabled: true,
    placement: 'bottom-right',
  },
);
</script>

<template>
  <ToastProvider v-if="enabled" :placement="placement">
    <slot />
  </ToastProvider>
  <slot v-else />
</template>
