// packages/runtime/src/toast/OptionalToastProvider.tsx
import { lazy, Suspense, type ReactNode } from 'react';

export interface OptionalToastProviderProps {
  children: ReactNode;
  enabled?: boolean;
  placement?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
}

const LazyToastProvider = lazy(async () => {
  const mod = await import('@larose/react');
  return { default: mod.ToastProvider };
});

/**
 * Opt-in toast wrapper — keeps @larose/react out of the default runtime bundle.
 * Used internally by LaRoseProvider when enableToasts is true.
 */
export function OptionalToastProvider({
  children,
  enabled = true,
  placement = 'bottom-right',
}: OptionalToastProviderProps) {
  if (!enabled) return <>{children}</>;

  return (
    <Suspense fallback={children}>
      <LazyToastProvider placement={placement}>{children}</LazyToastProvider>
    </Suspense>
  );
}

// packages/runtime-vue/src/toast/OptionalToastProvider.vue
<script setup lang="ts">
/**
 * Optional toast wrapper — keeps toast host behind enableToasts without duplicating the platform tree.
 */
import { ToastProvider } from '@larose-ui/vue';

withDefaults(
  defineProps<{
    enabled?: boolean;
    placement?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
  }>(),
  {
    enabled: true,
    placement: 'bottom-right',
  },
);
</script>

<template>
  <ToastProvider v-if="enabled" :placement="placement">
    <slot />
  </ToastProvider>
  <slot v-else />
</template>
