// packages/runtime/src/LaRoseProvider.tsx
import { useEffect, useMemo, type ReactNode } from 'react';
import type {
  Density,
  Environment,
  FeatureFlagEvaluator,
  SessionState,
  ThemeMode,
  UserContext,
  TenantContext,
} from '@larose-ui/core';
import { LAROSE_VERSION } from '@larose-ui/core';
import type { ColorTokens } from '@larose-ui/tokens';
import {
  MotionProvider,
  ThemeCustomizationContext,
  type MotionConfig,
  type ThemeCustomizationContextValue,
} from '@larose-ui/react';
import { getThemePreset, type ThemePresetId } from '@larose-ui/themes';
import type { ComponentConfiguration, LaRoseTheme, LaRoseThemeInput } from '@larose-ui/themes';
import { createTheme, resolveTheme } from '@larose-ui/themes';
import { PermissionProvider } from '@larose-ui/permissions';
import {
  ObservabilityProvider,
  createConsoleAdapter,
  createNoopAdapter,
  type ObservabilityAdapter,
} from '@larose-ui/observability';
import type { Locale } from './i18n/messages';
import { EnvironmentProvider } from './environment/EnvironmentProvider';
import { FeatureFlagProvider, type FeatureState } from './features/FeatureFlagProvider';
import { I18nProvider } from './i18n/I18nProvider';
import { NetworkProvider } from './network/NetworkProvider';
import { OfflineProvider } from './offline/OfflineProvider';
import { ResponsiveProvider } from './responsive/ResponsiveProvider';
import { ThemeProvider, type Appearance } from './theme/ThemeProvider';
import { useNetwork } from './network/NetworkProvider';
import { useOffline } from './offline/OfflineProvider';
import { RuntimeContextProvider } from './runtime/RuntimeContextProvider';
import { RuntimeBridge, SessionBridge } from './runtime/RuntimeBridge';
import { RuntimeObservabilityBridge } from './observability/RuntimeObservabilityBridge';
import type { RuntimeEvent } from './runtime/RuntimeContextProvider';
import { resolveTenantConfig } from './tenant/resolveTenant';
import { OptionalToastProvider } from './toast/OptionalToastProvider';
import {
  shouldSyncOfflineQueue,
} from './runtime/sessionSecurity';

export interface LaRoseProviderProps {
  children: ReactNode;
  theme?: ThemeMode;
  /** Resolves light/dark from system when set to `system`. Defaults to Apple-inspired tokens. */
  appearance?: Appearance;
  density?: Density;
  /** Brand color preset. `refined` (Apple-inspired) is the default token set. */
  themePreset?: 'refined' | ThemePresetId;
  tenantId?: string;
  tenant?: TenantContext;
  brandColors?: Partial<ColorTokens>;
  locale?: Locale;
  timezone?: string;
  environment?: Environment;
  permissions?: string[];
  permissionsLoading?: boolean;
  features?: Record<string, FeatureState>;
  featuresLoading?: boolean;
  featureFlagEvaluator?: FeatureFlagEvaluator;
  featureNames?: string[];
  observabilityAdapter?: ObservabilityAdapter;
  observabilityDebug?: boolean;
  userId?: string;
  user?: UserContext;
  session?: SessionState;
  version?: {
    frontend?: string;
    api?: string;
    feature?: string;
    compatible?: boolean;
    warnings?: string[];
  };
  onRuntimeEvent?: (event: RuntimeEvent) => void;
  enableToasts?: boolean;
  toastPlacement?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
  /** Global motion configuration for laRose UI components. */
  motion?: MotionConfig;
  /** Full theme configuration with token overrides. */
  themeConfig?: LaRoseThemeInput | LaRoseTheme;
  /** Per-component defaults, tokens, and motion overrides. */
  components?: ComponentConfiguration;
}

function AutoSync({
  children,
  session,
}: {
  children: ReactNode;
  session?: SessionState;
}) {
  const network = useNetwork();
  const offline = useOffline();

  useEffect(() => {
    if (!shouldSyncOfflineQueue(session)) return;
    if (network.online && offline.queue.length > 0) {
      void offline.sync(async (request) => {
        const response = await fetch(request.url, {
          method: request.method,
          headers: {
            'Content-Type': 'application/json',
            ...request.headers,
          },
          body: request.body ? JSON.stringify(request.body) : undefined,
        });
        if (!response.ok) {
          throw new Error(`${response.status} ${response.statusText}`);
        }
      });
    }
  }, [network.online, offline.queue.length, offline.sync, session]);

  return <>{children}</>;
}

export function LaRoseProvider({
  children,
  theme,
  appearance = 'system',
  themePreset = 'refined',
  density = 'comfortable',
  tenantId,
  tenant,
  brandColors: brandColorsProp,
  locale = 'en',
  timezone,
  environment = 'development',
  permissions = [],
  permissionsLoading = false,
  features = {},
  featuresLoading = false,
  featureFlagEvaluator,
  featureNames,
  observabilityAdapter,
  observabilityDebug,
  userId,
  user,
  session,
  version,
  onRuntimeEvent,
  enableToasts = true,
  toastPlacement = 'bottom-right',
  motion,
  themeConfig,
  components = {},
}: LaRoseProviderProps) {
  const adapter =
    observabilityAdapter ??
    (observabilityDebug ? createConsoleAdapter() : createNoopAdapter());

  const presetBrandColors =
    themePreset !== 'refined' ? getThemePreset(themePreset).colors : undefined;

  const brandColors = {
    ...presetBrandColors,
    ...brandColorsProp,
    ...(tenant?.brandColors as Partial<ColorTokens> | undefined),
  };

  const normalizedTheme = useMemo(
    () =>
      themeConfig
        ? 'tokens' in themeConfig && themeConfig.tokens
          ? (themeConfig as LaRoseTheme)
          : createTheme({ preset: themePreset, ...themeConfig })
        : createTheme({ preset: themePreset }),
    [themeConfig, themePreset],
  );

  const resolvedTheme = useMemo(
    () =>
      resolveTheme({
        theme: normalizedTheme,
        density,
        brandColors,
        components,
      }),
    [normalizedTheme, density, brandColors, components],
  );

  const customizationValue = useMemo<ThemeCustomizationContextValue>(
    () => ({
      theme: normalizedTheme,
      resolved: resolvedTheme,
      components,
    }),
    [normalizedTheme, resolvedTheme, components],
  );

  const resolved = resolveTenantConfig({
    tenant,
    tenantId,
    theme,
    density,
    brandColors,
    locale,
    timezone,
    permissions,
    features,
  });

  const resolvedTenantId = resolved.tenantId;
  const resolvedUserId = userId ?? user?.id;
  const offlineScopeId = useMemo(() => {
    const parts = [resolvedTenantId, resolvedUserId].filter(Boolean);
    return parts.length > 0 ? parts.join(':') : undefined;
  }, [resolvedTenantId, resolvedUserId]);
  const resolvedVersion = {
    frontend: version?.frontend ?? LAROSE_VERSION,
    api: version?.api,
    feature: version?.feature,
    compatible: version?.compatible ?? true,
    warnings: version?.warnings ?? [],
  };

  const tree = (
    <ThemeCustomizationContext.Provider value={customizationValue}>
      <RuntimeContextProvider
      initialContext={{
        environment,
        session: session ?? (user || userId ? 'authenticated' : 'unauthenticated'),
        timezone: resolved.timezone,
        version: resolvedVersion,
      }}
      onEvent={onRuntimeEvent}
    >
      <ThemeProvider
        theme={resolved.theme}
        appearance={appearance}
        density={resolved.density}
        tenantId={resolvedTenantId}
        brandColors={resolved.brandColors}
        themeConfig={normalizedTheme}
        themePreset={themePreset}
        components={components}
      >
        <ObservabilityProvider
          adapter={adapter}
          tenantId={resolvedTenantId}
          userId={userId ?? user?.id}
          debug={observabilityDebug}
        >
          <I18nProvider locale={resolved.locale}>
            <PermissionProvider
              permissions={resolved.permissions}
              loading={permissionsLoading}
              context={{ userId: userId ?? user?.id, tenantId: resolvedTenantId }}
            >
              <FeatureFlagProvider features={resolved.features} loading={featuresLoading}>
                <EnvironmentProvider environment={environment}>
                  <ResponsiveProvider>
                    <NetworkProvider>
                      <OfflineProvider scopeId={offlineScopeId}>
                        <AutoSync session={session}>
                          <RuntimeBridge
                            userId={userId}
                            user={user}
                            tenant={resolved.tenant ?? tenant}
                            tenantId={tenantId}
                            timezone={resolved.timezone}
                            session={session}
                            features={resolved.features}
                            featuresLoading={featuresLoading}
                            version={resolvedVersion}
                            featureFlagEvaluator={featureFlagEvaluator}
                            featureNames={
                              featureNames ?? Object.keys(resolved.features)
                            }
                          />
                          <RuntimeObservabilityBridge />
                          <SessionBridge />
                          {children}
                        </AutoSync>
                      </OfflineProvider>
                    </NetworkProvider>
                  </ResponsiveProvider>
                </EnvironmentProvider>
              </FeatureFlagProvider>
            </PermissionProvider>
          </I18nProvider>
        </ObservabilityProvider>
      </ThemeProvider>
    </RuntimeContextProvider>
    </ThemeCustomizationContext.Provider>
  );

  if (!enableToasts) {
    return <MotionProvider {...motion}>{tree}</MotionProvider>;
  }

  return (
    <MotionProvider {...motion}>
      <OptionalToastProvider enabled placement={toastPlacement}>
        {tree}
      </OptionalToastProvider>
    </MotionProvider>
  );
}

// packages/runtime-svelte/src/LaRoseProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type {
    Density,
    Environment,
    SessionState,
    ThemeMode,
    UserContext,
    TenantContext,
  } from '@larose-ui/core';
  import { LAROSE_VERSION } from '@larose-ui/core';
  import type { ColorTokens } from '@larose-ui/tokens';
  import {
    createTheme,
    getThemePreset,
    type ComponentConfiguration,
    type LaRoseTheme,
    type LaRoseThemeInput,
    type ThemePresetId,
  } from '@larose-ui/themes';
  import type { FeatureState, Locale } from '@larose-ui/runtime-core';
  import { resolveTenantConfig } from '@larose-ui/runtime-core';
  import {
    ObservabilityProvider,
    createConsoleAdapter,
    createNoopAdapter,
    type ObservabilityAdapter,
  } from '@larose-ui/observability-svelte';
  import { PermissionProvider } from '@larose-ui/permissions-svelte';
  import {
    LaRoseProvider as ThemeShell,
    AcceleratorProvider,
  } from '@larose-ui/svelte';
  import EnvironmentProvider from './environment/EnvironmentProvider.svelte';
  import FeatureFlagProvider from './features/FeatureFlagProvider.svelte';
  import I18nProvider from './i18n/I18nProvider.svelte';
  import NetworkProvider from './network/NetworkProvider.svelte';
  import OfflineProvider from './offline/OfflineProvider.svelte';
  import ResponsiveProvider from './responsive/ResponsiveProvider.svelte';
  import RuntimeProvider from './runtime/RuntimeProvider.svelte';
  import AutoSync from './runtime/AutoSync.svelte';
  import OptionalToastProvider from './toast/OptionalToastProvider.svelte';

  export type Appearance = 'light' | 'dark' | 'system';

  interface Props {
    theme?: ThemeMode;
    appearance?: Appearance;
    density?: Density;
    themePreset?: 'refined' | ThemePresetId;
    tenantId?: string;
    tenant?: TenantContext;
    brandColors?: Partial<ColorTokens>;
    locale?: Locale;
    timezone?: string;
    environment?: Environment;
    permissions?: string[];
    permissionsLoading?: boolean;
    features?: Record<string, FeatureState>;
    featuresLoading?: boolean;
    observabilityAdapter?: ObservabilityAdapter;
    observabilityDebug?: boolean;
    userId?: string;
    user?: UserContext;
    session?: SessionState;
    version?: {
      frontend?: string;
      api?: string;
      feature?: string;
      compatible?: boolean;
      warnings?: string[];
    };
    enableToasts?: boolean;
    toastPlacement?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
    themeConfig?: LaRoseThemeInput | LaRoseTheme;
    components?: ComponentConfiguration;
    children?: Snippet;
  }

  let {
    theme,
    appearance = 'system',
    density = 'comfortable',
    themePreset = 'refined',
    tenantId,
    tenant,
    brandColors: brandColorsProp,
    locale = 'en',
    timezone,
    environment = 'development',
    permissions = [],
    permissionsLoading = false,
    features = {},
    featuresLoading = false,
    observabilityAdapter,
    observabilityDebug,
    userId,
    user,
    session,
    version,
    enableToasts = true,
    toastPlacement = 'bottom-right',
    themeConfig,
    components = {},
    children,
  }: Props = $props();

  function resolveAppearanceTheme(value: Appearance): ThemeMode {
    if (value === 'system') {
      if (
        typeof window !== 'undefined' &&
        typeof window.matchMedia === 'function' &&
        window.matchMedia('(prefers-color-scheme: dark)').matches
      ) {
        return 'dark';
      }
      return 'light';
    }
    return value;
  }

  let systemTheme = $state<ThemeMode>(resolveAppearanceTheme(appearance));

  $effect(() => {
    if (appearance !== 'system' || typeof window === 'undefined') return;
    if (typeof window.matchMedia !== 'function') return;
    const media = window.matchMedia('(prefers-color-scheme: dark)');
    const update = () => {
      systemTheme = media.matches ? 'dark' : 'light';
    };
    update();
    media.addEventListener('change', update);
    return () => media.removeEventListener('change', update);
  });

  const activeTheme = $derived(
    theme ?? (appearance === 'system' ? systemTheme : resolveAppearanceTheme(appearance)),
  );

  const adapter = $derived(
    observabilityAdapter ?? (observabilityDebug ? createConsoleAdapter() : createNoopAdapter()),
  );

  const brandColors = $derived({
    ...(themePreset !== 'refined' ? getThemePreset(themePreset).colors : undefined),
    ...brandColorsProp,
    ...(tenant?.brandColors as Partial<ColorTokens> | undefined),
  });

  const normalizedTheme = $derived(
    themeConfig
      ? 'tokens' in themeConfig && themeConfig.tokens
        ? (themeConfig as LaRoseTheme)
        : createTheme({ preset: themePreset, ...themeConfig })
      : createTheme({ preset: themePreset }),
  );

  const resolvedTenant = $derived(
    resolveTenantConfig({
      tenant,
      tenantId,
      theme: activeTheme,
      density,
      brandColors,
      locale,
      timezone,
      permissions,
      features,
    }),
  );

  const offlineScopeId = $derived.by(() => {
    const parts = [resolvedTenant.tenantId, userId ?? user?.id].filter(Boolean);
    return parts.length > 0 ? parts.join(':') : undefined;
  });

  const initialRuntimeContext = $derived({
    environment,
    session: session ?? (user || userId ? ('authenticated' as const) : ('unauthenticated' as const)),
    timezone: resolvedTenant.timezone,
    version: {
      frontend: version?.frontend ?? LAROSE_VERSION,
      api: version?.api,
      feature: version?.feature,
      compatible: version?.compatible ?? true,
      warnings: version?.warnings ?? [],
    },
  });
</script>

<ThemeShell
  theme={resolvedTenant.theme}
  density={resolvedTenant.density}
  tenantId={resolvedTenant.tenantId}
  brandColors={resolvedTenant.brandColors}
  themeConfig={normalizedTheme}
  {components}
>
  <AcceleratorProvider>
    <OptionalToastProvider enabled={enableToasts} placement={toastPlacement}>
      <ObservabilityProvider
        adapter={adapter}
        tenantId={resolvedTenant.tenantId}
        userId={userId ?? user?.id}
        debug={observabilityDebug}
      >
        <I18nProvider locale={resolvedTenant.locale}>
          <PermissionProvider
            permissions={resolvedTenant.permissions}
            loading={permissionsLoading}
            context={{ userId: userId ?? user?.id, tenantId: resolvedTenant.tenantId }}
          >
            <FeatureFlagProvider features={resolvedTenant.features} loading={featuresLoading}>
              <EnvironmentProvider {environment}>
                <ResponsiveProvider>
                  <NetworkProvider>
                    <OfflineProvider scopeId={offlineScopeId}>
                      <AutoSync {session}>
                        <RuntimeProvider initialContext={initialRuntimeContext}>
                          {@render children?.()}
                        </RuntimeProvider>
                      </AutoSync>
                    </OfflineProvider>
                  </NetworkProvider>
                </ResponsiveProvider>
              </EnvironmentProvider>
            </FeatureFlagProvider>
          </PermissionProvider>
        </I18nProvider>
      </ObservabilityProvider>
    </OptionalToastProvider>
  </AcceleratorProvider>
</ThemeShell>
