// packages/vue/src/components/CommandPalette/CommandPalette.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch, type CSSProperties } from 'vue';
import { activateOverlayFocus } from '@larose-ui/primitives';
import styles from '@larose-ui/styles/components/CommandPalette/CommandPalette.module.css';
import { cn } from '../../utils/cn';
import { useLaRosePortalTarget } from '../../composables/useLaRosePortalTarget';

export interface CommandPaletteItem {
  id: string;
  label: string;
  group?: string;
  keywords?: string[];
  onSelect: () => void;
}

const props = withDefaults(
  defineProps<{
    open: boolean;
    items: CommandPaletteItem[];
    placeholder?: string;
    emptyMessage?: string;
    class?: string;
    style?: CSSProperties;
    ariaLabel?: string;
  }>(),
  {
    placeholder: 'Search commands…',
    emptyMessage: 'No commands found',
    ariaLabel: 'Command palette',
  },
);

const emit = defineEmits<{ openChange: [open: boolean] }>();
const portalTarget = useLaRosePortalTarget();
const query = ref('');
const activeIndex = ref(0);
const inputRef = ref<HTMLInputElement | null>(null);
const dialogRef = ref<HTMLElement | null>(null);

const filtered = computed(() => {
  const q = query.value.trim().toLowerCase();
  if (!q) return props.items;
  return props.items.filter((item) =>
    [item.label, ...(item.keywords ?? [])].join(' ').toLowerCase().includes(q),
  );
});

const grouped = computed(() => {
  const groups: Array<{ group: string; items: Array<CommandPaletteItem & { flatIndex: number }> }> =
    [];
  let flatIndex = 0;
  const buckets = new Map<string, Array<CommandPaletteItem & { flatIndex: number }>>();

  for (const item of filtered.value) {
    const key = item.group ?? 'Commands';
    let bucket = buckets.get(key);
    if (!bucket) {
      bucket = [];
      buckets.set(key, bucket);
      groups.push({ group: key, items: bucket });
    }
    bucket.push({ ...item, flatIndex });
    flatIndex += 1;
  }

  return groups;
});

function close() {
  emit('openChange', false);
  query.value = '';
  activeIndex.value = 0;
}

function select(item: CommandPaletteItem) {
  item.onSelect();
  close();
}

watch(
  () => props.open,
  async (open, _prev, onCleanup) => {
    if (!open) return;
    query.value = '';
    activeIndex.value = 0;
    await nextTick();
    inputRef.value?.focus();
    const deactivate = activateOverlayFocus({
      container: dialogRef.value,
      onEscape: close,
      autoFocus: false,
    });
    onCleanup(() => deactivate());
  },
);

function onKeyDown(event: KeyboardEvent) {
  if (event.key === 'Escape') {
    event.preventDefault();
    close();
  } else if (event.key === 'ArrowDown') {
    event.preventDefault();
    activeIndex.value = Math.min(activeIndex.value + 1, Math.max(filtered.value.length - 1, 0));
  } else if (event.key === 'ArrowUp') {
    event.preventDefault();
    activeIndex.value = Math.max(activeIndex.value - 1, 0);
  } else if (event.key === 'Enter') {
    event.preventDefault();
    const item = filtered.value[activeIndex.value];
    if (item) select(item);
  }
}
</script>

<template>
  <Teleport v-if="open" :to="portalTarget">
    <div :class="styles.overlay" role="presentation" @click.self="close" @keydown="onKeyDown">
      <div
        ref="dialogRef"
        role="dialog"
        aria-modal="true"
        :aria-label="ariaLabel"
        :class="cn(styles.dialog, props.class)"
        :style="props.style"
      >
        <input
          ref="inputRef"
          type="search"
          :class="styles.search"
          :placeholder="placeholder"
          :value="query"
          role="combobox"
          aria-controls="larose-command-list"
          :aria-expanded="filtered.length > 0"
          :aria-activedescendant="
            filtered[activeIndex] ? `larose-command-${filtered[activeIndex]!.id}` : undefined
          "
          aria-autocomplete="list"
          @input="
            query = ($event.target as HTMLInputElement).value;
            activeIndex = 0;
          "
          @keydown="onKeyDown"
        />
        <ul
          id="larose-command-list"
          :class="styles.list"
          role="listbox"
          :aria-label="ariaLabel"
        >
          <li v-if="!filtered.length" :class="styles.empty" role="presentation">
            {{ emptyMessage }}
          </li>
          <template v-else>
            <li
              v-for="section in grouped"
              :key="section.group"
              :class="styles.group"
              role="presentation"
            >
              <div :class="styles.groupLabel">{{ section.group }}</div>
              <ul role="group" :aria-label="section.group">
                <li v-for="item in section.items" :key="item.id" role="presentation">
                  <button
                    :id="`larose-command-${item.id}`"
                    type="button"
                    role="option"
                    :aria-selected="item.flatIndex === activeIndex"
                    :class="styles.item"
                    :data-state="item.flatIndex === activeIndex ? 'active' : 'inactive'"
                    @click="select(item)"
                    @mouseenter="activeIndex = item.flatIndex"
                  >
                    {{ item.label }}
                  </button>
                </li>
              </ul>
            </li>
          </template>
        </ul>
      </div>
    </div>
  </Teleport>
</template>

// packages/react/src/CommandPalette/CommandPalette.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type KeyboardEvent } from 'react';
import { STANDARD_ACCELERATORS } from '@larose-ui/core';
import { activateOverlayFocus } from '@larose-ui/primitives';
import { useAccelerator } from '../accelerator';
import styles from '@larose-ui/styles/components/CommandPalette/CommandPalette.module.css';

export interface CommandPaletteItem {
  id: string;
  label: string;
  group?: string;
  keywords?: string[];
  onSelect: () => void;
}

export interface CommandPaletteProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  items: CommandPaletteItem[];
  placeholder?: string;
  emptyMessage?: string;
  className?: string;
  style?: CSSProperties;
  'aria-label'?: string;
}

function matchesQuery(item: CommandPaletteItem, query: string): boolean {
  if (!query) return true;
  const haystack = [item.label, ...(item.keywords ?? [])].join(' ').toLowerCase();
  return haystack.includes(query.toLowerCase());
}

export function CommandPalette({
  open,
  onOpenChange,
  items,
  placeholder = 'Search commands…',
  emptyMessage = 'No commands found',
  className,
  style,
  'aria-label': ariaLabel = 'Command palette',
}: CommandPaletteProps) {
  const [query, setQuery] = useState('');
  const [activeIndex, setActiveIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);

  const filtered = useMemo(
    () => items.filter((item) => matchesQuery(item, query.trim())),
    [items, query],
  );

  const close = useCallback(() => {
    onOpenChange(false);
    setQuery('');
    setActiveIndex(0);
  }, [onOpenChange]);

  const selectItem = useCallback(
    (item: CommandPaletteItem) => {
      item.onSelect();
      close();
    },
    [close],
  );

  useEffect(() => {
    if (!open) return;
    setQuery('');
    setActiveIndex(0);
    inputRef.current?.focus();
    return activateOverlayFocus({
      container: dialogRef.current,
      onEscape: close,
      autoFocus: false,
    });
  }, [open, close]);

  useEffect(() => {
    if (activeIndex >= filtered.length) {
      setActiveIndex(Math.max(filtered.length - 1, 0));
    }
  }, [activeIndex, filtered.length]);

  const filteredRef = useRef(filtered);
  const activeIndexRef = useRef(activeIndex);
  filteredRef.current = filtered;
  activeIndexRef.current = activeIndex;

  const handleNavigationKeyDown = useCallback(
    (event: KeyboardEvent<HTMLElement>) => {
      const items = filteredRef.current;
      const current = activeIndexRef.current;

      if (event.key === 'Escape') {
        event.preventDefault();
        close();
        return;
      }

      if (event.key === 'ArrowDown') {
        event.preventDefault();
        setActiveIndex((index) => (index + 1) % Math.max(items.length, 1));
        return;
      }

      if (event.key === 'ArrowUp') {
        event.preventDefault();
        setActiveIndex(
          (index) => (index - 1 + Math.max(items.length, 1)) % Math.max(items.length, 1),
        );
        return;
      }

      if (event.key === 'Enter' && items[current]) {
        event.preventDefault();
        selectItem(items[current]!);
      }
    },
    [close, selectItem],
  );

  useEffect(() => {
    if (!open) return;
    const active = document.getElementById(
      filtered[activeIndex] ? `larose-command-${filtered[activeIndex]!.id}` : '',
    );
    active?.scrollIntoView?.({ block: 'nearest' });
  }, [activeIndex, filtered, open]);

  if (!open) return null;

  const grouped = filtered.reduce<Record<string, CommandPaletteItem[]>>((acc, item) => {
    const group = item.group ?? 'Commands';
    acc[group] = acc[group] ?? [];
    acc[group]!.push(item);
    return acc;
  }, {});

  let itemIndex = -1;

  return (
    <div className={[styles.overlay, className].filter(Boolean).join(' ')} style={style} onClick={close}>
      <div
        ref={dialogRef}
        role="dialog"
        aria-label={ariaLabel}
        className={styles.dialog}
        onClick={(event) => event.stopPropagation()}
      >
        <input
          ref={inputRef}
          type="search"
          className={styles.search}
          placeholder={placeholder}
          value={query}
          role="combobox"
          aria-controls="larose-command-list"
          aria-expanded={filtered.length > 0}
          aria-activedescendant={
            filtered[activeIndex] ? `larose-command-${filtered[activeIndex]!.id}` : undefined
          }
          aria-autocomplete="list"
          onChange={(event) => {
            setQuery(event.target.value);
            setActiveIndex(0);
          }}
          onKeyDown={handleNavigationKeyDown}
        />
        <ul
          id="larose-command-list"
          className={styles.list}
          role="listbox"
          aria-label={ariaLabel}
        >
          {filtered.length === 0 ? (
            <li className={styles.empty} role="presentation">
              {emptyMessage}
            </li>
          ) : (
            Object.entries(grouped).map(([group, groupItems]) => (
              <li key={group} role="presentation">
                <div className={styles.groupLabel}>{group}</div>
                <ul role="group" aria-label={group}>
                  {groupItems.map((item) => {
                    itemIndex += 1;
                    const isActive = itemIndex === activeIndex;
                    return (
                      <li key={item.id} role="presentation">
                        <button
                          id={`larose-command-${item.id}`}
                          type="button"
                          role="option"
                          aria-selected={isActive}
                          className={styles.item}
                          data-state={isActive ? 'active' : 'inactive'}
                          onMouseEnter={() => setActiveIndex(itemIndex)}
                          onClick={() => selectItem(item)}
                        >
                          {item.label}
                        </button>
                      </li>
                    );
                  })}
                </ul>
              </li>
            ))
          )}
        </ul>
      </div>
    </div>
  );
}

export function useCommandPaletteShortcut(onOpen: () => void, enabled = true) {
  useAccelerator(STANDARD_ACCELERATORS.commandPalette, onOpen, {
    allowInEditable: true,
    enabled,
    id: 'larose-command-palette',
  });
}
